### ISSUE TITLE
Incompatible with Figura

### ISSUE THREAD

**Issue by vDekuu** [ZsoltMolnarrr/BetterCombat#101]
**Minecraft version** - 1.19
**Mod loader** - 0.14.8/0.14.9
**Mod version** - bettercombat-fabric-1.3.1+1.19.jar
**I am using the latest version available** - fabric loader: no better combat: yes

**Describe the bug**
The game crashes when you try to play with the figura nd better combat mod installed

**To Reproduce**
1. Install fabric loader 0.14.8/0.14.9 and minecraft version 1.19
2. Install the Better Combat and Figura mod
3. Click play

**Expected behavior**
I expected them to work together.

**Screenshot**
![error](https://user-images.githubusercontent.com/84327635/189486716-3cf9a5d7-e6e5-4c1c-a72a-a8292a77903e.png)

**Comment by ZsoltMolnarrr** [comment]
https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility
