### ISSUE TITLE
Issue with better combat occures on my server 

### ISSUE THREAD

**Issue by Accaliah** [ZsoltMolnarrr/BetterCombat#103]
I'm having this issue where when i kill enough mobs usually in my mob farm, my melee swings no longer register a hit instead pass through mobs harmlessly. if i unequip my weapons i can still deal damage using a punch. how do i keep this issue from occurring.

with a dual wield mod, (which is now uninstalled) i was able to attack with my offhand weapon, i figured it might have been a conflict with the dual wield mod but issue is still occurring even without it installed. 

its almost feels like the server doesn't like many mobs dying to a player in a short amount of time but to my knowledge there isn't a setting that affects that. open to suggestions and fixes for this issue.

**Comment by ZsoltMolnarrr** [comment]
Please fill the bug report form, and provide more information like screen recordings, and stable way of reproducing the issue.
