### ISSUE TITLE
Blacklist/whitelist config for ignoring grass

### ISSUE THREAD

**Issue by Rimevel** [ZsoltMolnarrr/BetterCombat#106]
Would love to be able to set what weapons swing through grass. Certain mods, like Farmer's Delight, have tools with unique interactions when breaking grass, so being able to toggle it off for those would be sweet.

**Comment by ZsoltMolnarrr** [comment]
We already have a feature in fallback compatibility for putting Farmer's Delight onto blacklist.
No additional change is expected.
