### ISSUE TITLE
[Crash] Probably a Crash when attacking a Skeleton Villager with a Naga Fang Dagger while sneaking

### ISSUE THREAD

**Issue by Catomax262** [ZsoltMolnarrr/BetterCombat#107]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - Better Combat 1.3.1, Savage and Ravage 4.0.0, Mowzie's Mobs 1.5.28
**I am using the latest version available** - Yes

**Describe the bug**
For some reason when i attack a Skeleton Villager with a naga dagger (while sneaking) and while scaled up with Band of Gigantism it freezes then crashes. Thought posting here was necessary because i see it mainly as a better combat issue.

**To Reproduce**
1. Spawn a Skeleton Villager
2. Attack it while sneaking with a naga dagger
3. Crash

**Expected behavior**
Not crashing and dealing damage normally

**Screenshots or video recordings**
n/a

**Additional context**
It was really odd because no such thing could've happened that normally. It may also been an interfering with The One Probe.
Crash Log: https://crashy.net/RvyuKtt3nFV7GYgDzlG6

**Comment by ZsoltMolnarrr** [comment]
This crashlog doesn't reference any Better Combat related problem.
I am sorry that I cannot help, please contact the developers of the crash related mod.
