### ISSUE TITLE
Attacking with a weapon doesn't cause the body's yaw to change

### ISSUE THREAD

**Issue by floral-qua-floral** [ZsoltMolnarrr/BetterCombat#11]
The vanilla arm-swinging animation causes the player's body to rotate to match their head, however performing a weapon attack does not do so. Since the hitbox of a weapon attack is based on the head's rotation, this can cause weird-looking behaviour, especially with narrow attacks like the Trident's thrust attack - if the body is facing straight north, but the player's head is turned northeast, the _animation_ will point north but the actual hitbox will point northeast. Forcing the body to match the head's yaw while attacking would fix this.

**Comment by ZsoltMolnarrr** [comment]
What a find!
