### ISSUE TITLE
Incompatibility with PlayerRevive

### ISSUE THREAD

**Issue by RedBeast1959** [ZsoltMolnarrr/BetterCombat#112]
PlayerRevive_FORGE_v2.0.10_mc1.19.2.jar (https://www.curseforge.com/minecraft/mc-mods/playerrevive)
bettercombat-forge-1.4.1+1.19.jar

PlayerRevive mode makes player down for certain amount of seconds when hp reach to zero. When player down, they crawl slowly and can't attack before someone revive them or die bleeding. But with Better Combat mode, player is still able to attack when downed.

According to PlayerRevive Mode developer, PlayerRevive cancels the ClickInputEvent when a player is downed([source](https://github.com/CreativeMD/PlayerRevive/blob/1.18/src/main/java/team/creative/playerrevive/client/ReviveEventClient.java#L62)). So somehow this is being ignored with Better Combat.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thank you for reporting, I will look into the issue.
