### ISSUE TITLE
[Mod Incompatability]  PlayerEx

### ISSUE THREAD

**Issue by MLMII** [ZsoltMolnarrr/BetterCombat#114]
PlayerEx has a str stat that adds damage to attacks, but for whatever reason it doesn't seem to do so with Better Combat installed.

Thank you for your time.

**Comment by ZsoltMolnarrr** [comment]
Hello!
I installed PlayerEx, leveled up strength to 10.
Before that I was hitting 5 with a Stone Sword.
After that I was hitting 7.5 with a Stone Sword.

Issue looks invalid.
Also not fillind issue form, hence closing.

Make sure to have installed the latest version of both mods.

**Comment by MLMII** [comment]
Sorry for wasting your time, I managed to stumble across the solution, I'm an idiot that missed the fact "Attribute Fix" is incompatible with "Data Attributes" so yeah, it was a completely invalid issue caused on my end.

Thank you for your time in looking into it.
