### ISSUE TITLE
[Forge 1.19] Exit code: -1 on start

### ISSUE THREAD

**Issue by sort50** [ZsoltMolnarrr/BetterCombat#116]
**Minecraft version** - 1.19
**Mod loader** - 41.0.38
**Mod version** - 1.4.1 +1.19
**I am using the latest version available** - yes

**Describe the bug**
Game crashes with exit code -1 on opening

**Screenshots or video recordings**
[crash-2022-09-25_13.35.57-client.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9640550/crash-2022-09-25_13.35.57-client.txt)

**Additional context**
at first i got this problem with the latest cloth config without the mod or player animations installed, i scrolled through versions until i find one that didn't crash on start then i tried all versions of bettercombat available.
for cloth config i used version cloth-config-7.0.72-forge
for player animation i used version player-animation-lib-forge-0.3.5
also here is a screenshot of the mods im trying to run with it. the game opens and plays without bettercombat
![Screenshot 2022-09-25 134454](https://user-images.githubusercontent.com/114337749/192139650-19629df9-3700-4d23-a52d-f3e8f73a5303.png)

**Comment by ZsoltMolnarrr** [comment]
Hello!
Sorry I cannot help, because the crashlog does not mention any Better Combat related issues.
It looks like an internal error of Forge mod loader.

Suggested solutions:
- Update all mods to **latest** version
- Install mods one by one
- Use Fabric loader, because it is much more stable
