### ISSUE TITLE
[Fabric 1.19.2] [1.4.2] Mod not fully disabling itself when no server side installation

### ISSUE THREAD

**Issue by MT729** [ZsoltMolnarrr/BetterCombat#117]
Minecraft version 1.19.2
Fabric Loader 0.14.9
Fabric API 0.62.0

Latest version of the mod says that it should fully disable on joining vanilla unmodded multiplayer servers.

[Video Link](https://youtu.be/SYIai_UvRZA)

**Comment by ZsoltMolnarrr** [comment]
Hey
Thanks for reporting, I will fix it.
