### ISSUE TITLE
[Fabric 1.18.2] [1.4.2] Compatibility with Bosses of Mass Destructions and Crawl

### ISSUE THREAD

**Issue by kingkuys2123** [ZsoltMolnarrr/BetterCombat#119]
Minecraft 1.18.2
Fabric Loader 0.14.9
Fabric Api 0.59.0

(I am using the latest version of the BC mod including it's required mods)

 - **Bosses of Mass Destructions** (https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction)
>> Can't hit Gauntlet's eye with weapons that has attack animations even if I aimed it directly at the center of the eye, projectile weapons (tridents (thrown), bows) still work tho.

 - **Crawl Mod** (https://www.curseforge.com/minecraft/mc-mods/crawl)
>> It is the same with the swimming issue #99, the animation, pose and attack direction
 
  - **Misc.**
>> for wands, most mods (in fabric at least) that has wands/staffs/scepters uses the right-click mouse button to use so maybe a feature/config that triggers the animation for wands with right-clicking?

**Comment by ZsoltMolnarrr** [comment]
Hello!

One problem per github issue please.
BoMD: https://github.com/miyo6032/bosses-of-mass-destruction/issues/79
#99 - Already registered
Misc - not the scope of Better Combat at all

**Comment by kingkuys2123** [comment]
Understandable, and erm forgot to add that the Crawl Mod has its own Crawling Animation, so yeah.
P.S. beautiful mod by the way, love it!
