### ISSUE TITLE
Adding weapons

### ISSUE THREAD

**Issue by Looodon** [ZsoltMolnarrr/BetterCombat#120]
**Is your feature request related to a problem? Please describe.**
Hey, I'm not a mod maker so I have very basic knowledge when it comes to setting mods up. I read your READ ME section and I was trying to find out how to make a weapon from another mod use the animation of your mod. Some weapons in the GreekFantasy (swords) use the animation of your mod except for the spear. I couldn't understand the language used in your READ ME as a code noob, so I was wondering if someone can do me the favor of guiding me in the right direction. Thanks!

**Comment by ZsoltMolnarrr** [comment]
Hello!
Please do not create github issue for such matter.
Please join the Discord server of the project instead.
