### ISSUE TITLE
[Forge 1.18.2] Dragon Survival Incompatibility

### ISSUE THREAD

**Issue by AStrangeMouse** [ZsoltMolnarrr/BetterCombat#121]
**Minecraft version** - 1.18.2
**Mod loader** - Forge 40.1.80
**Mod version** - bettercombat-forge-1.4.2+1.18.2

When playing as a dragon in the **Dragon Survival** mod (latest version), the first person model does not render correctly. Changing render settings around in both mods did not clear the issue.

Specifically, when playing as a dragon, the player model (normally visible when looking down on default config settings) in first person is entirely absent until you click to swing a weapon. The player model then briefly appears, taking up the entire screen for a moment, before disappearing again without playing the weapon animation. Other first person animations involving showing the dragon model are broken as well.

I can add screenshots or try recording the bug if necessary.

**Comment by ZsoltMolnarrr** [comment]
Invalid issue, since that mod is semantically incompatible.
https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility
