### ISSUE TITLE
Question about

### ISSUE THREAD

**Issue by Gamemassa** [ZsoltMolnarrr/BetterCombat#123]
I wasn't sure where to post this, but my friend and I had a question about your mod (we're using the Fabric version, but I doubt that'll change anything). We were wondering why all weapons including two-handed weapons show their stats as "when in main hand". I guess really this is a two-part question:

Part 1: Why do two-handed weapons say "when in main hand" ?
Part 2 (and more important): For weapons that can be dual-wielded, are the offhand stats the same, and if not, how do we view them?

**Comment by ZsoltMolnarrr** [comment]
1. This is the vanilla way how attributes work
2. They work the same in the offhand slot, try it and see. :)

Please use Discord for such Q n A.
