### ISSUE TITLE
[Fabric 1.19] Off Hand Item Breaks Main-Hand Item

### ISSUE THREAD

**Issue by verlixis** [ZsoltMolnarrr/BetterCombat#126]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric Loader 0.14.9
**Mod version** - 1.4.3
**I am using the latest version available** - Yes

**Describe the bug**
When dual wielding, if the item in the offhand slot breaks out of its durability, the item in the main hand slot breaks along with it.

**To Reproduce**
1. Equip a full durability sword on the main hand.
2. Equip a 1% durability sword on the off hand.
3. Attack.
4. Both item breaks.

**Expected behavior**
Only the off-hand item should break, not the item in the main hand.

**Comment by ZsoltMolnarrr** [comment]
This is a valid issue. Thank you for reporting!
