### ISSUE TITLE
[Forge 1.18.2] Events not fired when attacking with Better Combat weapon

### ISSUE THREAD

**Issue by vertexcubed** [ZsoltMolnarrr/BetterCombat#127]
**Minecraft version** - 1.18,2
**Mod loader** - Forge 40.1.69
**Mod version** - 1.4.4
**I am using the latest version available** - Yes

**Describe the bug**
When using a weapon modified by Better Combat, events related to attacking (notably ClickInputEvent and LeftClickEmpty) are never fired, which could break mod compatibility with any mods that rely on these events.

**To Reproduce**
Note: You will need to listen to these events in some way in order to confirm this behavior.

1. Join a world
2. Observe difference between attacking with item not affected by Better Combat vs. item affected by Better Combat

**Expected behavior**
a ClickInputEvent for the player's attack key is fired, and then LeftClickEmpty is fired if their attack misses.

**Screenshots or video recordings**
In this video I'm using a custom mod to simply send a message in chat when the two specified events are fired.
[Demonstration of the bug](https://www.youtube.com/watch?v=UZEsCw78dJo)

**Additional context**
Fixing this would fix mod compatibility issues with quite a few mods, notably Botania

**Comment by itsdinkd** [comment]
Terra Blade and Starcaller from botania do not allow it to fire its projectiles with Better Combat enabled.
