### ISSUE TITLE
No attack on the target

### ISSUE THREAD

**Issue by Dr-WeiAL** [ZsoltMolnarrr/BetterCombat#131]
**Minecraft version** - 1.18.2
**Mod loader** - forge
**Mod version** - 1.4.2
**I am using the latest version available** - yes

**Describe the bug**
Attacking directly below the target in certain directions does not hit the target

**To Reproduce**
1. Look down and attack

**Expected behavior**
It should be able to attack

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/47446553/194306353-8875f0e3-aabb-4c99-b0bb-3aeb22aff27a.png)
![image](https://user-images.githubusercontent.com/47446553/194306384-fcd64390-6982-45b2-92f0-e5e2af011d58.png)

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
The fix for this is already on the main branch.
It will be released soon.

**Comment by ZsoltMolnarrr** [comment]
Nope, looks like it still not solved.

**Comment by ZsoltMolnarrr** [comment]
Looks like the issue is within the collision detection algorithm.
It occurs when the weapon OBB contains the target AABB.
