### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by petrenko17** [ZsoltMolnarrr/BetterCombat#133]
**Minecraft version** - 1.19.2
**Mod loader** - Forge-43.1.34
**Mod version** - bettercombat-forge-1.4.4+1.19
**I am using the latest version available** - Yes

**Describe the bug**
A crash on startup. Game does not crash when only better combat is present. Crash apears in conjunction with journey map. I do not know whos bug this is, but the log cites bettercombat.

**Pastebin link**
https://pastebin.com/gfzKqSjh

**Comment by ZsoltMolnarrr** [comment]
Please make sure to update forge and all mods to the latest version.

**Comment by petrenko17** [comment]
I do have the latest version of Journeymap. It was causing simillar problem with another mod. I have replaced it since. I no longer experience this crash.
