### ISSUE TITLE
Alternate crit mechanic

### ISSUE THREAD

**Issue by Derpford** [ZsoltMolnarrr/BetterCombat#134]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
Jumping attacks are...weird. I get where the mod is coming from with not altering crits, and it *does* feel nice to learn the crit timing on a given weapon, but...thanks to how much critting means to fighting regular mobs like zombies and skeletons, it's annoying to not be able to crit as easily as in vanilla, especially in modpacks that aren't actually combat-focused (and I'm using BetterCombat anyway because it's a 100% improvement over vanilla combat)

**Describe the solution you'd like**
I want a toggle for Alternate Crit Mechanics. When toggled on, jump crits are disabled; instead, each time you deal damage, you add a certain amount of progress to a "Crit Meter".  When this Crit Meter is full, you emit particles, and your next attack will be a crit. The Crit Meter drains over time if you go more than 10 seconds without hitting anything (a full Crit Meter should take around 30s to completely drain). The amount added to the Crit Meter increases as the weapon's damage goes up, so that weapons that are slower and heavier can crit at around the same rate as faster but lower-damage weapons, and weapons that have better stats overall will crit more often.

**Describe alternatives you've considered**
* Random crits would also work, but wouldn't be as interesting, since there would be no way to predict or play around a character being able to crit.
* Alternatively, holding Sneak and Attack to "charge up" a crit would be an interesting mechanic, as it would reward players for positioning in ways that let them safely charge a crit. This would also *not* require any new animations to be made, while still making crits more heavily telegraphed.

**Additional context**
N/A

**Comment by ZsoltMolnarrr** [comment]
Sorry.
This will not be implemented.
Discord frequently asked channel covers this topic.
