### ISSUE TITLE
Add different hit sounds for different types of weapons

### ISSUE THREAD

**Issue by XM666-Dev** [ZsoltMolnarrr/BetterCombat#136]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I think that the same hit sound of all weapons in the original version is too monotonous, and different hit sounds should be added to them. For example, the hit sound of a hammer should be like "bang", and the hit sound of a sword should be like "slash".

**Describe the solution you'd like**
Add different hit sounds for different types of weapons

**Describe alternatives you've considered**
None

**Additional context**
None
I am not good at English，so this is the machine translation

**Comment by ZsoltMolnarrr** [comment]
Weapons already have different swing sounds.
Try MC Dungeons Weapons to see.
