### ISSUE TITLE
Looking directly up/down while attacking results in very awkward animations

### ISSUE THREAD

**Issue by dopadream** [ZsoltMolnarrr/BetterCombat#138]
**Minecraft version** - 1.19.2
**Mod loader** - Quilt
**Mod version** - Latest
**I am using the latest version available** - yes

**Describe the bug**
Looking up or down while attacking causes all body parts to rotate in incorrect ways resulting in very awkward looking animation.

**To Reproduce**
Self explanatory.

**Expected behavior**
Only the head and arms rotations should be influenced by the camera's yaw axis.

**Screenshots or video recordings**
https://cdn.discordapp.com/attachments/750169982721327228/1031819083555033108/Base_Profile_2022.10.18_-_01.39.09.03.mp4

**Additional context**
I understand that fixing this in a way that looks good might be hard or even near impossible, but I feel like it's worth reporting nonetheless. I play on a multiplayer server and its painfully noticeable.

**Comment by ZsoltMolnarrr** [comment]
Its a known issue, in my private backlog.
I am unable to improve it.

**Comment by Chuzume** [comment]
Is it impossible to set a limit on the body angle during an attack motion, or to prevent it from exceeding or falling below a certain angle?

**Comment by dopadream** [comment]
> Is it impossible to set a limit on the body angle during an attack motion, or to prevent it from exceeding or falling below a certain angle?

I will level with you and say no, it's not impossible, It is very doable. Obv that's up to the dev though
