### ISSUE TITLE
[1.18.2 Forge Bug]: Dragon Survival Incompatibility

### ISSUE THREAD

**Issue by kutuzovpuzov** [ZsoltMolnarrr/BetterCombat#139]
**Minecraft version** - 1.18.2
**Mod loader** - forge 40.1.84
**Mod version** - 1.4.4
**I am using the latest version available** - Yes

I played with a modpack where 94 mods are in. If I try to add one more, I get the crash-log, where the problem caused by bettercombat and dragonsurvival incompatibility. If I delete DS from my modpack and add some new mods, minecraft starts working. (start with more than 94 mods.) Configs and etc were cleaned and reinstalled.

@reDIrect conflict. Skipping bettercombat.mixins.json:PlayerEntityMixin->@reDIrect::getMainHandStack_Redirect(Lnet/minecraft/world/entity/player/Player;)Lnet/minecraft/world/item/ItemStack; with priority 1000, already redirected by dragonsurvival.mixins.json:MixinPlayerEntity->@reDIrect::getDragonSword(Lnet/minecraft/world/entity/player/Player;)Lnet/minecraft/world/item/ItemStack; with priority 1000

I want to play them both, so pls help.

[tlauncher_10_21_2022_17_27_52.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/9840221/tlauncher_10_21_2022_17_27_52.log)

**Comment by ZsoltMolnarrr** [comment]
https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility

**Comment by MarioSMB** [comment]
It's possible to play as a human with Dragon Survival, is the incompatibility a hardcoded one or is there something that can be done to make it possible for the mods to play together?  
If it's something that can be addressed on their end I can report it there instead, thanks.

**Comment by ZsoltMolnarrr** [comment]
I am not the developer of the underlying animation library.
To address the issue, the developers of Dragon Survival need to implement their player model changes in a more compatible way, like Figure did.

**Comment by MarioSMB** [comment]
Thanks for the heads up, I've let them know and pointed to Figura as an example.

**Comment by FirDragon** [comment]
This problem does not appear in the model. The reason is that Dragon Survival needs to implement the tool replacement function of [Claw Tools], so the attack hand weapon has been modified. And BetterCombat is also in order to achieve dual-wielding attacks. This caused compatibility issues.

**Comment by FirDragon** [comment]
I don't have any good ideas to be honest.
