### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by DonorKrovi** [ZsoltMolnarrr/BetterCombat#142]
**Minecraft version** - 1.18.2
**Mod loader** -  40.1.80 Forge
**Mod version** - [bettercombat-forge-1.4.4+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/4015126)
**I am using the latest version available** - yeah

**Describe the bug**
Idk

**To Reproduce**
1. Idk

**Expected behavior**

**Screenshots or video recordings**

**Additional context**
https://paste.gg/p/anonymous/fea65885c60b40b3ad5f3b9875e576ab

**Comment by ZsoltMolnarrr** [comment]
Please make sure to install the latest version of everything you use.
