### ISSUE TITLE
Pehkui - Compat

### ISSUE THREAD

**Issue by KdronTheShadow** [ZsoltMolnarrr/BetterCombat#143]
When using **_PEHKUI_** to resize entities it would be nice if the weapon hitboxes change scale and position based on the values of **_pehkui:base_**, **_pehkui:held_item_**, **_pehkui:width_**, **_pehkui:height_** . 

as a small player has the hitbox floating to far ahead of them and too large, and large players are literally engulfing the weapon's hitbox as it is too close and small.

This would result in any entity holding an item that is scaled by **_PEHKUI_** to have accurate hitboxs relative to the their size.

![2022-10-24_23 56 06](https://user-images.githubusercontent.com/88908714/197703780-6b1d982b-58b8-48a6-be64-3c00e90d8519.png)
![2022-10-24_23 56 35](https://user-images.githubusercontent.com/88908714/197703797-cfeec83c-d581-4687-8f80-1ef900dc15d5.png)

**Comment by ZsoltMolnarrr** [comment]
Pehkui has a basic compatibility for quite a while. Are you sure you are using the latest version of all mods?

**Comment by KdronTheShadow** [comment]
Well damn, apparently my pehkui is out of date; strange since I just downloaded it the other day, sorry about that must have grabbed the wrong file. i'll post an update after testing with newer files and if the issue is resolved close the request.

**Comment by KdronTheShadow** [comment]
After some testing I can conclude support works albeit very bare-bones. Attack hitbox's only scale off of one value; that being  _**pehkui:reach**_ (and consequently _**pehkui:base**_ as it alters reach under the hood) which makes sense but should definitely **not** be the only factor as there are lots of factors in **_PEHKUI_** that can and will change the apparent weapon's scale relative to the player; those being **_[ pehkui:width, pehkui:height, pehkui:held_item ]_**.

If I want the player's pehkui:height and pehkui:width to be different I set them directly to whatever values I want which then results in hitbox's that are unaltered. Where as when I change pehkui:reach it changes all factors of the weapon's hitbox **_[x, y, & z]_** scale.

Now this isn't major by any means but would help alot in allowing for even more possibilities such as a tiny player with ridiculously large weapons actually having huge hitboxs **without** affecting their reach.

Due to this, i'll be leaving this compat request up unless of course you deem it un-important and something you don't want to look into in the future. 

Sorry for the lengthy message & possibly wasting your time; 
Thank you for the wonderful mod and help.

**Comment by ZsoltMolnarrr** [comment]
No additional development is planned on this topic.
If you want to see it improved feel tree to post a PR, Pehkui integration is implemented in a single class.
