### ISSUE TITLE
Fallback not working for Tinkers Construct

### ISSUE THREAD

**Issue by Chrisigrimm** [ZsoltMolnarrr/BetterCombat#144]
**Minecraft version** - 1.18.2
**Mod loader** - Forge 40.1.73
**Mod version** - bettercombat-forge-1.4.5+1.18.2

First of all thanks for creating that awesome mod!
I tried to get [Tinkers Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct) weapons to work with the mod but it didnt get recognised. Weapons from the mod from Tinkers Survival did work out of the box with the fallback configuration.

**To Reproduce**
1. Install both mods
2. Try out weapons from Tinkers Construct

**Expected behavior**
Fallback working for the mod Tinkers Construct

**Comment by ZsoltMolnarrr** [comment]
Tinkers construct doesn't use different weapon IDs for different weapon types, hence it is not compatible.

**Comment by MarioSMB** [comment]
If you don't mind my asking, is there a technical reason for that? The ID of the scythes still contains "scythe", for example.  

EDIT: I'm asking since I intend to make a pull request to Tinker's Construct for support and I'd like to be able to provide a detailed explanation as to why they need to do it when Better Combat has compatibility fallbacks, thanks!

**Comment by ZsoltMolnarrr** [comment]
I am not sure what causes those items to be skipped by fallback compat.
Most probably some sequentiality problem.

**Comment by MarioSMB** [comment]
Hmm, that makes it a curious situation; Tinker's Construct is also a low level mod that doesn't deal with direct support (all their metals use Forge tags so no single mod is referenced), and it sounds like them needing to reference Better Combat may be considered a workaround to a bug somewhere, which they may not take too kindly.  
I wonder if this issue should be re-opened so the cause can be investigated? It would be interesting to find out which step is skipping their items, the solution to which may benefit general compatibility with mods.

**Comment by MarioSMB** [comment]
Pardon the double post, but I think this *might* be related to GENERIC_ATTACK_DAMAGE; I see no references to it in Tinker's Construct's codebase, and there's a forum here stating that ATTACK_DAMAGE is preferred: https://forums.minecraftforge.net/topic/115560-118-im-trying-to-find-the-listed-damage-attribute-of-a-sword/  
The fix might be to check both of these values (assuming GENERIC_ATTACK_DAMAGE is a classic way of checking the item's damage attribute?) before skipping them, hope that helps!
