### ISSUE TITLE
[1.19.2] Compat issue with Survivalist Essentials knife 

### ISSUE THREAD

**Issue by Baggytrousers27** [ZsoltMolnarrr/BetterCombat#145]
1.19.2
Forge 43.1.47
bettercombat-forge-1.4.5+1.19
SurvivalistEssentials-1.19+-4.1.0.0

Swingthrugrass prevents Survivalist essentials Crude Knife from cutting grass.
Perhaps an option to allow crouch to disable temporarily (alternatively a keybind toggle)?

**Comment by ZsoltMolnarrr** [comment]
You can fix this by adding those knives to the fallback compatibility config blacklist.

**Comment by Baggytrousers27** [comment]
Cheers and thanking you. What might be the syntax to do so? Mod author is trying to do per item/weapon instead of blacklisting all mod items.

        So there isn't a per-weapon configuration for the swing through grass feature. It is either global, or you have to blacklist the mod to prevent this. Maybe the author will change this in the future.

_Originally posted by @wendall911 in https://github.com/wendall911/SurvivalistEssentials/issues/3#issuecomment-1292197248_

**Comment by wendall911** [comment]
Ideally in the future, if there was a tag to allow a per-weapon grass, that would work. It would be a pretty simple addition.
