### ISSUE TITLE
Lance weapon from Epic Knights mod is broken

### ISSUE THREAD

**Issue by ConfusedToaster** [ZsoltMolnarrr/BetterCombat#146]
**Minecraft version** - 1.19.2
**Mod loader** - Forge 43.1.43
**Mod version** - bettercombat-forge-1.4.5+1.19

After I crafted a lance weapon, I tested it out on a zombie but it did nothing at all. I tried it riding on a horse, still nothing. And if related, it does have animations and some delay, but I'm not sure if it's from Epic Knights or from Better Combat.

**To Reproduce**
1. Install both mods (Forge)
2. Get a lance weapon (Any type)
3. Try to damage a mob with it

**Expected behavior**
Damage dealt to the mob registers

**Actual behavior**
Mob does not get damaged

(P.S, sorry for any mistakes I make, I'm still new around here.)

**Comment by ZsoltMolnarrr** [comment]
This is not an issue of Better Combat, I cannot do anything about it.
