### ISSUE TITLE
Wont even load minecraft

### ISSUE THREAD

**Issue by Icyy54** [ZsoltMolnarrr/BetterCombat#147]
**Minecraft version** - all
**Mod loader** -forge
**Mod version** - all
**I am using the latest version available** - yes

**Describe the bug**
Upon trying to launch forge with the better combat mod, it will just crash before getting the chance to launch. It says "exit code 1". I've tried loading this mod with different version combinations of better combat, player animator, and forge with none of them loading. I have confirmed that the mod and forge builds should be able to run yet they dont. I have 7 other mods that will all load just fine. it is only this one that seems to have trouble

**To Reproduce**
1-download required mods and forge

2-load the game

**Expected behavior**
the game and mods to load correctly

**Screenshots or video recordings**

**Additional context**

https://user-images.githubusercontent.com/116844015/198393625-797a09cc-507d-44e2-98b9-df51d479e391.mp4

**Comment by ZsoltMolnarrr** [comment]
You are missing a dependency: Cloth Config
