### ISSUE TITLE
Crash When Attacking While Dual Wielding

### ISSUE THREAD

**Issue by AshuraKuro** [ZsoltMolnarrr/BetterCombat#148]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric - 0.14.10
**Mod version** - 1.4.5
**I am using the latest version available** - Yes

**Describe the bug**
I will be swinging a weapon while dual wielding, I don't even have to be hitting anything, and then suddenly the game will just crash after a few swings.

**To Reproduce**
1. Launch Minecraft
2. Load into a world
3. Equip two weapons to dual wield *(For my example two iron swords)*
4. Attack a few times

**Expected behavior**
I did these steps multiple times, and each time my game crashed.

**Crash Log**

The text below is the crash log that I have also sent to the Better Combat discord server.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-11-01 23:56:52
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.28)
	at java.lang.System.arraycopy(Native Method)
	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.remove(Object2ObjectArrayMap.java:394)
	at net.minecraft.entity.attribute.EntityAttributeInstance.md0d9f1c$lambda$data_removeModifier$1$2(EntityAttributeInstance:674)
	at net.minecraft.entity.attribute.EntityAttributeInstance.actionModifier(EntityAttributeInstance:709)
	at net.minecraft.entity.attribute.EntityAttributeInstance.handler$bph000$data_removeModifier(EntityAttributeInstance:672)
	at net.minecraft.entity.attribute.EntityAttributeInstance.removeModifier(EntityAttributeInstance)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.entity.attribute.AttributeContainer.md0d9f1c$lambda$data_removeModifiers$1$1(AttributeContainer:611)
	at java.util.Map.forEach(Map.java:713)
	at net.minecraft.entity.attribute.AttributeContainer.handler$bpj000$data_removeModifiers(AttributeContainer:606)
	at net.minecraft.entity.attribute.AttributeContainer.removeModifiers(AttributeContainer)
	at net.bettercombat.logic.PlayerAttackHelper.setAttributesForOffHandAttack(PlayerAttackHelper.java:156)
	at net.minecraft.entity.LivingEntity.handler$zom000$getAttributeValue_Inject(LivingEntity:9663)
	at net.minecraft.entity.LivingEntity.getAttributeValue(LivingEntity)
	at net.minecraft.entity.player.PlayerEntity.getAttackCooldownProgressPerTick(PlayerEntity:2162)
	at net.minecraft.entity.player.PlayerEntity.getAttackCooldownProgress(PlayerEntity:2166)
	at net.minecraft.client.gui.hud.InGameHud.renderCrosshair(InGameHud:438)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:213)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:862)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.System.arraycopy(Native Method)
	at it.unimi.dsi.fastutil.objects.Object2ObjectArrayMap.remove(Object2ObjectArrayMap.java:394)
	at net.minecraft.class_1324.md0d9f1c$lambda$data_removeModifier$1$2(class_1324.java:674)
	at net.minecraft.class_1324.actionModifier(class_1324.java:709)
	at net.minecraft.class_1324.handler$bph000$data_removeModifier(class_1324.java:672)
	at net.minecraft.class_1324.method_6202(class_1324.java)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_5131.md0d9f1c$lambda$data_removeModifiers$1$1(class_5131.java:611)
	at java.base/java.util.Map.forEach(Map.java:713)
	at net.minecraft.class_5131.handler$bpj000$data_removeModifiers(class_5131.java:606)
	at net.minecraft.class_5131.method_26847(class_5131.java)
	at net.bettercombat.logic.PlayerAttackHelper.setAttributesForOffHandAttack(PlayerAttackHelper.java:156)
	at net.minecraft.class_1309.handler$zom000$getAttributeValue_Inject(class_1309.java:9663)
	at net.minecraft.class_1309.method_26825(class_1309.java)
	at net.minecraft.class_1657.method_7279(class_1657.java:2162)
	at net.minecraft.class_1657.method_7261(class_1657.java:2166)
	at net.minecraft.class_329.method_1736(class_329.java:438)
	at net.minecraft.class_329.method_1753(class_329.java:213)

-- Affected level --
Details:
	All players: 1 total; [class_746['AshuraKuro'/199, l='ClientLevel', x=4031.30, y=62.35, z=-5523.14]]
	Chunk stats: 4096, 644
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,34,-48), Section: (at 0,2,0 in 1,2,-3; chunk contains blocks 16,-64,-48 to 31,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 184320 game time, 186593 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, §b§lTetra_GUI_v.0.7.1, DragonRemastered[3][1.16.2-1.19.0].zip, replaymod_lang, Essential (fabric_1.19.2).jar

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 860583568 bytes (820 MiB) / 5771362304 bytes (5504 MiB) up to 16475226112 bytes (15712 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) RX Vega 10 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=30.0.13044.10001
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39883.30
	Virtual memory used (MB): 20403.72
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 23.63
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx15712m -Xms256m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.6
		adventurez: AdventureZ 1.4.17
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.3.49
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		backslot: BackSlot 1.2.10
			amecsapi: Amecs API 1.3.6+mc22w17a
		bagofholding: Bag Of Holding 4.1.4
			extensibleenums: Extensible Enums 4.0.0
		barteringstation: Bartering Station 4.0.2
		bclib: BCLib 2.1.2
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		bettercombat: Better Combat 1.4.5+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.1
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bettervillage: Better village 2.0.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		blast: BLAST 1.10
		boe: Blades Of Endaria 1.0.0
		bookshelf: Bookshelf 16.1.11
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.1+1.19
		craftpresence: CraftPresence 1.9.5
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.2+70efcffe90
		cull-less-leaves: Cull Less Leaves 1.0.6
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
			conditional-mixin: conditional mixin 0.3.0
		dataattributes: Data Attributes 1.2.7
		deathfinder: Death Finder 4.1.2
		diagonalfences: Diagonal Fences 4.2.3
		dynamicfps: Dynamic FPS 2.2.0
		easyanvils: Easy Anvils 4.0.5
		easymagic: Easy Magic 4.3.2
		easyshulkerboxes: Easy Shulker Boxes 4.3.3
		effective: Effective 1.4
			midnightlib: MidnightLib 0.5.2
		elementa: Elementa 558
		enchdesc: EnchantmentDescriptions 13.0.3
		entity_texture_features: Entity Texture Features 4.1.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		essential: Essential 10879+deploy-staging+g04722d17a
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		extrakeybinds: ThatRobins Extra Origins Keybinds 0.4.0+1.17-1.19.2
		extraorigins: Extra Origins 1.19-2
		fabric-api: Fabric API 0.64.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.21+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.2+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.0+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.2+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.32+70efcffe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.22+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.20+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.6+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.9+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.17+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.18+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.14+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.12+c0ae659d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.14+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.21+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.23+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.0+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.0+aae9039d90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.27+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.0+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.21+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fpsreducer: FPS Reducer 1.19.2-2.1
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
				mm: Manningham Mills 2.3
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		geckolib3: Geckolib 3.1.34
			com_eliotlash_mclib_mclib: mclib 19
		geodes: More Geodes 1.5.1
		icarus: Icarus 1.13
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.10
		impaled: Impaled 1.1.4
		indium: Indium 1.0.9+mc1.19.2
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.4.0
			io_github_douira_glsl-transformer: glsl-transformer 1.0.0-pre21.2
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.10.1
		itemmodelfix: Item Model Fix 1.0.3+1.19
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lazydfu: LazyDFU 0.1.3
		leavesbegone: Leaves Be Gone 4.0.0
		legendarytooltips: Legendary Tooltips 1.3.3
		libraryferret: Library ferret 3.0.0
		medievalmusic: Medieval Music Mod 1.19-1.8
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		nbteditor: NBT Editor 1.8.0
		notenoughanimations: NotEnoughAnimations 1.6.1
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		nyfsquiver: Nyf's Quivers Fabric-0.5.1-1.19.2
		onsoulfire: On Soul Fire 1.19-2
		org_jetbrains_annotations: annotations 13.0
		origins: Origins 1.7.1
			apoli: Apoli 2.6.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		origins-classes: Origins: Classes 1.4.0
		originsumbrellas: Origins: Umbrellas 1.5.4
		paxi: Paxi 1.19.2-Fabric-3.0
		pehkui: Pehkui 3.6.0+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickyourpoison: Pick Your Poison 1.0.11
			org_json_json: json 20211205
		player-animator: Player Animator 0.3.5
		playerex: PlayerEx 3.3.7
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		prism: Prism 1.0.3
		publicguiannouncement: Public Gui Announcement 4.3.2
		puzzleslib: Puzzles Lib 4.3.12
		raised: Raised 1.1.3
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		replanter: Replanter 1.3
		replaymod: Replay Mod 1.19.1-2.6.8
		roughlyenoughitems: Roughly Enough Items 9.1.562
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.2
		satin: Satin 1.9.0
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		simplyswords: Simply Swords 1.33-1.19.x
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.11+mc1.19.2-build.68
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		tiered: Tiered 1.1.3
		tradingpost: Trading Post 4.2.0
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		universalcraft: UniversalCraft 242
		universalenchants: Universal Enchants 4.2.8
		vigilance: Vigilance 264
		visualworkbench: Visual Workbench 4.2.0
		voicechat: Simple Voice Chat 1.19.2-2.3.12
		voidz: VoidZ 1.0.9
		windchimes: Windchimes 1.2.1
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		yet-another-config-lib: YetAnotherConfigLib 1.6.0
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
		zoomify: Zoomify 2.8.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.3
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.3
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.3
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.3
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.10-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) RX Vega 10 Graphics GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.44.10 30.0.13044.10001, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, file/§b§lTetra_GUI_v.0.7.1 (incompatible), file/DragonRemastered[3][1.16.2-1.19.0].zip
	Current Language: English (US)
	CPU: 8x AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx 
	Server Running: true
	Player Count: 1 / 8; [class_3222['AshuraKuro'/199, l='ServerLevel[World #1]', x=4031.30, y=62.35, z=-5523.14]]
	Data Packs: vanilla, Fabric Mods, file/BOE Compat, file/upgraded.zip (incompatible), HybridOrigins.zip
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Better Combat (bettercombat)

**Comment by ZsoltMolnarrr** [comment]
The issue does not happen when only Better Combat is installed.
Please provide information about which of your installed mods exactly causes the issue.
Without this I have no chance to fix the problem, and this issue will be just closed.

**Comment by AshuraKuro** [comment]
I have found the mod causing the crash, the mod is called "Not Enough Animations"
I am unsure of why it is causing the crash, as I've used it with better combat before, and it never caused this crash before.
I hope this helps.

**Comment by AshuraKuro** [comment]
The Mod "TieredZ" also causes this crash, again, I am unsure as to why as I have used it before with no issues.

**Comment by ZsoltMolnarrr** [comment]
I installed the latest versions of "Not Enough Animations" and "TieredZ", but I am unable to reproduce this issue.
