### ISSUE TITLE
I can't hit my cows. (Slab > Shield)

### ISSUE THREAD

**Issue by Psychodeus** [ZsoltMolnarrr/BetterCombat#149]
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 0.14.9
Environment: Singleplayer
Mod version: 1.4.5

## **Describe the bug**
I can't hit my cows if I put slab in front of me, but I need slab for my leather and beef farm.

## **Screenshots or video recordings**
https://imgur.com/a/hYNIcT1

**Comment by ZsoltMolnarrr** [comment]
Others have complained about such issues too.
This usecase is considered cheesing the game, the collision detection algorithm was not designed to handle this.

You need to set `"allow_attacking_thru_walls": true` in your server config to hit the cows thru such tiny hole.

No additional support is provided for this usecase.

**Comment by Psychodeus** [comment]
Where to set it? I'm playing in Singleplayer.

**Comment by ZsoltMolnarrr** [comment]
Read project readme.
