### ISSUE TITLE
Trident & Throwable Return to Off-hand

### ISSUE THREAD

**Issue by Maxz752** [ZsoltMolnarrr/BetterCombat#150]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I like dual wielding a sword & a trident, but When I throw the Trident with my off-hand it does not return (by Loyalty, or just by picking up) to said off-hand & the next empty inventory slot is chosen instead.

**Describe the solution you'd like**
If the trident is thrown from off hand, next time you pick-up the trident it will come back to off-hand.

**Describe alternatives you've considered**
Alternatively if the trident is thrown from a slot, reserve said inventory slot until you pick it up & place the trident there (a more flexible setup).

**Additional context**
To be more precise I ran into this case in the mod Medieval Weaponry - dual wielding a javelin & a sickle.
So it would be nice to have compatibility with this mod & general fallback compatibility with any throwables.

Note: There is one mod for 1.19 that does that ("bettertridentreturn"), but it's only for the trident, it's not actively developed (to my knowledge) & it has no compatibility with mods.

**Comment by ZsoltMolnarrr** [comment]
Hello!
I understand the issue, since being a very item specific issue it is rather difficult to fix it.

**Comment by ZsoltMolnarrr** [comment]
After further investigation I decided this feature will not be implemented, due to being outside of project scope and already existing specific solutions
