### ISSUE TITLE
Console Spam with Error: Modifier is already applied on this attribute!

### ISSUE THREAD

**Issue by NevendyND** [ZsoltMolnarrr/BetterCombat#151]
**Minecraft version** - 1.18.2
**Mod loader** - Fabric
**Mod version** - [bettercombat-fabric-1.4.5+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/4046669)
**I am using the latest version available** - From 1.18.2 yes

**Describe the bug**
Its seems like a Console Spam appears when you kill a Mob spawned from a Spawner.

**To Reproduce**
1. Kill Mobs from a Spawner.

**Expected behavior**
-

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/28860034/200438189-cc338bef-38d6-41cf-bcf8-f18e0875e29d.png)

**Additional context**
These Mods get used, its All of Fabric 5_1.5.1
https://drive.google.com/file/d/1nB5NQHG3NPJHQQzwhsmnenvQsVPD36mC/view
and some Custom Mods that got added over the Time and two Replace Mods.
https://drive.google.com/file/d/1aifpJYLnpfaDVx8P4496VsmtAlrnA_FP/view

**Comment by ZsoltMolnarrr** [comment]
Hello!
Sorry, no additional support is provided for 1.18.2.
Feel free to reopen the issue in case 1.19.X is affected.
