### ISSUE TITLE
[Alex's Mobs] Cannot hit Crocodile while death rolling

### ISSUE THREAD

**Issue by LolJohn11** [ZsoltMolnarrr/BetterCombat#152]
**Minecraft version** - 1.19.2
**Mod loader** - Forge 43.1.43
**Mod version** - 1.4.5
**I am using the latest version available** - Yes (for all mods involved)

**Describe the bug**
When using Better Combat with [Alex's Mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs) mod, hitting the crocodile mob  (`alexsmobs:crocodile`) while he is "grabbing" you is not possible with Better Combat, even though that behavior is intended in the "vanilla" combat system.

I _did_ manage to fix this behavior by setting `allow_attacking_mount` to `true`. It seems that the "crocodile grab" is coded to be seen as a "mounted" state by the game - you can even see the "horse hearts" appear on the HUD when a crocodile gets you.
But this fix resulted in an unwanted behavior where it is possible to hit a horse that you are riding, which is frustrating to say the least. Is there a way to fix the original issue? Maybe creating a blacklist\whitelist of entities for which the `allow_attacking_mount` will (not) apply?

**To Reproduce**
1. Spawn/find the crocodile mob (`alexsmobs:crocodile`)
2. Aggro the crocodile and let it "grab" you
3. Try hitting it with a weapon while in the "grabbed" state and fail, unless the `allow_attacking_mount` is set to `true`

**Expected behavior**
Should be possible to hit the crocodile during the "grab" state without the downside of having the possibility of hitting your own horse when riding it.

**Video recordings**
Better Combat behavior:

https://user-images.githubusercontent.com/49366383/201408000-e8ac936d-db89-4cd2-b6a4-914f42f9a174.mp4

Vanilla behavior:

https://user-images.githubusercontent.com/49366383/201408018-8a380524-2009-48c9-a6bc-33d432097bc5.mp4

**Comment by ZsoltMolnarrr** [comment]
Can you press shift to get free of the hold of the crocodile's hold?

**Comment by LolJohn11** [comment]
Yes, you can "dismount" the crocodile hold, but I see that as a sub-optimal solution compared to being able to hit the crocodile regardless of being "grabbed" or not.

**Comment by ZsoltMolnarrr** [comment]
The fact that you can break the attack by pressing shift at any point is I think a more serious issue.
https://youtu.be/gAY2SXpUCwU
Not to mention retaliating while a death roll is very unrealistic.

Putting personal opinions aside. Is there a technical solution you can suggest?
As far as I can see, the root cause of the problem, Alex mob using the mounting mechanics for something completely incorrect.

**Comment by LolJohn11** [comment]
In my original post I suggest the following solution:
>creating a blacklist\whitelist of entities for which the `allow_attacking_mount` will (not) apply

I don't know whether it is feasible to create such a workaround, so please do tell me if it would be possible to implement something like this. 
At least that way it won't have to be fixed on Alex's Mobs side, since there are 300+ open issues on GitHub for that mod, and I don't want to wait for an eternity for this to get a "fix" of some kind.

**Comment by ZsoltMolnarrr** [comment]
I understand your stance, and agree with it in general.
This is a low priority issue, I am working on more important stuff.
Anyone is free to implement an additional blacklist for this config, preferably based on regex.

**Comment by Proxwian** [comment]
Same is happening when you got attacked by Pinch Beetle from Twilight Forest
https://user-images.githubusercontent.com/31781674/209348787-50ba0297-24ac-460a-a57e-c78a9ed20efd.mp4
