### ISSUE TITLE
Strong/Heavy attacks

### ISSUE THREAD

**Issue by KapsiF** [ZsoltMolnarrr/BetterCombat#155]
**I read project readme, checked client side and server side configurations, and no such feature exists** 
- **YES**/no

**What is the feature request about? Please describe.**
- **Hold down the attack button for a heavy attack. Basically a charged normal attack**
- The attack would deal longer the attack is held. Player would be unable to use feint after releasing the attack from the "charging" state.
- The attack would serve as great extension of the simple yet expansive combat system. Would go greatly together with the parrying you mentioned in the readme (if it's still being considered),
 - Cool way to add even more depth in to the combat.

**Comment by ZsoltMolnarrr** [comment]
Explicitly stated on Better Combat Discord, no such feature will be added into this specific mod.
