### ISSUE TITLE
Compatibility with Visuality mod (1.18.2)

### ISSUE THREAD

**Issue by ygoroffici** [ZsoltMolnarrr/BetterCombat#156]
I tried using Better Combat 1.4.5 with Visuality 0.4.3, but whenever I hit any mob with hit particles (skeletons, chickens, villagers by default) set for it, those particles won't show up. 
I have tried on both Forge (using Visuality Reforged) and Fabric. The results were the same.

Not sure if this is a problem on Visuality's side, but checking its code there doesn't seem to be anything, hit particles show up whenever an entity is hit by a player (from what I could understand). So I'm posting this here.

I think using this mod with those particles would make combat a bit more satisfying so I hope this is not something too hard to fix. Thank you for the great mod, I love it 🙂

**Comment by ZsoltMolnarrr** [comment]
Hello!
Is this a problem on 1.19.2 too?

**Comment by ygoroffici** [comment]
Yep, same thing on both Fabric and Forge too.
