### ISSUE TITLE
The mod makes any weapon with slow attack speed unusable

### ISSUE THREAD

**Issue by Defetyre** [ZsoltMolnarrr/BetterCombat#157]
Axe was a weapon of chose for many players due to how consistently you can crit using them, keeping your dps at maximum. But for some reason, your mod ads an incredibly long windup phase that on top of removing said advantage makes them overall a harder to use weapon with less dps than a sword. A windup phase is already reflected in a knife-bar under cursor, you rise up your weapon for a strike right after you equip it or after making a swing with it. So there was no need to make this animation so long. 
Also your comment on #39 answers nothing, I would like to know why exactly there is nothing to do for this. If there is a limitation that makes slow weapons wind up way too long, then I think it would be worth it to overhaul this system, or atleast remove vanilla axes from the list of affected weapons. This is a glaring issue with you mod, I know it's called Better combat for simplicity reasons, but so far any weapons with slow enough attack speed was incredibly frustrating to use, I feel like I'm swinging a floaty balloon instead of a weapon, uncannily even and slow animation that is neither realistic or satisfying has nothing to do with improving the game, as the name of this mod states

**Comment by ZsoltMolnarrr** [comment]
Knife under the crosshair is not the windup phase, it repesents the cooldown.
Cooldown and windup are completely different things.

Axe are slow weapons by vanilla settings, my mod does not effect their speed.

All weapons have about 50% (of cd) windup.

I tested fighting with axe and glaive myself, both of them being slow but perfectly usable when adjusted, hence I the issue in this form is invalid.

I understand you dislike the windup, but that’s how it is for now.

**Comment by ZsoltMolnarrr** [comment]
For this kind of conversation this project uses Discord.
GitHub is primarily used as issue tracker.
