### ISSUE TITLE
game crash in 1.19.2 fabric

### ISSUE THREAD

**Issue by DarkCrystalll** [ZsoltMolnarrr/BetterCombat#158]
**Minecraft version** - 1.19.2
**Mod loader** - fabric
**Mod version** - 1.5.0+
**I am using the latest version available** - yes

**Describe the bug**
when I use the diamond sword hit a entity,game crash.the sword have some level skill by the mod "EnhancedArmaments" 
url:https://www.curseforge.com/minecraft/mc-mods/enhanced-armaments

**To Reproduce**
1. add level skill to sword
2. hit some entity
3.game crash

**Expected behavior**
fix it~

**Screenshots or video recordings**

**Additional context**
[minecraft-exported-crash-info-2022-11-29T14-25-03.zip](https://github.com/ZsoltMolnarrr/BetterCombat/files/10110338/minecraft-exported-crash-info-2022-11-29T14-25-03.zip)

**Comment by ZsoltMolnarrr** [comment]
The linked mod doesn't seem to have a 1.19.2 version.
How to reproduce this issue then?

**Comment by ZsoltMolnarrr** [comment]
The crashlog does not contain Better Combat related traces.
Looks like nothing to do on Better Combat side.
In case definitive evidence of the opposite surfaces, feel free to reopen the issue.

**Comment by DarkCrystalll** [comment]
I'm sorry that see the information just now. I found that the problem disappeared when I tried to reproduce the problem. I will continue to follow up this problem, which may be a potential mod problem. Thank you for your reply
