### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by M1hono** [ZsoltMolnarrr/BetterCombat#159]
**Minecraft version** - ?18
1.18.2
**Mod loader** - ?
forge
**Mod version** - ?
1.5.0
**I am using the latest version available** - ?
![2022-11-29_21 44 41](https://user-images.githubusercontent.com/82386665/204545720-59cbecd4-d238-4103-a634-1c127e7e32ee.png)
This is the screenshot when I attack in the first-person version.
This is the link of posture https://github.com/MrCrayfish/Posture
Can you solve this issue if available?

**Comment by ZsoltMolnarrr** [comment]
This issue occurs when a mod with faulty render state management is installed.
There is nothing I can do to fix it.

Please make sure to update to all of your mods to the latest version.
If this doesn't help, try disabling some of them to find out which one causes the problem.
