### ISSUE TITLE
[MedievalWeapons] Blocking Animation is broken with "Better Combat installed".

### ISSUE THREAD

**Issue by Foxificer** [ZsoltMolnarrr/BetterCombat#160]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - 1.5.1
**I am using the latest version available** - Yes

**Describe the bug**
2 Handed Medieval Weapons from the Medieval Weapons mod have a block feature and a custom animation. With this mod installed it breaks the blocking animation as shown below.

**To Reproduce**
1. Go to Minecraft
2. Grab a weapon that has a blocking function like the longsword
3. Hold RMB or the USE button you have set so you can block (Same key that you would normally use to block with a shield.)

**Expected behavior**
I expected to see the proper animation to go with the blocking.

**Screenshots or video recordings**

When I am blocking:
![unknown32](https://user-images.githubusercontent.com/95505194/205461860-658de6e2-9018-4d6b-b89c-f302a58931f7.png)

When I am not Blocking:
![unknown33](https://user-images.githubusercontent.com/95505194/205461872-02aea912-125d-4f10-8d4a-24931c18bc60.png)

**Comment by ZsoltMolnarrr** [comment]
I am sorry, this cannot be fixed on Better Combat side, this requires a bit of integration improvement in Medieval Weapons.
