### ISSUE TITLE
Damaging mounts while using BetterCombat

### ISSUE THREAD

**Issue by CasualJeremy** [ZsoltMolnarrr/BetterCombat#161]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - 1.5.1+1.19
**I am using the latest version available** - Yes

**Describe the bug**
When using weapons on a mount like a horse, when the hitbox of the weapon collides with the mount the mount takes damage when it shouldn't.

**Expected behavior**
To be able to use weapons such as the sword or axe to attack mobs while on horseback without hurting the mount.

**Additional context**
I'm not sure if this is important but the bug is for all weapons including modded ones like MedievalWeapons

**Comment by ZsoltMolnarrr** [comment]
Hello!
What is the state of server side config `allow_attacking_mounts` on your server?

**Comment by CasualJeremy** [comment]
Welp I seemed to have missed that, apologies
