### ISSUE TITLE
[Forge]crashes when I start up Minecraft its a  "exit code 1" what is says is " An unexpected issue occurred the game crashed we,re sorry for the inconvenience exit code 1"

### ISSUE THREAD

**Issue by Toasti58** [ZsoltMolnarrr/BetterCombat#162]
**Minecraft version** - ?
**Mod loader** - ?
**Mod version** - ?
**I am using the latest version available** - ?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**

**Additional context**

**Comment by Toasti58** [comment]
im using 1.19.2 with no other mods

**Comment by ZsoltMolnarrr** [comment]
Failed to fill issue form.

**Comment by Toasti58** [comment]
Wdym issue from? can you tell me were it is?
