### ISSUE TITLE
Cant Mine Wood with Axe

### ISSUE THREAD

**Issue by RisingKaiserGrey** [ZsoltMolnarrr/BetterCombat#163]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - 1.5.1
**I am using the latest version available** - Yes

**Describe the bug**
Using an Axe to break wood does attacks instead of mining

**To Reproduce**
Use any axe and start chopping down wood

**Expected behavior**
Wood breaks 

**Solution**
config\bettercombat\fallback_compatibility.json
Delete the axe from the text file
    {
      "item_id_regex": "axe",
      "weapon_attributes": "bettercombat:axe"
    },

**Comment by ZsoltMolnarrr** [comment]
Please make sure to use correct settings.
It definitely works.
