### ISSUE TITLE
[mincraft1.19.2][Forge 1.19.2][mod version is thr 1.19.2] using the latest versions of both forge and the mod version when i have the mod loaded up and load up Minecraft it loads for a bit than crashes with error code 1. and i am using the cloth con fig and the player animations 

### ISSUE THREAD

**Issue by Toasti58** [ZsoltMolnarrr/BetterCombat#164]
**Minecraft version** - ?
**Mod loader** - ?
**Mod version** - ?
**I am using the latest version available** - ?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Failing to fill issue form.
