### ISSUE TITLE
Game Crashes on Launch

### ISSUE THREAD

**Issue by greencow382** [ZsoltMolnarrr/BetterCombat#165]
Trying to launch the game comes up with this error

***The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot read field "allow_sweeping" because "net.bettercombat.BetterCombat.config" is null***

The thing probably causing this issue is the Comforts mod, since that's the only one relating to sleeping.

**Comment by ZsoltMolnarrr** [comment]
Failing to fill issue form.

**Comment by ZsoltMolnarrr** [comment]
Please try updating Better Combat.
