### ISSUE TITLE
Game Crashes on Startup

### ISSUE THREAD

**Issue by greencow382** [ZsoltMolnarrr/BetterCombat#166]
**Minecraft version** -1.18.2
**Mod loader** - Forge 40.1.85
**Mod version** - 1.5.1
**I am using the latest version available** - Yes

**Describe the bug**
Starting up the game, it kicks me out back to launcher, with error code -1, and this error:

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Cannot read field "allow_sweeping" because "net.bettercombat.BetterCombat.config" is null

**To Reproduce**
1. Open Launcher
2. Click Play
3. Window Opens.
4. Game Crashes with Error.

**Expected behavior**
The Game Launches like normal with no crashing.

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/59983054/206298223-90c5a7eb-43f2-40b4-b75d-cd2c03375c7b.png)

**Additional context**
Nothing Else.

**Comment by ZsoltMolnarrr** [comment]
Hello!
There is 1.5.2 out, trying to address this issue. Please try that.

**Comment by greencow382** [comment]
That worked! I didn't realize that 1.5.2 was out when I installed it yesterday, Off to go fix my other mods in this modpack, thank you!
