### ISSUE TITLE
Version 1.5.2 for 1.18.2 Code 1 Error

### ISSUE THREAD

**Issue by RustyMrGin** [ZsoltMolnarrr/BetterCombat#167]
**Minecraft version** 1.18.2
**Mod loader** Forge
**Mod version** 1.5.2 
**I am using the latest version available** For 1.18.2 Yes

**Describe the bug**
A clear and concise description of what the bug is. On game start up. Getting error code 1.

**Comment by RustyMrGin** [comment]
![image](https://user-images.githubusercontent.com/93096240/206356895-a2d5125f-4179-4987-b0d3-8c1d402c2588.png)

**Comment by RustyMrGin** [comment]
![image](https://user-images.githubusercontent.com/93096240/206357001-df53e2cd-6016-4ad1-b5c0-e6028059ca14.png)

**Comment by ZsoltMolnarrr** [comment]
Come on bro just read whats on the mod page....
![Screenshot 2022-12-08 at 9 00 44](https://user-images.githubusercontent.com/4989469/206391667-eee68cd8-3e10-4814-945b-b298e7572084.png)
![Screenshot 2022-12-08 at 9 01 10](https://user-images.githubusercontent.com/4989469/206391787-530c5696-11dd-4935-8490-6292bd432948.png)

**Comment by RustyMrGin** [comment]
Okay my bad I was asking i didn't see that no need to be a smart ass

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RustyMrGin** [comment]
I didn't say it was broken to fix it I was just asking

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RustyMrGin** [comment]
Simple question requires simple answer not a smart ass one

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
