### ISSUE TITLE
Frequently failure to start for no apparent reason

### ISSUE THREAD

**Issue by ArchiDreamZ** [ZsoltMolnarrr/BetterCombat#173]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - 1.5.2
**I am using the latest version available** - yes

**To Reproduce**
Just when I launch the game, it pops up "Error loading mods, 2 errors have occurred during loading"
But the strange thing is that sometimes it can start normally
I have added a lot of mods, but no matter how I exclude them, I can't find out which mod is in conflict, because each mod is normal when added with bettercombat and combatroll alone.

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/89504984/208227082-13fe739c-0640-4487-9e16-a3725a3dbedd.png)

**Additional context**
Description: Mod loading error has occurred
Here is the crash report：

[crash-2022-12-17_13.18.42-fml.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/10250983/crash-2022-12-17_13.18.42-fml.txt)

**Comment by ZsoltMolnarrr** [comment]
This looks like an internal problem of Forge mod loader, which I can do nothing about.
Forge is not recommended for use, exactly for this kind of unstable behaviour, compatibility issues and performance issues.

Please experiment with Forge on your on behalf. (You can try different Forge versions, and different JVM versions).
