### ISSUE TITLE
[FORGE 1.19.2] Cutting trees

### ISSUE THREAD

**Issue by Aulberon** [ZsoltMolnarrr/BetterCombat#175]
When using the option to disable mining with weapons, the axes stop working as tools, and it is no longer possible to use them to cut trees.
The solution can be as simple as making it so that, if we are sneaking, the configuration is ignored, being able to mine even with it active. Alternatively, it could become a new configuration option, giving us more freedom.
In addition to this solution, two others are creating a list of exceptions where the items on that list maintain normal behavior, or even making our attacks capable of "mining" blocks with each hit.

**Comment by ZsoltMolnarrr** [comment]
The feature works as intended. It is a soft battle mode.
No sneak related thing will be added.
