### ISSUE TITLE
[Question/Request] Could Illagers kick my ass with cool animations?

### ISSUE THREAD

**Issue by neutralboolean** [ZsoltMolnarrr/BetterCombat#178]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
Could Illagers be made to use the same weapons/animations as the player?

**Comment by neutralboolean** [comment]
Sorry to crack open an issue on what is essentially a comment, so feel free to close as appropriate.

**Comment by ZsoltMolnarrr** [comment]
Sorry it is not possible. The depended animation library doesn't support animating mobs.
