### ISSUE TITLE
Bukkit / Spigot / Paper Plugin?

### ISSUE THREAD

**Issue by rght925h** [ZsoltMolnarrr/BetterCombat#179]
Would it be feasible to convert the server-side addon to a, e.g., Paper plugin?
Sorry if this sounds naive, I have no idea how difficult this would be :) 

At any rate, an absolutely fantastic mod. Thank you!

**Comment by ZsoltMolnarrr** [comment]
Hello!

I am not familiar with Bukkit / Spigot / Paper so I cannot say anything about technical feasibility.
I myself am not interested in these, hence I am not going to develop or maintain such code.

This is an open source project, with extensive documentation, anyone is free to implement a server plugin as a separate project. :)
