### ISSUE TITLE
Tinker's Construct compatibility

### ISSUE THREAD

**Issue by MarioSMB** [ZsoltMolnarrr/BetterCombat#180]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO
YES

**Is your feature request related to a problem? Please describe.**
Support for [Tinker's Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct) is currently broken.

**Describe the solution you'd like**
As a followup to #85, requesting support for Tinker's Construct.

**Describe alternatives you've considered**
The linked issue points to a datapack that can be used in the meantime, but this is obviously a subpar workaround.

**Additional context**
The Tinker's Construct developers have stated they will not add support for this mod https://github.com/SlimeKnights/TinkersConstruct/issues/4993

**Comment by ZsoltMolnarrr** [comment]
It goes the other way around my friend.
Better Combat is a low level mod, offering multiple kind of APIs. Tinkers Construct should add compatibility.

**Comment by MarioSMB** [comment]
Sadly Tinker's Construct has stated they will not be adding support for Better Combat.  
Here's hoping something can be done about the fallbacks not working...

**Comment by ZsoltMolnarrr** [comment]
I am sorry for that.
Please understand that Better Combat is not adding or referencing any content, it is a behaviour/mechanic only mod. This is why it is offering an API. Adding compatibility from Better Combat side is not feasible for several reasons (https://github.com/ZsoltMolnarrr/BetterCombat#basics).

You can join our Discord server, where you can download a compatibility data pack. As far as I know it works well.

**Comment by MarioSMB** [comment]
I see, that is understandable. Unfortunately I don't see datapacks as a "solution" to problems like this, so I'll see if Tinker's Construct will accept a pull request to make the mods compatible - it looks like your API makes this incredibly trivial and easy to maintain for them.  

Thank you for the feedback.
