### ISSUE TITLE
Wiki links to API containers broken

### ISSUE THREAD

**Issue by MarioSMB** [ZsoltMolnarrr/BetterCombat#181]
**Minecraft version** - N/A
**Mod loader** - N/A
**Mod version** - N/A
**I am using the latest version available** - N/A

**Describe the bug**
The wiki links to [AttributesContainer](https://github.com/ZsoltMolnarrr/BetterCombat/blob/main/src/main/java/net/bettercombat/api/AttributesContainer.java) and [WeaponAttributes](https://github.com/ZsoltMolnarrr/BetterCombat/blob/main/src/main/java/net/bettercombat/api/WeaponAttributes.java) are currently broken at https://github.com/ZsoltMolnarrr/BetterCombat#custom-attributes

**To Reproduce**
1. Visit the wiki
2. Check the AttributesContainer and WeaponAttributes links

**Expected behavior**
I'm not sure what the desired behaviour is now - presumably the API has changed to require different links?

**Screenshots or video recordings**
N/A

**Additional context**
A lot of the requested information doesn't apply to the issue I'm reporting so I've left it as N/A to avoid the issue being closed outright.  
The second link to [WeaponAttributes](https://github.com/ZsoltMolnarrr/BetterCombat/blob/1.19.3/common/src/main/java/net/bettercombat/api/WeaponAttributes.java) is functional but it appears to be version specific.

**Comment by ZsoltMolnarrr** [comment]
Should be fixed :) Feel free to reopen if not
