### ISSUE TITLE
Error occurred during loading

### ISSUE THREAD

**Issue by VanilaBOI** [ZsoltMolnarrr/BetterCombat#182]
**Minecraft version** - 1.19.2
**Mod loader** - 1.19.2-forge-43.2.2
**Mod version** - 1.5.4
**I am using the latest version available** - Yes

**Describe the bug**
I used to be able to start the game with no problem and play on my server but a couple of days ago, I got a crash and since then, I get 2-3 Issues/crashes while starting the game. It's always the same thing, something about a zip file being closed and it's either with better combat, combat roll or both.

**To Reproduce**
I wouldn't know how, because if I put all the mods that I use in a curseforge instance the problem never shows up and as I said this only started once I got a crash.

**Expected behavior**
I would love to be educated on how to remove this annoyance from my Minecraft client and avoid it in the future.

**Screenshots or video recordings**
![client sided](https://user-images.githubusercontent.com/86358160/212461667-ab9fad81-49a6-4132-966d-be01af073205.PNG)

**Additional context**
[crash-2023-01-14_08.25.44-fml.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/10416875/crash-2023-01-14_08.25.44-fml.txt)

**Comment by ZsoltMolnarrr** [comment]
This is an issue of Forge modloader itself. I cannot do anything about it.
Even Forge recommends you to use a different version.

![Screenshot 2023-01-14 at 10 52 32](https://user-images.githubusercontent.com/4989469/212466293-213055af-20be-4dba-affa-ed83d7aaf6b7.png)

**Comment by VanilaBOI** [comment]
Thanks, that did it!
