### ISSUE TITLE
Animation glitch with double axes

### ISSUE THREAD

**Issue by MarioSMB** [ZsoltMolnarrr/BetterCombat#183]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 40.2.0
**I am using the latest version available** - Yes

**Describe the bug**
When using weapons with the "bettercombat:double_axe" attribute, the swing to the right is a bit glitchy; the animation plays twice in rapid succession. This does not occur with regular axes.

**To Reproduce**
1. Add the "bettercombat:double_axe" attribute to a weapon
2. Attack with the weapon
3. Watch the second swing animation

**Expected behavior**
Smooth animations.

**Screenshots or video recordings**
I can provide a short video showing off the issue if requested, though this is with the default attributes so it should be reproducible.

**Additional context**
None to note.

**Comment by ZsoltMolnarrr** [comment]
Is this specific to Forge?
Is there a similar problem using Fabric + Iris?

**Comment by MarioSMB** [comment]
I'm not sure in that regard as I've never used Fabric. I don't have Oculus installed as it crashes on Forge 1.18.2, if that helps.

**Comment by ZsoltMolnarrr** [comment]
No action can identified for this issue.
Anyone who dislikes how double axe animation looks, is free to submit a new one :)
(Tooling, resources and documentation are all available in the repository)

**Comment by MarioSMB** [comment]
I'll make a video of it soon, it looks like a visual glitch.

**Comment by ZsoltMolnarrr** [comment]
Are you using Optifine?

**Comment by MarioSMB** [comment]
No, but I am using Rubidium - I'll be sure to try it without any other mods when recording.

**Comment by MarioSMB** [comment]
Can confirm that it's reproducible without any extra mods - I used Simply Swords but modified the .jar file directly to replace the weapon's attributes with only "bettercombat:double_axe":  
https://youtu.be/5hi72eVNv6k  
Be sure to play it in slow motion if the issue isn't apparent. The "double swing" it does going from right to left is what I'm referring to.

Also confirmed that it occurs in 1.19.2 versions of the mod. Didn't try with Fabric as I don't have a testing environment for it.

**Comment by ZsoltMolnarrr** [comment]
Have you seen this animation in third person?

**Comment by MarioSMB** [comment]
I see... it is quite difficult to convey that the character is doing a spinning attack there, but seeing as this is intended behaviour we can consider this resolved. Apologies for the false positive!
