### ISSUE TITLE
Crash when running version 1.19.2 better combat mode Trouble code is 1

### ISSUE THREAD

**Issue by wonjin771** [ZsoltMolnarrr/BetterCombat#185]
**Minecraft version** - 1.19.2
**Mod loader** - forge
**Mod version** - 1.5.4
**I am using the latest version available** - yes

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**
If applicable, add screenshots t
![Desktop Screenshot 2023 01 19 - 17 25 01 09](https://user-images.githubusercontent.com/123061886/213391462-feb9ee81-e5f1-49a1-be6a-e005fa81f671.png)
o help explain your problem.

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
This is an installation error on your end.
Steps to resolve:
- Install required mods for Better Combat (Cloth Config, Player Animator)
- Make sure Fabric and Forge versions and not mixed
- User **recommended** version of Forge
