### ISSUE TITLE
Compatibility issue for attack range

### ISSUE THREAD

**Issue by charlyb01** [ZsoltMolnarrr/BetterCombat#186]
**Minecraft version** - Any
**Mod loader** - Fabric
**Mod version** - Any
**I am using the latest version available** - Yes

**Describe the bug**
When playing with other mods changing reach/attack range attributes, this mod will take over. Indeed, Better Combat is not using [Reach Entity Attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes) Fabric API.

**To Reproduce**
1. Install [sihywtcamc](https://www.curseforge.com/minecraft/mc-mods/sihywtcamc) along with Better Combat.
2. Change reach attributes of weapons with the first mod (or use default updated ones).
3. Try to attack with them and notice you can't attack from expected reach.

**Expected behavior**
Setting a longer reach in Combat mod should apply when using Better Combat.

**Additional context**
Maybe a priority should be set if both mods change the range.

**Comment by ZsoltMolnarrr** [comment]
Reach Entity Attributes is a parallel implementation.
It is incompatible for the same reason as Iris being incompatible with Optifine.

Mod compat lists this as explicitly incompatible.
https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility
