### ISSUE TITLE
Speed Enchantments can break the animations

### ISSUE THREAD

**Issue by TaeoG** [ZsoltMolnarrr/BetterCombat#187]
Versions:
Better Combat 1.5.3 Forge
Forge 43.2.0
PlayerAnimator 0.4.0
ClothConfig 8.2.88

Issue:
Some speed enchantments can cause the animation to break entirely, not allowing you to attack. After attempting to, all your other attack animations increase in speed even without enchantments on them.

To recreate, I put Faster Attack V (Ma Enchants), Speed Enchantment III (So Many Enchants!!!), Light Blade III (So Many Enchants!!!) on a sword and for giggles also equipped the Feral Claws (Artifacts). Probably not all of these are necessary but its sure to break like this. In vanilla the weapon becomes fast but not crazy, and functions normally. With Better Combat, the animation is so fast it almost can't be seen, and will break and refuse to let you swing again, as noted above.

**Comment by ZsoltMolnarrr** [comment]
Next update will come with attack speed cap.

**Comment by ZsoltMolnarrr** [comment]
Fixed by 1.5.5, feel free to reopen if not.
