### ISSUE TITLE
Does not work on Mod Added Equipment

### ISSUE THREAD

**Issue by ardissaps** [ZsoltMolnarrr/BetterCombat#19]

**Comment by ardissaps** [comment]
Maybe you can use #c:tool tag so it work with all?

**Comment by ZsoltMolnarrr** [comment]
https://github.com/ZsoltMolnarrr/BetterCombat#-integrate-your-mod

**Comment by ardissaps** [comment]
Do I need to add everysingle sword one by one?

**Comment by ZsoltMolnarrr** [comment]
Yes, just like how minecraft textures and models are specified.

**Comment by ardissaps** [comment]
Sure I will test on my own with single sword then request mod authors to integrate it, I actually not using many equipment mods, only :
1. [MythicMetal](https://www.curseforge.com/minecraft/mc-mods/mythicmetals)
2. [VariantTool and Weaponry](https://www.curseforge.com/minecraft/mc-mods/variant-tools-and-weaponry-tools-and-swords)
