### ISSUE TITLE
Bows acting very strange

### ISSUE THREAD

**Issue by Mr-Syntax** [ZsoltMolnarrr/BetterCombat#190]
ive included your mod in this pack
https://www.curseforge.com/minecraft/modpacks/hack-n-craft

and all is well with the melee, its super cool that like in general every 3 attacks does more damage
but this seems to apply to bows aswell? is this intended?
its acting super weird in my pack sometime doubling damage, sometime only 1 damage?
is this the intended behavior?

**Comment by ZsoltMolnarrr** [comment]
Failing to use issue form, it’s not there for deleting.
Also specify what exactly the problem is, hopefully with some footage or image attached.

**Comment by Mr-Syntax** [comment]
okay so i narrowed it down to being when this mod called tiered is installed then it just starts acting completely weird have no idea why tho :-|
https://www.curseforge.com/minecraft/mc-mods/tiered
