### ISSUE TITLE
Bows with inconsistent damage

### ISSUE THREAD

**Issue by Mr-Syntax** [ZsoltMolnarrr/BetterCombat#191]
Minecraft 1.19.2
Fabric 0.14.12
bettercombat-fabric-1.5.5+1.19.jar
Currently using the newest version

**Describe the bug**
it seems like the combo system which works for melee also is applied to bows, and sometimes its just straight up bugged with no damage at all

Here is a small clip of the problem
https://drive.google.com/file/d/1K_P7H0bSux_8ABnKUD2LnL4yszu3E8fT/view?usp=share_link

**To Reproduce**
I have released the pack with bug present, i didnt notice it because i was testing mostly melee stupid me :-|
https://www.curseforge.com/minecraft/modpacks/hack-n-craft

**Expected behavior**
i would expect a flat damage each time the bow is fully charged, the combo damage variations make sense with melee but not ranged IMO

small side note, if you could make bows and crossbows count as two handed so they cant be dual wielded that would be awesome
the only other combat mod in the pack should be this one
https://www.curseforge.com/minecraft/mc-mods/sihywtcamc
i have turned off the bow nerf from that mod in the config

**Comment by ZsoltMolnarrr** [comment]
Better Combat does’t modify ranged weapon mechanics at all.
What the video shows is nothing but Vanilla bow behavior.
Where exactly do you see difference compared to Vanilla?

**Comment by Mr-Syntax** [comment]
well in vanilla its a consistent flat damage when you draw the string all the way back right?
or do i remember that wrong?
but the ones that dont give of a damage indicator actually do 0 damage which is very strange
its acting like its running through the combos melee do, like 2 low damage hits and then 1 high damage hit

**Comment by ZsoltMolnarrr** [comment]
Putting vanilla client and Better Combat side by side, didn't result any difference for me.
Vanilla bows have a slightly randomized damage, not completely flat.
More over, the damage output depends on when you release the arrow. If its too early it will to do less damage, if at the perfect time it will do critical damage.

The video you sent does seem to be correlating to this mechanic entirely.

**Comment by Mr-Syntax** [comment]
okay so i narrowed it down to being when this mod called tiered is installed then it just starts acting completely weird have no idea why tho :-|
https://www.curseforge.com/minecraft/mc-mods/tiered

opened a ticket on the fork aswell
https://github.com/Andrew6rant/tiered/issues/10
