### ISSUE TITLE
The problem of attack distance and main and auxiliary hands

### ISSUE THREAD

**Issue by 48004800** [ZsoltMolnarrr/BetterCombat#192]
**Minecraft version** - 1.19.2
**Mod loader** - forge
**Mod version** - 1.5.5
**I am using the latest version available** -  yes

**Describe the bug**
The problem is between mods, not the problem of better combat itself

https://www.curseforge.com/minecraft/mc-mods/apotheosis

Apotheosis mod is just an example. Almost all mods that provide similar functions have this problem

Better combat resets the attack distance of the weapon, making the modification of the attack distance by other mods invalid. 

Apotheosis mod can improve the attack distance of the weapon, but it is invalid under the influence of better combat
If the weapon itself can improve the attack distance, I can change the json file to achieve this

The problem is that some mods provide an improvement in attack distance rather than aiming at the weapon itself. For example, Apotheosis's affix. In this case, the effect of affix to increase attack distance is invalid.

Another problem is that some weapons need to play a role in the auxiliary hand, while some weapons need to be held by both hands
If it happens that this weapon needs to be held by both hands

In this case, even if the weapon is placed in the auxiliary hand slot, it will not work

**Comment by ZsoltMolnarrr** [comment]
Better Combat discord frequently asked:
**Why are my attack range increasing buff/enchantments/gems not working?**
Better Combat defines its own attack range attribute. This attack range is designed to be a non changeable, intrinsic property of weapons.
From a game design perspective, increasing attack range of melee attacks with buffs/enchants/gems etc. is an absolutely unbalanceable mechanic.
No wonder no properly designed game (I know of) does increase attack range in such way. In every case this is an intrinsic property of the weapon or attack style.
To experience weapons with significantly different range, install some weapon mods adding a wider variety of weapons. Check out partnering mods.


Moreover https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility references this explicitly.
