### ISSUE TITLE
game crashes when I use it, Im on 1.19.2

### ISSUE THREAD

**Issue by kcazz8** [ZsoltMolnarrr/BetterCombat#193]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - ?
**I am using the latest version available** - ?

**Describe the bug**
crashes when I open the game
literally just crashes, even when it's the only mod in the folder
**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Make sure to install dependencies.

<img width="924" alt="Screenshot 2023-01-27 at 23 34 55" src="https://user-images.githubusercontent.com/4989469/215219053-e98b0e8f-68fb-4a26-ad99-047ac70e0cf5.png">
