### ISSUE TITLE
Option to add/remove damage based on what part of a combo is done

### ISSUE THREAD

**Issue by sentwayfarer** [ZsoltMolnarrr/BetterCombat#196]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO

**Is your feature request related to a problem? Please describe.**
Not exactly, just more of a quality of life thing for other modders

**Describe the solution you'd like**
For combos (like the claymore or claw), I'd like to see an option for a damage multiplier based on what move is done.

**Describe alternatives you've considered**
No alternatives, probably not possible without making an entirely new mod

**Additional context**
Not needed

**Comment by ZsoltMolnarrr** [comment]
Attack specific damage multiplier already exists:
https://github.com/ZsoltMolnarrr/BetterCombat/blob/029257c24fd6f7e0ec7df9009c1478c215657540/common/src/main/java/net/bettercombat/api/WeaponAttributes.java#L117
https://github.com/ZsoltMolnarrr/BetterCombat#custom-attributes

Claymore is a good example that uses it.

What exactly should be different about it?

**Comment by sentwayfarer** [comment]
Oh, never saw this! Thanks for the info.
