### ISSUE TITLE
[Forge 1.19.2] Many particles, including Vanilla ones such as Warden's Sonic Shrieks, do not render with Better Combat installed

### ISSUE THREAD

**Issue by Reshirou** [ZsoltMolnarrr/BetterCombat#198]
**Minecraft version** - 1.19.2
**Mod loader** - Forge 43.2.3
**Mod version** - 1.5.5
**I am using the latest version available** - Yes

**Describe the bug**
Note: I may be misusing the word "particle." These effects LOOK like particles, but I could be mistaken:

Many projectile particles, or presumably particles in general but most evidently projectile based one, simply do not render when Better Combat is installed. Particles from the Warden's Shriek do not work. Particles from Create Misc and Things' Spout Guns don't work (although the Lava one does have one working visual, but it is missing most of them.) Etc.

**To Reproduce**
Challenge a Warden
or
Install the Warden Horn mod and use it (faster to test, but bug still happens to Warden without it installed.)
or
Install Create Misc and Things mod, grab any spout gun, and use it (bug still happens to Warden without it installed.)

**Comment by ZsoltMolnarrr** [comment]
Hello!
Does this issue happen on Fabric versions?

**Comment by Reshirou** [comment]
Hey, yes, this issue is for both versions, so it's not an obscure Forge incompat

**Comment by ZsoltMolnarrr** [comment]
I am unable to reproduce this issue.
Using Fabric 1.19.2 + Better Combat warden attacks look like as they should.

https://user-images.githubusercontent.com/4989469/216615931-c3767450-f236-4366-a61d-c824b596c8ef.mov

Please provide some footage about the problem.

**Comment by Reshirou** [comment]
Odd; here is a comment left by someone who is using Fabric and came across what seems to be the exact problem as me
https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus?comment=518
I don't use Fabric myself, so I said "yes it happens on Fabric" without testing, because I knew through checking the comments that someone else had a particle render issue, and it was with the Fabric version

Here is video of the Warden boom not rendering, on Forge 1.19.2 43.2.3

https://user-images.githubusercontent.com/19141286/216693997-2b5834f4-46ec-4094-bd88-2edc3ad5e2af.mp4

**Comment by ZsoltMolnarrr** [comment]
Are you entirely sure this is not some Vanilla bug?
Better Combat doesn't even touch particle rendering.

**Comment by Reshirou** [comment]
Ok, your total confusion led me to think "how could this be on my end?" And I did find something.

When I delete my custom config files, such that they regenerate as standard, the particles return. Somehow, editing something in the Better Combat configs leads to particles disappearing for me and the person I linked before. I guess I'll figure out which setting is edited to cause that and get back to you. Note that I'm gonna be using WardenHorn mod to instantly see the boom instead of waiting for an actual warden lol.

**Comment by Reshirou** [comment]
it's "isSweepingParticleEnabled": false

in hindsight, of course it's that, haha.

**Comment by ZsoltMolnarrr** [comment]
Wow! Very nice find I will take a look. Thanks!
(I kinda forgot about that feature)

**Comment by ZsoltMolnarrr** [comment]
``
