### ISSUE TITLE
Automatically disable the mod on unsupported servers

### ISSUE THREAD

**Issue by cookie981** [ZsoltMolnarrr/BetterCombat#199]
In some cases, I still need to shut down, such as accessing some servers (which might misjudge cheating).

**Comment by ZsoltMolnarrr** [comment]
Please rephrase what exactly you would like. I don't understand what is the subject of the request.

**Comment by cookie981** [comment]
> 

Sorry, my English is no good.  is it possible to add an option to disable BetterCombat ?

**Comment by ZsoltMolnarrr** [comment]
This should work automatically like Combat roll
