### ISSUE TITLE
Local version of the mod

### ISSUE THREAD

**Issue by Gazdea** [ZsoltMolnarrr/BetterCombat#200]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I really like this mod, especially the first person attack view, it is very nice and I would like a similar attack animation for the client, not the client - server

**Describe the solution you'd like**
So that the attack animation works on the server, only on the client, like emotecraft

**Describe alternatives you've considered**
You can make a client mod and a plugin for the server, which will allow you to use the functions of the mod on the server, and animations for the client

**Comment by ZsoltMolnarrr** [comment]
Definitely no.
Lots of work needs to be done for this, and in the end it wouldn't work well. The animations without the upswing mechanic are totally broken.
