### ISSUE TITLE
uhh

### ISSUE THREAD

**Issue by ohwthestupid** [ZsoltMolnarrr/BetterCombat#201]
hi

this is probably a terrible issue thing, but i just wanted to say what the hell is player-animator?
where do i get it? i cant run it on fabric

if im stupid, please make fun of me
![uhohstinky](https://user-images.githubusercontent.com/112510013/217399626-2d04297f-16c1-40ac-a829-e8a091b4e19d.PNG)

**Comment by ZsoltMolnarrr** [comment]
It’s another mod, you need to install that too.

Use CurseForge launcher to install mods. https://download.curseforge.com
Just create your own profile, open it, search for mod, click install and boom! The launcher downloads the mod with all of its required dependencies.

:no_entry_sign: I cannot provide support for manually drag and dropped jar files. Million things can go wrong in the process.
