### ISSUE TITLE
[BUG] Swords from other mods that have a single word for their namespaced ID do not register as a Better Combat sword.

### ISSUE THREAD

**Issue by Clark919** [ZsoltMolnarrr/BetterCombat#202]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - 1.5.5
**I am using the latest version available** - To my knowledge.

**Describe the bug**
When using swords from other mods, they register with a better combat sword moveset, unless the sword has a single word as a namespaced ID. (e.g. I tried to use this mod with the [Witcher Origin](https://www.curseforge.com/minecraft/mc-mods/witcher-origin) mod. Every sword in the pack registers as a Better Combat sword apart from three legendary weapons, which only have a single word as their namespaced ID).

**To Reproduce**
1. Equip a sword from a mod that has a single word as it's namespaced identifier. For example: `witcheroriginaddon:aerondight`
2. Swinging the sword will make it act like a vanilla weapon, and an attack range will not be present on the tooltip if enabled in the config.
3. Compare this to another modded sword with more than one word in snake case. For example: `witcheroriginaddon:winters_blade`
4. This weapon will act as intended using the sword moveset from Better Combat.

**Expected behavior**
Both weapons should use the better combat sword moveset, but only the latter does.

**Screenshots or video recordings**
N/A. Can submit if absolutely necessary.

**Additional context**
I'm almost certain this is caused by the namespaced ID, as changing the weapons to have `_sword` as a suffix fixed the issue fine.

**Comment by ZsoltMolnarrr** [comment]
This is not a bug, but rather a lack of proper compatibility from the mod in question.

Weapons without a weapon attribute data (json) file, are picked up by fallback compatibility.

You have the following options:
- Change fallback compatibility configuration
- Disable fallback compatibility
- Ask the developer of the mod in question to add proper support files for Better Combat. The process is fully documented in the project readme.
