### ISSUE TITLE
Attacking with certain previously compatible weapons results in 1 damage punches in same session

### ISSUE THREAD

**Issue by corvusv** [ZsoltMolnarrr/BetterCombat#204]
im having some kind of issue/bug i think and im not sure why its happening specifically to me or how to fix it:
im using the epic knight mod to add some weapon variety to the game
im using an estoc (confirmed its with all weapons in epic knights mod)
it was working fine until relatively recently
the swings were coming out normally, and they still do when im not aiming at anything
but when i get in range of a mob and hit it (the reticle changes)
it just attacks with a punch instead
and does 1 damage
the only time it does work is when i deliberately miss
its accompanied by some other bug where occasionally without me clicking or doing anything else, my attack button is held down. usually happens when ive dealt the killing blow to something
ive tried restarting my client and toggling the "mine with weapon" button
neither have fixed it and i have no idea what to do next

[heres a link to a video showing what happens, I test it on a cow](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjBhOTc4ZmZkN2QxNjc2NGEzYjgyNTdiNGYwYzFmODRmYmU5ZjVkOSZjdD1n/sA8jtOK9ntKjmRKZmz/giphy.gif)

**Comment by ZsoltMolnarrr** [comment]
Using the latest version of Epic Knights and Better Combat this issue cannot be reproduced.
The problem is that you most likely have a mod installed that is interfering overriding the mechanics of Better Combat.
Only you can find what is causing this for you.
Sorry, that I cannot help more. :(
