### ISSUE TITLE
Option to Disable Better Combat in Configration Settings

### ISSUE THREAD

**Issue by Azzmikaelson** [ZsoltMolnarrr/BetterCombat#205]
Since a lot of players are used to the Vanilla Combat style and maybe for some players it'll take a long time to get used to the new combat mechanics. Adding a feature to disable the mod entirely without manually removing it in your mods folder will prove useful especially if they're playing in a modpack that includes Better Combat.

**Comment by ZsoltMolnarrr** [comment]
This feature would introduce inconsistency in difficulty and strength across players.
This will never be added.
