### ISSUE TITLE
[Suggestion] Screen trembling effect with wieldings of weapons

### ISSUE THREAD

**Issue by ChromaPIE** [ZsoltMolnarrr/BetterCombat#209]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
The animation now is mad good now, but overall it's still a little bit not it bc it doesn't pass me the feeling of strength.

**Describe the solution you'd like**
The visual field of the player, the whole screen, needs to be shoked by those whooshes and clangs. This idea was cursed to be born by Warzone, or for Minecraft, the latest Vic's Modern Warfare mod overhauls, making the screen shake per shot, or as they call it, Gunkicks. It makes you feel like ur clicking the left button like ur pulling the trigger.

I mean Steve is wielding such a gigantic claymore towards zombies and his head is steady like a PTZ. That's not great.

**Describe alternatives you've considered**
No, sadly.

**Additional context**
If it's considered unnecessary, redundant, out of route, or technically impossible, feel free to close the issue. It's nothing but a crazy and personal imagination of the mod at its best.

If there's really a chance for it to come true, I'm on 1.19.2 Fabric, just so you know. ;)

**Comment by ZsoltMolnarrr** [comment]
Sorry, your request does not fit the project goal.

**Better Combat Project goal:** 
Replicate Minecraft Dungeons combat experience.
Rework the melee combat system of Minecraft, without adding any content or content specific feature, so other content creators can build on Better Combat, without interfering content.
