### ISSUE TITLE
Feature Request: Add attack animation while walking

### ISSUE THREAD

**Issue by FirdausCraft10** [ZsoltMolnarrr/BetterCombat#210]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Please fill the issue form with details, otherwise I have to close it.
