### ISSUE TITLE
[Quilt 1.19.2] Better Combat causes the game to crash on load if other mods adding mobs are present

### ISSUE THREAD

**Issue by SimplyTadpole** [ZsoltMolnarrr/BetterCombat#214]
**Minecraft version** - 1.19.2
**Mod loader** - Quilt
**Mod version** - 1.5.5+1.19
**I am using the latest version available** - Yes

## **Describe the bug**
Not much else I can add - enabling Better Combat causes Minecraft to refuse to launch. Removing it and other mods dependent on Better Combat makes Minecraft launch successfully. The error log complains about a "critical injection failure" involving Better Combat and lists several mods that add mobs to it - such as Naturalist, Ecologics, Earth2Java and BetterNether. Removing every single mod that happens to add mobs just to get this mod to work isn't a viable solution sadly, as much as I hoped to use what seems to be the only good magic mod for Fabric/Quilt.

## **To Reproduce**
1. Install and enable BetterCombat and any mod that happens to add any mob, no matter how small/insignificant it may be.
2. Launch Minecraft.

## **Expected behavior**
Minecraft would launch without crashing.

## **Screenshots or video recordings**
Here's my log file, if it helps any: [latest.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/10832926/latest.log)

## **Additional context**
I'm mostly only using Better Combat in order to use the Wizards mod, as it requires Spell Engine which has BetterCombat as a hard dependency.

**Comment by ZsoltMolnarrr** [comment]
Do not use alpha version of PlayerAnimator.
Use release version.

**Comment by SimplyTadpole** [comment]
Welp, that did it. Seems like Prism Launcher accidentally updated to the alpha version of PlayerAnimator when I told it to update my mods... downgrading to 0.4.2 fixed it. Thanks. ^^'
