### ISSUE TITLE
Minecraft doesn't start

### ISSUE THREAD

**Issue by eiidrovo** [ZsoltMolnarrr/BetterCombat#215]
**Minecraft version** - 1.19.2
**Mod loader** - fabric
**Mod version** - 1.5.5
**I am using the latest version available** - yes

**Describe the bug**

Installed with fabulously optimized modpack, doesnt start, delete the mod, minecraft starts, the problem might be the mod

**To Reproduce**
1. Install the mod

**Comment by ZsoltMolnarrr** [comment]
This is a non actionable report.
Make sure to install required dependencies.
