### ISSUE TITLE
Process exited with code -1

### ISSUE THREAD

**Issue by eiidrovo** [ZsoltMolnarrr/BetterCombat#216]
**Minecraft version** - 1.19
**Mod loader** - fabric
**Mod version** - 1.5.5
**I am using the latest version available** - yes

**Describe the bug**
When I installed the complementary mods (cloth config, etc) its fine, but when I install better combat, it doesnt start

https://mclo.gs/O93JGYT

**Comment by ZsoltMolnarrr** [comment]
Do not use alpha version of Player Animator.
Downgrade to release version (0.4.2).
