### ISSUE TITLE
[Forge] 1.19.3, rendering error with First Person Models

### ISSUE THREAD

**Issue by Rohtea** [ZsoltMolnarrr/BetterCombat#217]
**Minecraft version** - 1.19.3
**Mod loader** - Forge 44.1.0
**Mod version** - 1.6.0
**I am using the latest version available** - Yes

**Describe the bug**
Two hands/swords rendered when used with First Person Models.

**To Reproduce**
1. Install both mods.
2. Swing any weapon.
3. See error

**Expected behavior**
Only one hand is rendered.

**Screenshots or video recordings**
![2023-02-27_06 57 55](https://user-images.githubusercontent.com/86233149/221442681-be67f511-170c-4cd2-88f1-73ee21a10c38.png)
![2023-02-27_06 57 56_2](https://user-images.githubusercontent.com/86233149/221442683-c1498f4a-fad7-4542-8a74-3c4832bae669.png)
![2023-02-27_06 57 56](https://user-images.githubusercontent.com/86233149/221442685-4e63656f-cc7a-4a9e-a906-3a1f628e185b.png)

**Additional context**
![image](https://user-images.githubusercontent.com/86233149/221442665-7850dbb1-137c-423f-b3d0-3d18876fc2d2.png)
Only these mods were installed.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thank you for the report.
Seems like the FirstPersonModel integration is broken.
This seems to be my fault, sorry for the inconvenience.

**Comment by ZsoltMolnarrr** [comment]
Fixed in 1.6.1
