### ISSUE TITLE
Twilight Forest mod - player model parts

### ISSUE THREAD

**Issue by Trozuu20** [ZsoltMolnarrr/BetterCombat#22]
When I attack my character's head blinks in front of the screen
[latest.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/9172777/latest.log)
![2022-07-23_02 33 41](https://user-images.githubusercontent.com/101068896/180583401-95e89c14-2317-4b59-9bbb-9537fca52146.png)
.

**Comment by SticksS123** [comment]
twiligth forest is the problem

**Comment by ZsoltMolnarrr** [comment]
Thanks for the information!

**Comment by ZsoltMolnarrr** [comment]
For some reason, Twilight Forest is touching player model visibility with their armor renderers.
It is also incompatible with FirstPersonModel mod.
I believe the issue has to be solved on their end, there is nothing I can do.

**Comment by ZsoltMolnarrr** [comment]
A bugfix PR was submitted to Twilight Forest team
https://github.com/TeamTwilight/twilightforest-fabric/pull/107

**Comment by ZsoltMolnarrr** [comment]
Fixed by this new release:
https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/3906655
