### ISSUE TITLE
Crashing seems inevitable...

### ISSUE THREAD

**Issue by DeathWray** [ZsoltMolnarrr/BetterCombat#220]
I can't get better combat to launch without crashing. I've tried every version of BC from 1.5.5 to 1.6.1, PA 0.4.0 to 1.0.0 and every combination of these versions for 1.18.2. They're the only mods in my mods folder, and every time I launch it crashes back to the launcher with exit code: 1 and generates no crash log. 
[latest.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/10854897/latest.log)
Found a log while writing this, but I'm not sure it'll help. 
I'm using 1.18.2-forge-40.2.1 with 8GB of allocated memory. I'm at my wits end, and have no more time to troubleshoot this morning.

**Comment by ZsoltMolnarrr** [comment]
`Mod ID: 'cloth_config', Requested by: 'bettercombat', Expected range: '[6.0.0,)', Actual version: '[MISSING]'`

The log says you need to install Cloth Config.
