### ISSUE TITLE
Player Animations

### ISSUE THREAD

**Issue by papamaionise** [ZsoltMolnarrr/BetterCombat#221]
**I read project readme, checked client side and server side configurations, and no such feature exists** -
 No
**Is your feature request related to a problem?**
This mod is a must have when making a vanilla friendly modpack but it isnt compatible with any quality player animation mod because most break  with this mod the best you can do is use fresh Animation resourcepack and thats it, Combat animations are good dont get me wrong but all others are just those decade old Animations they need to be reworked like how trainguysanimations mod achieves mc dungeons like Animation style or how fresh Animation resource pack makes mobs animations like the once in mc cinamatic trailers

**Solution**
Asking other modders for compatibily with their mods doesnt sounds really great i think just make them in this mod it would give players another reason to use this already amazing mod and no one would drop it for a player Animation mod and there are not many player animations (like compared to all mobs animations) so plz a humble request from community.

**Alternatives**
Alternatively I just use a player Animations mod like when playing third person or on servers.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Better Combat no longer has any animation related code.
The incompatibility you are referring to, exists between PlayerAnimator and your desired mods.

Usually these third party mods need to consider how PlayerAnimator works and implement their changes in a more compatible way.
