### ISSUE TITLE
FPS problem of dual-holding weapons

### ISSUE THREAD

**Issue by Dr-WeiAL** [ZsoltMolnarrr/BetterCombat#223]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.6.2
**I am using the latest version available** - Yes

**Describe the bug**
The attack speed of dual-held weapons is too fast, resulting in FPS reduction

**To Reproduce**
1. The attack speed of the test weapon is 3.36
2. Hold a weapon in both hands and attack

**Expected behavior**
One-handed attacks do not lead to a reduction in FPS, but two-handed attacks will have this problem

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/47446553/224441084-b6395c80-6b79-476c-b305-63c7a3d8ec3e.png)
![image](https://user-images.githubusercontent.com/47446553/224441157-942f56d1-b869-4d37-8fa3-dff36600e357.png)

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Forge in general performs much worse than Fabric, also since you have other mods installed it is difficult to tell what is causing the problem.
Are you using Optifine?

**Comment by Dr-WeiAL** [comment]
No, I use rubidium
About attack speed, I used the affix of Apotheosis

**Comment by ZsoltMolnarrr** [comment]
No FPS reduction can be observed when the mod is installed on its own, hence this issue is hardly actionable.

Please provide exact details with the minimum number of mods installed about how to reproduce this.

**Comment by Dr-WeiAL** [comment]
Oh well... After a few hours of testing, I found that it's not the attack speed that causes the problem, but the dual-wielded weapons with Apotheosis affixes that cause the FPS to decrease.
So this is perhaps a compatibility issue with Apotheosis?

**Comment by ZsoltMolnarrr** [comment]
As far as I know the issue has been fixes on the side of Apotheosis.
Feel free to reopen in case the issue resurfaces.
