### ISSUE TITLE
Contrasting attack speed breaks dual wielding

### ISSUE THREAD

**Issue by MrHazMat** [ZsoltMolnarrr/BetterCombat#224]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.6.2
**I am using the latest version available** - Yes

**Describe the bug**
When dual wielding weapon with large attack speed difference, if the weapon in the off hand has lower speed, it will not swing. This can be circumvented by wielding the lower speed weapon in the main hand.

**To Reproduce**
1. Wield a netherite hoe in the main hand, and a wooden hoe in the off hand.
2. Hold attack to initiate combo.
3. The main hand keeps swinging while the off hand is skipped.

**Expected behavior**
Both weapon to swing at their respective speed.

**Screenshots or video recordings**

https://user-images.githubusercontent.com/87276147/225058080-24be15bf-1452-44ba-89d9-3e5e7f7460aa.mp4

**Comment by ZsoltMolnarrr** [comment]
There is no bug in this case.
Vanilla hoes have weird attack speeds, there is nothing I can do about them. Hoes have no support by default by a reason.
Also, attack speed increase while dual wielding is configurable via server config.
