### ISSUE TITLE
[Sugestion/Compability] some cool ideas i had and that id like to see in the mod and customizable player models animation editing

### ISSUE THREAD

**Issue by bruhicantlogin** [ZsoltMolnarrr/BetterCombat#225]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO
Yes

**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Not a solution as its not related to a problem, but id like to see the combat get a little bit more enhanced, like, swords being able to clash when both players hit at the same time making both stunned, depending on who attacked first, the one that attacked later would get a bigger stun, which would not allow them to attack and would make them move very slow, Fist combat id also like to see because... fist combat is always cool even though it would obviously deal way less damage, it would be quicker and cool. and for the compability thingy i put in the title, id just like so that you could edit each attack animation with Customizable player models, it just sounds cool

**Describe alternatives you've considered**
I have none

**Additional context**
i also have none lmao, but id if i knew how to make a screenshot of it

**Comment by ZsoltMolnarrr** [comment]
I am sorry none of this will be implemented.
Reworking the animation system is not possible within a reasonable amount of time, it would be equivalent to creating a new project.
Compatibility with customizable player models has nothing to do with Better Combat. Better Combat is using an animation library called PlayerAnimator. I recommend contacting the author of Customizable player modelsin order to establish proper integration with PlayerAnimator.

**Comment by bruhicantlogin** [comment]
okay, thank you for reading my thread or whatever you call those on github, i don't use this website often, anyways, thank you :)
