### ISSUE TITLE
Crosshair inconsistant

### ISSUE THREAD

**Issue by Aceplante** [ZsoltMolnarrr/BetterCombat#226]
**Minecraft version** - 1.18.2
**Mod version** - 1.6.2
**I am using the latest version available** - Yes

**Describe the bug**
The crosshair is sometimes red and sometimes light blue? And sometimes both at just the right angle?? See attached screenshot

![2023-03-16_19 49 54](https://user-images.githubusercontent.com/101857505/225777299-b2a818c2-c913-4996-b891-cd99bbdaca15.png)

**Comment by ZsoltMolnarrr** [comment]
It gets tinted red while there is a target in striking range.
The cross colors get inverted depending on background color. This is vanilla behaviour.
