### ISSUE TITLE
adding "no jumping while attacking" option

### ISSUE THREAD

**Issue by ZEENCL** [ZsoltMolnarrr/BetterCombat#228]
I suggest adding an option to the server-side config to enable or disable jumping while attacking. I've set the "movement_speed_while_attacking" to "0.0", it does its job, but I can still move around pretty quickly while attacking by spam jumping (holding spacebar). I truly think this feature should be heavily considered since I've found "Combat Roll" to be redundant if combined with "Better Combat". You can still easily and quickly dodge enemy assaults without compromising your fully committed attacks just with "Better Combat" alone simply by jump spamming.

Overall, I think it's a little imbalanced and there should be an option to disable jumping while attacking. Other than that, this is a fantastic mod, and keep up the amazing work! I hope this suggestion will help with the further development of this mod.

**Comment by ZsoltMolnarrr** [comment]
Interesting idea!
Added to the backlog.

**Comment by ZsoltMolnarrr** [comment]
Upon further investigation I concluded that this idea would conflict with Vanilla critical strike mechanic.
Hence it cannot be implemented in this form.
