### ISSUE TITLE
Incompatibility with Forbidden and arcanus.

### ISSUE THREAD

**Issue by drakosoldier298** [ZsoltMolnarrr/BetterCombat#229]
**Minecraft version** - 1.19.2
**Mod loader** - Forge 43.2.6
**Mod version** - 1.6.2
**I am using the latest version available** - Latest available for 1.19.2

**Describe the bug**
the bug is inconsistent but has been reproducable for a few weeks.
6/10 times when loading the game with forbidden and arcanus and better combat it will stop loading and just freeze.
**To Reproduce**
1. add Better combat and forbidden and arcanus
2. try to load
3. Either freeze, or on some occasion load as normal.

**Additional context**
This issue has been brought up with forbidden and arcanus.
https://github.com/stal111/Forbidden-Arcanus/issues/332

**Comment by ZsoltMolnarrr** [comment]
None of the related crashlogs show specific issues regarding Better Combat.
Please provide some actionable data on the matter.
