### ISSUE TITLE
Crash when staring at skeleton horse/entity with broken ownership

### ISSUE THREAD

**Issue by AnOpenSauceDev** [ZsoltMolnarrr/BetterCombat#231]
**Minecraft version** - 1.19.4
**Mod loader** - Fabric
**Mod version** - 1.6.2+1.19.3
**I am using the latest version available** - Yes

**Describe the bug**
Whenever I stare at a skeleton horse that spawned from a trap, the game crashes.
having your crosshair in the horse's hitbox will instantly crash the game

**To Reproduce**
Find a skeleton horse trap, of which the rider has probably been killed
stare _directly_ at said horse
watch the game crash

**Expected behavior**
I expected to be able to stare at the horse consequence-free

**Screenshots or video recordings**
the game crashes, so i really capture anything here

**Additional context**
this seems to have something to do with the skeleton horse's owner no longer existing, based off the class this crashes at

--- Crash Log ---
[crash-2023-03-31_18.57.12-client.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/11120112/crash-2023-03-31_18.57.12-client.txt)

**Comment by AnOpenSauceDev** [comment]
Just a small update - i have been able to replicate this on another machine.

**Comment by ZsoltMolnarrr** [comment]
The mod was forced to run on an unsupported Minecraft version.
Of course there will be crashes. :)
