### ISSUE TITLE
broken weapons when i use better combat in multiplayer

### ISSUE THREAD

**Issue by anreww2910** [ZsoltMolnarrr/BetterCombat#232]
**Minecraft version** - 1.19.3
**Mod loader** - forge
**Mod version** - latest
**I am using the latest version available** - yes

**Describe the bug**
So, all of my weapons are bugged except a iron claymore (from simplyswords mod) im using, they dont do the animation that pulls them out and charges their critical bar thingy, this is only bugged in multiplayer and not on singleplayer for some reason and its very annoying, even vanilla minecraft weapons such as axes are bugged and just dont work

**To Reproduce**
this only seems to happen to me, i just join my friends server and the weapons are bugged my other friends dont have this issue

**Expected behavior**
expected for everything to work fine
**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Non actionable issue, with no version info, logs or media attachments.
