### ISSUE TITLE
should make axes ACTUALLY work and not just act like a weapon

### ISSUE THREAD

**Issue by sijalids** [ZsoltMolnarrr/BetterCombat#233]
pls, I love this mod, but I hate to have axes not work like axes when chopping wood.

**Comment by ZsoltMolnarrr** [comment]
Better Combat Discord FAQ:

**How can I exclude axes from this mod?**
Use the fallback compatibility configuration to put them on blacklist.
`/config/bettercombat/fallback_compatibility.json`
`"blacklist_item_id_regex": "pickaxe"` :arrow_right: `"blacklist_item_id_regex": "pickaxe|axe"`
This works for any partial item id, not just axes.
