### ISSUE TITLE
Add vanilla tools

### ISSUE THREAD

**Issue by Aceplante** [ZsoltMolnarrr/BetterCombat#235]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES?

**Is your feature request related to a problem? Please describe.**
I would like to make the vanilla tools (as in shovel/pick/hoe) have an animation too but I cannot figure out how to do so with the config file. I would also like to make the hands have a punching animation (but mostly for the not instant attack speed). I assume for this I can use "claw" but how do I add fists to the config file?

**Describe the solution you'd like**
If this is currently not possible, I hope it would be an easy addition.

**Additional context**
Im using a mod called "actions of stamina", and with no cooldown on those three tools I mentioned, you can rapidly click to drain all of your stamina almost instantly. But that does not seem to happen with the slow swing animations of the sword and axe, so I would like to add those to these other tools and fists.

**Comment by ZsoltMolnarrr** [comment]
This can be done via fallback compat, or datapacks.

Better Combat Discord FAQ:

**How do I add compatibility for mod weapons?**
- As a player - The compatibility of weapons is not designed to be changed by end users. If you are really determined, you can check the content of `config/bettercombat/fallback_compatibility.json` file to change what attributes are assigned by default, to weapons without dedicated compatibility
- As a mod developer - You can add dedicated compatibility for your weapons, following this guide:
https://github.com/ZsoltMolnarrr/BetterCombat#-integrate-your-mod (This is the most preferred way!)
- As a modpack developer - You can add dedicated compatibility to weapons via datapacks, following this guide:
https://github.com/ZsoltMolnarrr/BetterCombat#-using-datapacks

**How can I exclude axes from this mod?**
Use the fallback compatibility configuration to put them on blacklist.
`/config/bettercombat/fallback_compatibility.json`
`"blacklist_item_id_regex": "pickaxe"` :arrow_right: `"blacklist_item_id_regex": "pickaxe|axe"`
This works for any partial item id, not just axes.

**Comment by Aceplante** [comment]
Edit: that did work nvm but also:

how would I add the "claw" animation to basic fists (not holding anything/everything else?)

**Comment by ZsoltMolnarrr** [comment]
Currently, there is no way to modify how unarmed combat works.
It is very problematic to implement.
