### ISSUE TITLE
There is an issue with the position of the hand when holding a long handled weapon.

### ISSUE THREAD

**Issue by 48004800** [ZsoltMolnarrr/BetterCombat#236]
**Minecraft version** - 1.19.4
**Mod loader** - forge
**Mod version** - 1.6.2
**I am using the latest version available** - yes
![2023-04-11_17 46 01](https://user-images.githubusercontent.com/78255094/231123830-d808cd17-db73-4cdc-9d6c-c95360c568ad.png)

**Comment by 48004800** [comment]
When using some weapons for stab attacks, the problem shown in the above picture may occur

**Comment by ZsoltMolnarrr** [comment]
It is what is.
All animation resources are open source. Feel free to improve them if you want.

**Comment by 48004800** [comment]
> It is what is. All animation resources are open source. Feel free to improve them if you want.

It seems that my previous conclusion was wrong, it is possible that the animation is not a problem. The problem can be solved by changing the position where Steve holds the weapon.

If Steve's hand were closer to the end of the spear while holding it, this issue may not occur.

**Comment by 48004800** [comment]
This raises another issue, where the attack distance of a spear should usually be farther than that of a sword. However, due to the incorrect position of the hand, the attack distance of the spear is almost the same as that of the sword (visually).

![2023-04-14_15 14 12](https://user-images.githubusercontent.com/78255094/231970999-9f8d701b-5bb0-46fb-831a-38ea3f50ec43.png)
![2023-04-14_15 14 01](https://user-images.githubusercontent.com/78255094/231971002-670ea2cd-1712-4e09-af89-1c310570344d.png)
The player has no problem holding the sword, but there is a problem of the hand being too close to the front when holding the spear.

Players also have this problem when holding a trident with one hand, as this holding method wastes the length of the weapon, and from a visual perspective, the attack distance is almost the same as the sword.
![2023-04-14_15 15 46](https://user-images.githubusercontent.com/78255094/231972046-c213934c-f36d-46f3-9a1d-8dc499838269.png)

**Comment by 48004800** [comment]
![2023-04-14_15 24 58](https://user-images.githubusercontent.com/78255094/231973327-523386bd-afdc-4644-bee8-d914f0a3e981.png)
The way a golem holds a spear is different from the way a player holds a spear.
I mainly refer to the position of their hands
