### ISSUE TITLE
Weapon Specific Movement Speed while Attacking options

### ISSUE THREAD

**Issue by Squidman13** [ZsoltMolnarrr/BetterCombat#237]
Would it be possible to make only certain weapons enforce the movement_speed_while_attacking config option, or have each specific weapon type have its own movement speed value option?

**Comment by ZsoltMolnarrr** [comment]
Hello!
This issue tracker is mostly for bugs.
The opinion and ideas of the community matter, please reach out on our Discord server, and explain how and why this would be important for you. :)
