### ISSUE TITLE
Offhand glitch with two-handed weapons

### ISSUE THREAD

**Issue by SanicFan19** [ZsoltMolnarrr/BetterCombat#238]
**Minecraft version** - 1.19.2
**Mod loader** - fabric 0.14.19
**Mod version** - 1.6.2
**I am using the latest version available** - yes

**Describe the bug**
Whenever I swap a two-handed weapon into my offhand it disappears

**To Reproduce**
1.run fabric with better combat and simply swords mods
2.take a two handed weapon from the creative menu and put it in your main hand
3.press the key that is bound to "swap with offhand" default is the "f" key

**Expected behavior**
the weapon should either refuse to swap with your offhand or go into your offhand but not do anything until it's back in your main hand (Idk what should do but I'm guessing its one of the things above)

**Additional context**
Me and my friends found this weird glitch while playing on a server with my own modpack

**Comment by ZsoltMolnarrr** [comment]
Two handed weapons can only be used in the main hand.
This feature is working as expected, there is no technically feasible way to implement otherwise.

**Comment by SanicFan19** [comment]
Is there any way to reverse the offhand swap or prevent it from happening? I don't think weapons should just vanish entirely with no way to get them back.

**Comment by Rimplestilt** [comment]
pathetic closing this issue

**Comment by dylanxyz** [comment]
I guess this problem is not gonna be fixed?

To be clear, the problem i'm referring to is the weapons disappearing after switching it from the offhand slot. I don't think that should happen.
