### ISSUE TITLE
[Incompability] Losing dyed color when swinging (Fancydyes)

### ISSUE THREAD

**Issue by Rad586** [ZsoltMolnarrr/BetterCombat#240]
**Minecraft version**
1.18.2 fabric 0.14.19
**Mod version**
1.6.2 ( latest)

**Describe the bug**
Losing dyed color(added by fancy dyes mod) on weapon when swinging. 

**To Reproduce**
1. Dye a weapon using solid(edit: sometimes shimmer) dyes. 
2. Swing it.

**Comment by ZsoltMolnarrr** [comment]
Can you please specify how exactly is this related to Better Combat?

**Comment by Rad586** [comment]
> Can you please specify how exactly is this related to Better Combat?

Better combat added the swinging animation, and that issue happens during the animation. 
This pic may explain: https://i.postimg.cc/KzkLZ4wQ/1.png

**Comment by Rad586** [comment]
It's an Iris issue, sorry for the inconvenience!
