### ISSUE TITLE
Problem using with Shield Expansion

### ISSUE THREAD

**Issue by Dr-WeiAL** [ZsoltMolnarrr/BetterCombat#241]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.6.2
**I am using the latest version available** - yes

**Describe the bug**
When used with [Shield Expansion](https://www.curseforge.com/minecraft/mc-mods/shield-expansion), raising the shield and using weapon attacks will keep the shield on cooldown unless you press and hold the right button until the shield is cooled down
https://github.com/infernalstudios/Shield-Expansion/issues/23

**To Reproduce**
1.Shield in the left hand, sword in the right
2.Press and hold the right button to use the shield
3.Left click while using shield to use weapon to attack
4.Do not perform any operations
5.The shield will always be on cooldown

**Expected behavior**
Shields should not be on cooldown all the time

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/47446553/233270667-5b2f68e1-48d9-4cb7-aa7f-99c5b35a9115.png)

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Hello!
It would be nice to get some feedback on this from [tinytransfem](https://github.com/tinytransfem)!
Maybe this is due to some state handling in Shield Expansion.

**Comment by Dr-WeiAL** [comment]
https://github.com/infernalstudios/Shield-Expansion/issues/23#issuecomment-1516097027
Well... that's what tinytransfem says

**Comment by ZsoltMolnarrr** [comment]
Does this issue still require action from my side?

**Comment by Dr-WeiAL** [comment]
Uh... the other side said it would be fixed in the next update, but it hasn't been updated until now, so it's better to fix it from this side?

**Comment by ZsoltMolnarrr** [comment]
It looks like the issue is in the internal state of Shield Expansion logic. (I might be wrong)
I don't see any possible ways to fix this from my end.

**Comment by ZsoltMolnarrr** [comment]
As far as I see, they could fix it by using Better Combat API.
Specifically `BetterCombatClientEvents.ATTACK_START` event. Hooking to this event would allow them to cancel shield blocking, or perform whatever is correct.

**Comment by ZsoltMolnarrr** [comment]
Feel free to reopen in case it turns out that action is required from me.

**Comment by CinnYaBoi** [comment]
Bug is still present, Tinytransfem says: https://github.com/infernalstudios/Shield-Expansion/issues/23#issuecomment-1516097027. Could this be implemented?
