### ISSUE TITLE
Problem with Alex's Mobs

### ISSUE THREAD

**Issue by Explode007** [ZsoltMolnarrr/BetterCombat#243]
**Minecraft version** - 1.19.2
**Mod loader** - Forge 43.2.8
Latest mod version

**Describe the bug**
(https://github.com/AlexModGuy/AlexsMobs/issues/1593#issue-1680271860)
I haven't tried with other mobs, but hitting a giant squid with a sword from better combat completely freezes the game in a state of infinite lag.

**To Reproduce**
1. Hit giant squid from alex's mobs with a weapon that uses better combats system
2. Game is now in a state of infinite lag

**Expected behavior**
The game to not freeze

**Screenshots or video recordings**

**Comment by ZsoltMolnarrr** [comment]
Please specify exactly what is version of Better Combat you are using.
Please try reproducing the issue on the recommended version of Forge.
<img width="373" alt="Screenshot 2023-04-26 at 9 05 49" src="https://user-images.githubusercontent.com/4989469/234496397-dd547e56-f700-4579-8267-1daf9b3f7531.png">

Note: Never use the latest version of Forge, always what is officially recommended by them.

**Comment by Explode007** [comment]
Regardless, I rolled back version of forge to recommended. Problem still exists
Better combat version: 1.6.2
AlexMobs Version: 1.12.1

**Comment by ZsoltMolnarrr** [comment]
Yesterday I tested this very specific scenario.
No issue occurred.
Please provide minimal setup that can reproduce the error.

**Comment by Explode007** [comment]
I don't know if it's with the other mods I have but since the immediate problem seemed to be better combat + alexsmobs that's what I assumed. But it seems to be related to entities with collision, Because I can kill other mobs from alexs just fine but the cachalot whale, giant squid which both you cannot pass through it freezes the game. I also took noticec because I launched game with minecraft game output log and got this set of outputs when hitting the entity.
![image](https://user-images.githubusercontent.com/12020284/235655909-51b59b6a-1c99-4709-92ad-994b071837d6.png)

Is there anyway for me to check further in detail when something like this happens?

**Comment by ZsoltMolnarrr** [comment]
Nothing in the provided information indicates any error of Better Combat.
I am unable to solve this for you.
Since the problem doesn't occur while only Better Combat and Alex mobs are installed, it likely that another mod is causing this problem.
I recommend disabling other mods to see what causes the problem. (Binary search method)

**Comment by Explode007** [comment]
Alright, guess I'll do it the old fashioned way (binary search)

**Comment by Explode007** [comment]
It appears to be Majrusz's progressive difficulty, thats the one mod that is causing the bug.
