### ISSUE TITLE
Attack speed minimum?

### ISSUE THREAD

**Issue by Aceplante** [ZsoltMolnarrr/BetterCombat#246]
I dont know what mod it is, but one of them is making the attack speed of my tools negative which makes me unable to attack with them. Perhaps there should be a check to make sure the attack speed never drops to or below 0 so you can still attack with them?

But then again, maybe some would want this as a feature to disable a certain item, so perhaps it could be configurable?

**Comment by ZsoltMolnarrr** [comment]
Better Combat does not modify attack speed attribute of any weapon, nor is it planned to do so.
Fixing bugs created by other mods is not the scope of this project.
