### ISSUE TITLE
Invisible weapon swings in 1st person using Canvas Renderer (1.19.2)

### ISSUE THREAD

**Issue by gamerpotion** [ZsoltMolnarrr/BetterCombat#247]
Hey,  have started using Canvas in DarkRPG and noticed this recently

You can replicate this issue by installing Better Combat and Canvas - https://www.curseforge.com/minecraft/mc-mods/canvas-renderer
in 1.19.2

For some reason its not showing the wapons in 1st person

Normal:-
![](https://cdn.discordapp.com/attachments/614625541114298397/1104090842819461150/javaw_EkxX3FvYK6.gif)

With Canvas installed:-
![](https://cdn.discordapp.com/attachments/614625541114298397/1104090791548297266/javaw_RuiQrqjXPI.gif)

@spiralhalo FYI

**Comment by ZsoltMolnarrr** [comment]
This issue is not actionable from my side.
Needs to be fixed in codebase of Canvas. Canvas needs to implement their changes in a more compatible manner, to avoid braking PlayerAnimator library.
