### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by MagmaSlime123** [ZsoltMolnarrr/BetterCombat#248]
**Minecraft version** - 1.18.2.
**Mod loader** - Forge.
**Mod version** - See modlist screenshot below.
**I am using the latest version available** - No. If 1.18.2 isn't supported, please archive/remove it.

**Describe the bug**
Mod crashes on its own.

**To Reproduce**
Install the mod.

**Expected behavior**
Game to load.

**Screenshots or video recordings**
![image](https://user-images.githubusercontent.com/51277766/236740870-88de9ed8-776b-4a16-9011-6d15c1884ebd.png)

**Additional context**
Combat Roll also seems to have this same issue.

**Comment by ZsoltMolnarrr** [comment]
Non actionable issue.
Missing dependency: Cloth Config.
Either read downloadable file page about dependencies. Or use CurseForge launcher that automatically resolves all of them for you.
