### ISSUE TITLE
mismatch

### ISSUE THREAD

**Issue by Rogenar** [ZsoltMolnarrr/BetterCombat#250]
![ss2](https://github.com/ZsoltMolnarrr/BetterCombat/assets/122460325/4b1bd9a2-556d-4f84-a1f5-56a86eea07ca)

**Comment by ZsoltMolnarrr** [comment]
Duplicate of #42

**Comment by Rogenar** [comment]
Will there be a version to fix this?

**Comment by ZsoltMolnarrr** [comment]
Yes breaks flag will be lifted if new version of Inventorio is verified to have no issues.
