### ISSUE TITLE
Better Combat Working With Mobs?

### ISSUE THREAD

**Issue by ZEENCL** [ZsoltMolnarrr/BetterCombat#251]
**I read project readme, checked client side and server side configurations, and no such feature exists** 
YES

**Is your feature request related to a problem? Please describe.**
I love this mod! I love the new mechanics and animations it adds to the game. It created depth and complexity in Minecraft's combat, which is very much needed in my opinion. With that being said, I think it would be amazing if this mod also applies to other entities and mobs, not just players. It would add this whole new feel into Minecraft's combat system. It's always so funny to see other mobs using weapons so blandly. They just mindlessly charge at you with no animation and timing. I'd imagine Better Combat Roll working extremely well with this new mechanic as you can time your dodges properly now with this feature.

**Describe the solution you'd like**
Since this is a MASSIVE feature and change, I think it would be best if this feature would be toggleable via the server-side config.

**Describe alternatives you've considered**
Another thing to consider is making a separate add-on mod for Better Combat that does exactly this instead.

**Additional context**
But other than that, I think this mod is awesome. I just wish the mobs have a bit more life when they're in combat. It would also make the combat more consistent. Anyway, I hope you consider this feature! I understand if this is too much to ask. It would be a massive addition.

**Comment by ZsoltMolnarrr** [comment]
Hello!
This is not possible with the current tech stack. The library used for playing animations (PlayerAnimator), is only capable on animating players.
The current best practice is to create proper animations for mobs using GeckoLib.
For vanilla mobs there is Entity Model Features, to play more sophisticated animations.
