### ISSUE TITLE
Adding sprint, crouch and jump specific atacks animations

### ISSUE THREAD

**Issue by MrDraxs** [ZsoltMolnarrr/BetterCombat#252]
kinda like Elden ring.
i recommend that the sprinting attack to the spear be like zelda botw.
heavy attacks in the future would be nice too.

if you don't like or approve of this idea or post or if the feature already exists just delete this post.

**Comment by ZsoltMolnarrr** [comment]
Hello!
Project goal is to replicate Minecraft Dungeons combat system, not Elden Ring, Dark Souls or whatever else.
Technical limitations also make this difficult to implement.
I will keep this suggestion in mind to see if this would have a place in the mod, in the future.
