### ISSUE TITLE
Have mobs inherit the combat system

### ISSUE THREAD

**Issue by DaanSchar** [ZsoltMolnarrr/BetterCombat#254]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Describe the solution you'd like**
Mobs currently use the vanilla-style combat system.
I think it would make combat a lot more interesting if mobs also used the same system as the player does when holding weapons.

**Additional context**
A great example as you might know, as it rivals your mod on forge, is the [Epic fight mod](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod). Mobs use the same combat system as players, which makes PvE a whole lot more fun!

**Comment by ZsoltMolnarrr** [comment]
Hello!
This is not possible with the current tech stack. The library used for playing animations (PlayerAnimator), is only capable on animating players.
The current best practice is to create proper animations for mobs using GeckoLib.
For vanilla mobs there is Entity Model Features, to play more sophisticated animations.
