### ISSUE TITLE
Mod conflict with Sully's Mod

### ISSUE THREAD

**Issue by Uraneptus** [ZsoltMolnarrr/BetterCombat#255]
Mc 1.19.2 Forge only!

Hey I've got this bug report on a mod I'm working on: [Link](https://github.com/Uraneptus/Sullys-Mod/issues/54)
For context the Jade Shield the user is referring to is a custom shield I have in that mod, which uses an attribute modifier to have a faster use speed. 
I'm not yet sure how to handle this issue and I wanted to know if there is anything you could do on your end to fix this or if you'd have an idea what I could try?

**Comment by ZsoltMolnarrr** [comment]
Hello!

There are too many factors at play here.
I was unable to reproduce such error, and currently I have no capacity to dig deep.

An issue needs specific details and minimal reproduction setup to be actionable.

**Comment by Uraneptus** [comment]
I could reproduce it quite easily. I installed Sully's Mod, Better Combat and any mod that adds Twohanded weapons.
Put the Jade Shield in the off-hand by pressing 'F' and then use the Two-handed weapon.
I just need to know if there is anything in your mod that could cause attributes from an item in the off-hand slot to be applied to the item in the main hand if the main hand weapon has to be two-handed?

**Comment by ZsoltMolnarrr** [comment]
Equiping Epic Knights Zweihander and Jade shield in the offhand slot does not reproduce the issue for me.
Attack speed is unaffected by Better Combat, unless dual wielding.
