### ISSUE TITLE
[Feature request] More accurate first person attack animations.

### ISSUE THREAD

**Issue by Warhand** [ZsoltMolnarrr/BetterCombat#259]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
First person weapon attack animations do not always line up with where the weapon will hit, this is especially pronounced when the player is swimming or using a spear. (This can easily be observed by attacking with a spear while strafing to either side, as the spear will target the side of the screen towards where the player is moving, while the actual attack range of the spear will be in the center of the screen, just like all weapons.

**Describe the solution you'd like**
I would like it if either by default or through a config option, the first person attack animations were made a bit more rigid, and more constrained to where the weapon will actually hit.

**Describe alternatives you've considered**
It could probably also help if you give people a config option to determine how heavily they want movement to factor into their first person combat animations, like an intensity slider from 0.0 (The animation will play with 0 variation, regardless of player movement) to 1.0 (The animation will deviate wildly at the slightest movement on the players part.)

**Additional context**
Screenshot demonstrating how far off center the spear animation can get when the player is strafing in any direction while attacking.
![2023-06-06_01 23 07](https://github.com/ZsoltMolnarrr/BetterCombat/assets/29134223/e64e615a-4395-4c38-b5af-277728ff3bb9)

**Comment by ZsoltMolnarrr** [comment]
Hello!
I experimented a lot with this feature. Unfortunately I am unable to further improve the behaviour of this. Hence this issue is non-actionable and is going to be closed.
If anyone wants to see this improved, that person needs to make the actual changes and send the result as a PR.
Contributions are more than welcome!

**Comment by Warhand** [comment]
I see... is it not possible to just replicate the behavior of the first person attack animations when the player is mounted? Those seem to be unaffected by player movement, and always direct towards the center of the screen.

**Comment by ZsoltMolnarrr** [comment]
I don't know if mounting improves this. I will check it out.

**Comment by ZsoltMolnarrr** [comment]
Hello @Warhand !
First person animations while mounted play the same for me.
Can you say a specific example of what do you mean?
