### ISSUE TITLE
[Question] What happens with the Sweeping Edge enchantment

### ISSUE THREAD

**Issue by Catomax262** [ZsoltMolnarrr/BetterCombat#260]
I have realized that it does nothing now that dynamic damage is added.

**Comment by ZsoltMolnarrr** [comment]
Hello!
- Weapon swings hitting multiple targets now deal reduced damage (the maximum damage penalty is 50%)
- The more enemies you hit the less damage your weapon swing deals
- To unleash the full potential of your weapon swings, and always hit full weapon damage against all targets, you now need to have Sweeping Edge enchantment
(All related values are configurable in `config/bettercombat/server.json5`)

I recommend Discord for QnA.
