### ISSUE TITLE
Add compatiblity with domestic innovation mod

### ISSUE THREAD

**Issue by GauntAndreX8** [ZsoltMolnarrr/BetterCombat#261]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO
Yes
**Is your feature request related to a problem? Please describe.**
The domestic innovation mod is suppose to help prevent the owner to attack the pet but the better combat mod installed completely ignores that and can help fix the issue 
**Describe the solution you'd like**
This mod doesn't ignore the protection of players attacking their pets
**Describe alternatives you've considered**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
An API could be added to what add additional logic about what to consider as a friendly target.
Directly targeted compatibility for this mod will not be added tho.

**Comment by GauntAndreX8** [comment]
nvm just download a mod i found fix the problem
