### ISSUE TITLE
Incompatibility with tinker construct weapons durability.

### ISSUE THREAD

**Issue by TimDub** [ZsoltMolnarrr/BetterCombat#262]
**Minecraft version** - 1.18.2
**Mod loader** - forge 40,2,9
**Mod version** - 1.6.2+

**Describe the bug**
When using the weapon in dual wielding mode from tinker construct (ver. 3.6.4.113) with custom datapack, its durability does not decrease in offhand. 

**To Reproduce**
Just make any type of weapon one handed via datapack with sword, dagger, etc animations and try to break offhand weapon. Its unbreakable.
Datapack i am using:
[constructcombat.zip](https://github.com/ZsoltMolnarrr/BetterCombat/files/11773312/constructcombat.zip)

**Comment by ZsoltMolnarrr** [comment]
1.18.2 versions are no longer provided support for. Sorry sir.
You can use it as is, or update to a newer game version.
