### ISSUE TITLE
Modular Reach indicator

### ISSUE THREAD

**Issue by ffuentesm** [ZsoltMolnarrr/BetterCombat#263]
I am mostly confused. 
As I am using Silent gears, I am not sure which mod's reach the weapons are using. 
As Batter combat shows the reach is 2.75 while Silent Gear shows it to be 3
![image](https://github.com/ZsoltMolnarrr/BetterCombat/assets/44974827/9e41750c-3716-4bdb-804d-eb98a95f5daf)

**Comment by ZsoltMolnarrr** [comment]
Hello!
Sorry sir, the other mod you mention is currently considered a semantical incompatibility.
https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility

**Comment by ffuentesm** [comment]
Which one would take priority, this or Silent's gear?
