### ISSUE TITLE
How to get animations on weapons with underscores

### ISSUE THREAD

**Issue by tvgblade** [ZsoltMolnarrr/BetterCombat#264]
Im making datapacks for weapons using the presets and it has worked for every weapon I have done it for except for the ones that have an underscore in their item id, I was wondering how to get around this or if there is a way to make it work

**Comment by ZsoltMolnarrr** [comment]
All information is available in the GitHub readme. For additional information on animations, you can also check out `animdations/README.md`.
You can also join our Discord to get live help with your project.
