### ISSUE TITLE
Kingdom Keys weapons keep being to fast (other weapons too but KK is the main issue)

### ISSUE THREAD

**Issue by DerShendi** [ZsoltMolnarrr/BetterCombat#265]
**Minecraft version** 1.18.2 
**Mod loader** Forge 
**Mod version** 1.6.2 
**I am using the latest version available** yes 

**Describe the bug**

Ive added the Kingdom key's mod and created the compatability Datapack for the mod but the weapons seem to attack too fast. (same seems to be the issue for other weapons like the Alph Blade from Mythic botany even though its using the automatic default compatability thingy)

**To Reproduce**
1. Go to 'Just download these 2 mods and create the compatability pack'
2. Click on 'anything'
3. See error

**Expected behavior**
For the weapons to attack in normal speed

**Screenshots or video recordings**
Vid keeps getting longer than 10 mb

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
1.18.2 versions are discontinued.
You can use it as is, or upgrade to a newer Minecraft version.

**Comment by DerShendi** [comment]
> 1.18.2 versions are discontinued. You can use it as is, or upgrade to a newer Minecraft version.

OK its cool that its discontinued but can i ask for a way i can edit the speed of the weapons ??
