### ISSUE TITLE
Pose/Idle animation still activates when the player starts using the item

### ISSUE THREAD

**Issue by RedPxnda** [ZsoltMolnarrr/BetterCombat#267]
**Minecraft version** 1.20.1 (should also occur on all) ?
**Mod loader** Fabric (should also occur on forge)
**Mod version** 1.7.2 ?
**I am using the latest version available** Yes

**Describe the bug**
When using an item, (eg. holding down right click to eat food or throwing a trident) the animation(or at least the transformations applied to the item during the animation) for the combo's pose/idle is still applied.

**To Reproduce**
1. Add an idle animation or pose to some item that also has a right click ability. (Trident, namely) Specifically, an animation that applies transformations to the item.
2. Start holding down right click. You'll notice these transformations are still applied.

**Screenshots or video recordings**
(item should not be rotated) [imgur gif of this](https://i.imgur.com/yMonsUD.gif)

**Other notes**
This should be a really easy fix: add a check for if the player is using an item. (`Player#isUsingItem` on yarn)
If you could tell me where your idle animation code is, I could probably make a quick pr to fix this.

**Comment by ZsoltMolnarrr** [comment]
Ohh, interesting stuff.
Never thought about such conflict before. Thank you for mentioning.
