### ISSUE TITLE
dual_handed_slash_cross cause crash

### ISSUE THREAD

**Issue by steve12621** [ZsoltMolnarrr/BetterCombat#269]
**Minecraft version** - 1.18.2
**Mod loader** - forge 40.2.9
**Mod version** - bettercombat-forge-1.6.2
**I am using the latest version available** - yes

**Describe the bug**
when applying "animation": "bettercombat:dual_handed_slash_cross" to a weapon and attack with dual weapon, the game crash

**To Reproduce**
1. create a datapack containing "animation": "bettercombat:dual_handed_slash_cross". Here's the specific sword.json I used, and it locates at datapacksname\data\bettercombat\weapon_attributes

 {
  "attributes": {
    "attack_range": 2.5,
    "two_handed": false,
	"pose": "bettercombat:pose_one_handed_backwards",
    "category": "dagger",
    "attacks": [
      {
		  "conditions": ["NOT_DUAL_WIELDING", "MAIN_HAND_ONLY"],
        "hitbox": "HORIZONTAL_PLANE",
        "damage_multiplier": 1,
        "angle": 120,
        "upswing": 0.5,
        "animation": "bettercombat:one_handed_slash_horizontal_right",
        "swing_sound": {
          "id": "bettercombat:dagger_slash"
        }
      },
      {
		  "conditions": ["NOT_DUAL_WIELDING", "MAIN_HAND_ONLY"],
        "hitbox": "HORIZONTAL_PLANE",
        "damage_multiplier": 1,
        "angle": 120,
        "upswing": 0.5,
        "animation": "bettercombat:one_handed_slash_horizontal_left",
        "swing_sound": {
          "id": "bettercombat:dagger_slash"
        }
      },
	  {
		  "conditions": ["NOT_DUAL_WIELDING", "MAIN_HAND_ONLY"],
        "hitbox": "VERTICAL_PLANE",
        "damage_multiplier": 1.2,
        "angle": 120,
        "upswing": 0.5,
        "animation": "bettercombat:one_handed_uppercut_right",
        "swing_sound": {
          "id": "bettercombat:claymore_swing"
        }
      },
      {
        "conditions": ["DUAL_WIELDING_SAME_CATEGORY", "MAIN_HAND_ONLY"],
        "hitbox": "VERTICAL_PLANE",
        "damage_multiplier": 1,
        "angle": 120,
        "upswing": 0.5,
        "animation": "bettercombat:dual_handed_slash_cross",
        "swing_sound": {
          "id": "bettercombat:dagger_slash"
		  }
        },
		{
        "conditions": ["DUAL_WIELDING_SAME_CATEGORY", "MAIN_HAND_ONLY"],
        "hitbox": "VERTICAL_PLANE",
        "damage_multiplier": 1,
        "angle": 120,
        "upswing": 0.5,
        "animation": "bettercombat:dual_handed_slash_uncross",
        "swing_sound": {
          "id": "bettercombat:dagger_slash"
        }
      },
	  {
        "conditions": ["DUAL_WIELDING_SAME_CATEGORY", "MAIN_HAND_ONLY"],
        "hitbox": "FORWARD_BOX",
        "damage_multiplier": 1.2,
        "angle": 0,
        "upswing": 0.5,
        "animation": "bettercombat:dual_handed_stab",
        "swing_sound": {
          "id": "bettercombat:claymore_stab"
        }
      }
    ]
  }
}

2. apply the datapack to a world
4. get into the world and grab 1 sword in main hand and another in off hand, then attack
5. Crash

**Expected behavior**
Crash

**Screenshots or video recordings**
na

**Additional context**
modlist:
GameMenuModOption-1.18-Forge-1.14.2
shutupexperimentalsettings-1.0.5
bettercombat-forge-1.6.2+1.18.2
cloth-config-6.5.102-forge
modernfix-forge-5.2.5+mc1.18.2
player-animation-lib-forge-1.0.2+1.18

**Comment by ZsoltMolnarrr** [comment]
Is this still an issue?
Are you sure your content is valid?

**Comment by steve12621** [comment]
I was testing on a completely new client so it should be true. It's not a issue if you are not using a datapack containing similar stuff. Another thing I should mention is, the dual_handed_slash_cross in your default sickle.json   [https://github.com/ZsoltMolnarrr/BetterCombat/blob/1.20.1/common/src/main/resources/data/bettercombat/weapon_attributes/sickle.json](url) somehow works well on my tinker sickles and did not crash my game
