### ISSUE TITLE
Mythic Metals + FirstPersonModel custom armor renderer

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [ZsoltMolnarrr/BetterCombat#27]
<img width="966" alt="Screenshot 2022-07-27 at 15 08 47" src="https://user-images.githubusercontent.com/4989469/181254846-66e8fa38-a5da-48b9-8b65-5b28337fde37.png">

**Comment by ZsoltMolnarrr** [comment]
The issue does not occour withou FPM installed.
Looks like nothing I can do in Better Combat to fix this.

**Comment by Fleyzi** [comment]
Not just Mythic Metals. [Immersive Armor](https://www.curseforge.com/minecraft/mc-mods/immersive-armors) have some issue too (all avaliable armor sets) (Wooden Armor for example)
![2022-07-31_17 22 43](https://user-images.githubusercontent.com/36078397/182031177-a109364b-fa0d-4cbe-8588-9f3badc413c5.png)
Phoenix Armor from [Paradise Lost](https://www.curseforge.com/minecraft/mc-mods/paradise-lost) (aka Aether Reborn) and some armor sets from [Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) (Knightmetal Armor for example)
![2022-07-31_17 12 47](https://user-images.githubusercontent.com/36078397/182031232-9da8a613-d148-4dd0-8ecc-7ccf5710e246.png)
![2022-07-31_17 16 17](https://user-images.githubusercontent.com/36078397/182031236-03762fb8-a7b6-484e-861b-fdd57f34d47d.png)

**Comment by ZsoltMolnarrr** [comment]
Thanks for the report$

**Comment by Fleyzi** [comment]
Dragon Armor (Helmet) from [DragonLoot](https://www.curseforge.com/minecraft/mc-mods/dragonloot) has some issue too
![2022-08-02_19 46 46](https://user-images.githubusercontent.com/36078397/182430311-3bc5941a-080f-4876-aa55-680e96d6ff84.png)

**Comment by ZsoltMolnarrr** [comment]
Fixed by FirstPersonModel 2.1.1
