### ISSUE TITLE
offhand items removed by 2 handed weapons

### ISSUE THREAD

**Issue by Goofishguy22** [ZsoltMolnarrr/BetterCombat#270]
**Minecraft version** - 1.20.1
**Mod loader** - fabric
**Mod version** - 1.7.2
**I am using the latest version available** - yes

**Describe the bug**
items in offhand get removed when holding 2 handed weapon

**To Reproduce**
1. put item in offhand(can be the 2 handed weapon)
2. hold 2 handed weapon in either main or offhand(only items in offhand will be removed)
3. item in offhand stops existing

**Expected behavior**
item is hidden from first and third person view and cannot be used but still exists in offhand

**Screenshots or video recordings**
https://github.com/ZsoltMolnarrr/BetterCombat/assets/140198913/5a1e4ff3-1688-4615-b916-f6e8d29bce3b

**Additional context**
mod used for the 2 handed weapons is simply swords

**Comment by TGWeaver** [comment]
How do you think you can you hold something in your offhand if you're using both hands for your weapon?

**Comment by Goofishguy22** [comment]
> How do you think you can you hold something in your offhand if you're using both hands for your weapon?

wdym

**Comment by Goofishguy22** [comment]
> How do you think you can you hold something in your offhand if you're using both hands for your weapon?

do you mean like not being able to use the item? because the item should not get deleted.

**Comment by ZsoltMolnarrr** [comment]
Hello!
I cannot help until you can specify which mod exactly is the one that causes this issue.
On its own, Better Combat does not have this problem.

Please provide more details, so I can fix.

**Comment by Goofishguy22** [comment]
after testing again(even with the mods used when i originally made this) it seems to no longer happen
