### ISSUE TITLE
Incompatibility with Inventorio

### ISSUE THREAD

**Issue by Abicce** [ZsoltMolnarrr/BetterCombat#271]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - 1.6.2
**I am using the latest version available** - for Fabric 1.19.2, yes

**Describe the bug**

 I’ve installed an inventory enhancement mod, Inventorio, by Lizard_OfOz but the game says the mod is incompatible with any version of Better Combat. I’ve raised this issue with the developer of Inventorio, and they said that the compatibility issue has only been resolved for versions 1.20+, but Better Combat never backported to 1.19. Is there any chance that this can be resolved? 

**To Reproduce**
1. Install the latest available version of Inventorio for Fabric 1.19.2
2. Drag and drop into mods folder (contains BetterCombat 1.6.2 for Fabric 1.19.2)
3. Start up the game

**Expected behavior**
An error message appears that says that Inventorio is incompatible with any version of Better Combat, advising to remove one or the other. Takes you back to launcher upon dismissal

**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Issue reported for non-latest version.
Only latest version is provided support for.
