### ISSUE TITLE
Farmer's Delight Knifes don't have proper attack animations

### ISSUE THREAD

**Issue by GodzillaFan13** [ZsoltMolnarrr/BetterCombat#273]
1.19.2
forge
bettercombat-forge-1.7.1+1.19
yes?

Farmers delight knives aren't registered as "proper" knifes with attack animations, whilst FD compatibility knifes (Create: Alloyed and Oreganized) do have proper attack animations.

To Reproduce
1. have Oreganized, Farmer's delight, bettercombat, and Create: Alloyed installed

Expected behavior
FD knives using proper knife animations. 

**Screenshots or video recordings**

**Comment by steve12621** [comment]
try deleting the "farmersdelight" after "blacklist_item_id_regex" in the minecraft folder, config/bettercombat/fallback_compatibility.json ?

**Comment by ZsoltMolnarrr** [comment]
Next release will contain fixed default configurations for these.

**Comment by GodzillaFan13** [comment]
something that i found out whilst playing yesturday is that the steel knifes (and presumably the electrum ones too) are unable to break blocks.  (EDIT) nevermind i just have .0005 braincells lol
