### ISSUE TITLE
Condition request - NOT wearing a shield.

### ISSUE THREAD

**Issue by zekeflynn** [ZsoltMolnarrr/BetterCombat#275]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO
YES
**Is your feature request related to a problem? Please describe.**
Nope
**Describe the solution you'd like**
I would like a condition for NO_SHIELD 🙂 the list of conditions includes "NO_OFFHAND_ITEM" & "OFF_HAND_SHIELD". I'd simply like a negative version of the latter, so that attacks still work - say - if I have a torch on the offhand, but not when paired with shields.

**Describe alternatives you've considered**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Will be implemented as part of https://github.com/ZsoltMolnarrr/BetterCombat/issues/277
