### ISSUE TITLE
Darkin Scythe's abilities don't work together

### ISSUE THREAD

**Issue by ItzTK** [ZsoltMolnarrr/BetterCombat#276]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - 1.7.1
**I am using the latest version available** - For 1.19.2 yes

**Describe the bug**
Darkin Scythes _Umbral Trespass_ ability can't be used for a few seconds after benefiting from its _Omnivamp_ ability. If this is an intentional balancing thing then it needs to be more clear.

**To Reproduce**
1. Be in survival mode
2. Use Darkin Scythe on mobs (multiple will showcase the issue better)
3. Try to _Umbral Trespass_ 
4. Don't take any damage or wait a few seconds for _Omnivamps_ cooldown

**Expected behavior**
I would expect you to be able to use _Umbral Trespass_ when its not on cooldown. _Omnivamp_ shouldn't be relevant to the abilities usage at all. It feels clunky and comes off as confusing. Like in league it should be used to escape multiple enemies for a moment. That is nearly impossible, if you take any amount of damage then attack _Omnivamps_ cooldown will lock you out of that option.

**Comment by ZsoltMolnarrr** [comment]
This is not possible to fix from Better Combat.
The mod in question needs to rely use Java API provided by Better Combat to trigger the abilities in question.
