### ISSUE TITLE
Conflict with Building Gadgets

### ISSUE THREAD

**Issue by Junkyard-Aristocrat** [ZsoltMolnarrr/BetterCombat#278]
Minecraft version: 1.19.2
Mod loader: Forge
Mod version: 1.19.2
I am using the latest version available for 1.19.2

Describe the bug:
I added on several mods to the modpack All the Mods 8.
When trying to use the building gadget and exchange gadget from Direwolf20's Building Gadgets mod, the blocks to be placed/affected always showed as red and I was unable to place or exchange them.
Through a process of elimination I determined that the conflict was with your mod.

To Reproduce
1. Download ATM 8, add on your mod
2. Attempt to use Direwolf's building gadgets

Expected behavior:
When using the building gadgets, it should not show red if the necessary blocks are in the player's inventory and the player should be able to place/exchange them without issue upon clicking

Additional Context:
I'm posting this issue here as opposed to on Building Gadgets because, as far as I'm aware, that mod merely adds some items and has had no issues with 400+ other mods.

**Comment by ZsoltMolnarrr** [comment]
Better Combat does not interact with any items from Building Gadgets, nor left click, nor right click.
If you are sure Better Combat is causing the issue, please provide more details, preferrably video footage.
