### ISSUE TITLE
[Forge] Putting Two-Handed in the off hand will disappear

### ISSUE THREAD

**Issue by Dr-WeiAL** [ZsoltMolnarrr/BetterCombat#279]
**Minecraft version** - 1.20.1
**Mod loader** - NeoForge 47.1.65
**Mod version** - 1.7.3
**I am using the latest version available** - yes

**Describe the bug**
As the title says.
Putting Two-Handed in the off hand will disappear.

**To Reproduce**
1. Take the Two-Handed weapon.
2. Use "F" or any method to put it in the off hand.
3. Weapons are gone.
4. Open Inventory at this time and you'll see that it's on the off hand, but it doesn't show up
5. If you keep pressing "F", the previous weapon will disappear.

**Expected behavior**
It shouldn't go away.

**Screenshots or video recordings**
![1](https://github.com/ZsoltMolnarrr/BetterCombat/assets/47446553/d68f3fbd-a4b3-41f2-b396-5825f796d7bc)

**Additional context**
If you need to test it, you can try the following mods
https://www.curseforge.com/minecraft/mc-mods/l2weaponry
https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm

**Comment by ZsoltMolnarrr** [comment]
Hello!
There are 2 known solutions for that problem.
- Do not use newer version than Forge 47.1.3 (use the officially recommended version), new versions are broken 🙂
- If using Apugli and TooManyOrigins mods, make sure to update them

![image](https://github.com/ZsoltMolnarrr/BetterCombat/assets/4989469/9f301a2c-5e3a-4279-8598-6811a230caa9)

**Comment by Dr-WeiAL** [comment]
That means the problem is unsolvable?
Some of the mods I added require a higher version of Forge than 47.1.3, so the first solution could not be used
These two mods don't have a 1.20.1 version of Forge, so the second solution can't be used either

**Comment by ZsoltMolnarrr** [comment]
That means, the modloader itself introduced breaking changes.
Use the recommended version, or experiment with unstable version on your own behalf.

**Comment by Dr-WeiAL** [comment]
Oh well, I was misremembering, I didn't add a mod that requires a higher version of Forge than 47.1.3, so let's just go with the first option

**Comment by CodySpirits1** [comment]
As a heads up, this is still an issue with Forge 47.2.0, the currently recommended forge version, as well as Forge 47.2.1.

**Comment by ZsoltMolnarrr** [comment]
Forge broke its own API and internal behaviour without considering whether or not mods will continue to work, then started recommending the new broken version.
I have no capacity to babysit the problems Forge creates for itself.
Forge support will likely end right here.

NeoForge support will likely replace it.

**Comment by ZsoltMolnarrr** [comment]
Fixed by Better Combat 1.8.0 for Forge. Requires Forge at least 47.2.0
