### ISSUE TITLE
Compatibility with Customizable Player Models 

### ISSUE THREAD

**Issue by Aabaddon** [ZsoltMolnarrr/BetterCombat#280]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
It is kind of frustrating using both mods together because if you create an animation for the arms with CPM (running animation, walking animation, jumping animation) the animations of Better Combat simply conflict and it doesnt play any of the two, instead the model just kind of goes to the "base pose" and attack with both arms and the weapon pointing to the floor

**Describe the solution you'd like**
Make Better Combat compatible by overriding the animations just when swinging the sword.

**Describe alternatives you've considered**
if it is not possible to override the animations you could atleast make that if it tries to play two animations at the same time the animations of better combat dont play? but i dont see this as a solution.

**Additional context**
Im playing on a server with friends and im the only one with customizable player models, the server has better combat and this conflict just ruins the experience but i like both mods.

**Comment by ZsoltMolnarrr** [comment]
This is specifically addressed that no such compatibility is possible.
https://github.com/ZsoltMolnarrr/BetterCombat#-mod-compatibility

Moreover, since I am not the developer of PlayerAnimator library, I cannot even implement this feature in Better Combat.
