### ISSUE TITLE
Dual Wield, more info

### ISSUE THREAD

**Issue by tablenitro** [ZsoltMolnarrr/BetterCombat#281]
its not really a suggestion as much a question, how much it buffs the speed when you dual wield and if you could pls add this info in the desc of the item when you dual wield, thanks

**Comment by tablenitro** [comment]
Dont mind my broken english

**Comment by ZsoltMolnarrr** [comment]
Hello!
I updated the project readme:
> Attacking with dual wielded weapons (held weapons are used alternated, +20% attack speed while dual wielding, Server configurable)
