### ISSUE TITLE
ANIMATION BUG

### ISSUE THREAD

**Issue by Fiiter910** [ZsoltMolnarrr/BetterCombat#283]
Minecraft version: 1.19.2 
Mod loader: Forge 43.2.3 
Mod version: bettercombat-forge-1.7.1+1.19.jar 

When I attack with any weapon the animaion just bug it with the player model. Im playing in MULTIPLAYER

https://github.com/ZsoltMolnarrr/BetterCombat/assets/81747601/945bb96f-8d55-4bba-8fd3-b1ef12844b5e

**Comment by ZsoltMolnarrr** [comment]
This is caused by another mod, that manages render states incorrectly.
The usual suspect is MCA Reborn.
Since this problem does not occur when only Better Combat is installed, this issue is not actionable.

**Comment by Fiiter910** [comment]
@ZsoltMolnarrr 
So there is no solution for this ?

**Comment by ZsoltMolnarrr** [comment]
As mentioned there is nothing I can do about it.
Better Combat does not implement animation capabilities, only uses PlayerAnimator library to play animation files.
Incompatible mods such as MCA Reborn need to implement their changes in a more compatible manner (which is certainly possible), to be compatible with the First Person Animation playback of PlayerAnimator library.

The solution is that, which ever mod causes this, needs to fix their render code, and stop overriding render (player model part visibility) states.
