### ISSUE TITLE
More configuration for Mine with weapons setting

### ISSUE THREAD

**Issue by Puffle2K** [ZsoltMolnarrr/BetterCombat#284]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I want to have mine with weapons off, but some things that I use to mine are considered weapons. Specifically axes, but I believe that some mods add weapons that are also used for mining.

**Describe the solution you'd like**
I believe that having the ability to configure hotbar slots to ignore "Mine with weapons - No" would be the best way to solve this issue.

**Describe alternatives you've considered**
Another option is to add another blacklist to the client config, like the Swing thru grass blacklist, except for Mine with weapons.

**Comment by ZsoltMolnarrr** [comment]
This suggestion would not fit the project vision as is, sorry.

**Comment by Puffle2K** [comment]
I don't quite understand how more configuration doesn't fit the project, especially since there is already configuration for a different setting.

**Comment by ZsoltMolnarrr** [comment]
Upon further consideration I do agree that this might worth some investigation.
The blacklist approach could work, but the hotbar specific behaviour definitely not.
Unfortunately currently I am very busy, Better Combat won't receive functional updates soon.

**Comment by ZsoltMolnarrr** [comment]
Will be published with next release.
