### ISSUE TITLE
Inventorio's Weapon Slot doesn't function properly with Better Combat

### ISSUE THREAD

**Issue by emorydeer2** [ZsoltMolnarrr/BetterCombat#286]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - v1.7.1+1.19

**Describe the bug**
Putting a weapon in the Inventorio weapon slot and holding attack with Better Combat installed makes you perform only weak attacks, and the same attack animation, the first attack is normal, but the rest are weak as long as it is held

**To Reproduce**
1. Get a weapon
2. Put it in the Inventorio weapon slot
3. Find a target
4. Hold the attack bind
 
**Expected behavior**
I expected the weapon to function as if I were using it in the hotbar, respecting the cooldown and combo-ing.

**Screenshots or video recordings**
![image](https://github.com/ZsoltMolnarrr/BetterCombat/assets/107522398/46b8ef46-f28f-412b-b85e-38e62f2eebe0)

**Additional context**
I'm using a modpack with a few other weapons, though I did use a vanilla Netherite Sword so I don't think it had much effect.

**Comment by ZsoltMolnarrr** [comment]
Better Combat has nothing to do with Inventorio mod.
I have no development capacity to implemenet compatibility with it, nor do I intend to maintain such.
Better Combat is open sourced, and it is also open for API requests if needed for integration.
