### ISSUE TITLE
tlauncher issue

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [ZsoltMolnarrr/BetterCombat#291]
**Minecraft version** - 1.18.2
**Mod loader** - forge
**Mod version** - 1.6..2
**I am using the latest version available** - For The MC Version 1.18.2

**tlauncher crashes when i load the game**

**To Reproduce**
1. Download Tlauncher
2. Install Mod On Forge
3. Load Tlauncher 1.18.2
4. It Crashes The Darn Game

**Expected behavior**
No Problem

**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Stop using pirated version.

**Comment by SonicTheHedgehog58987276** [comment]
what version?
