### ISSUE TITLE
Crash in 1.20.1 Forge

### ISSUE THREAD

**Issue by kgs233** [ZsoltMolnarrr/BetterCombat#293]
**Minecraft version** - ?
1.20.1
**Mod loader** - ?
Forge
**Mod version** - ?
1.7.4+1.20.1
**I am using the latest version available** - ?
yes

**Describe the bug**
After the game launch, report an error on the modloading-worker, immediately after that crash

**To Reproduce**
Launch Game -> Loading Mod -> Crash

**Expected behavior**
Normal launch Game

**Screenshots or video recordings**
Don't need

**Additional context**
Log: https://mclo.gs/G1xJgQW

**Comment by ZsoltMolnarrr** [comment]
You are not using the latest version.

It is crashing due to the fallback compatibility configuration file being malformed.
An update was already released to avoid crashing, but incorrect config files will be reset. 

Feel free to reopen the issue if needed.
