### ISSUE TITLE
[1.7.1+1.19-forge] Sudden crash from better combat? or?

### ISSUE THREAD

**Issue by Baenjamin** [ZsoltMolnarrr/BetterCombat#294]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - 1.7.1
**I am using the latest version available** - Yes

Not sure exactly what caused it as i was playing my modded world and had to log out for a bit. And when i logged back into the world, i crashed before i could fully load in.

Crash Log:
[crash-2023-10-29_00.29.54-client.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/13196824/crash-2023-10-29_00.29.54-client.txt)

Latest Log: 
[latest.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/13196829/latest.log)

**Comment by ZsoltMolnarrr** [comment]
Looking at this crash, I have no idea what might be the root cause.
1.19.2 versions are no longer being developed or supported, hence there is no action to take here.
Updating to newer version is recommended.

Feel free to reopen in case this happens on current versions.
