### ISSUE TITLE
Unknown breaking changes to datapack configs in 1.8.0+

### ISSUE THREAD

**Issue by moninformateur** [ZsoltMolnarrr/BetterCombat#296]
**Minecraft version** - 1.20.1
**Mod loader** - 47.1.3
**Mod version** - 1.8.0 vs 1.7.4
**I am using the latest version available** - No (because support for NeoForge was dropped in 1.8.1)

**Describe the bug**
My modpack uses both Better Combat and Simply Swords. 

When wielding claymores from Simply Sword, my wish was to use Better Combat's pose for two handed swords (as I prefer Better Combat's pose), so I made a datapack which looks like this:

_Datapack's path is: \data\my_custom_datapack\data\simplyswords\weapon_attributes\iron_claymore.json_

iron_claymore.json:
```
{
  "attributes": {
    "pose": "bettercombat:pose_two_handed_sword"
  }
}
```

When using Better Combat 1.7.4, the "swinging" animation is as intended and uses Better Combat's poses.
When using Better Combat 1.8.0+, the "swinging" animation are not working, vanilla animations are used.

**To Reproduce**
1. Use the datapack mentionned earlier.
2. Upgraded Better Combat from 1.7.4 to 1.8.0.
3. The two_handed_sword pose does not work anymore and is instead the vanilla pose.

**Expected behavior**
The custom pose should use Better Combat's pose. The repo still hasn't changed.

**Comment by ZsoltMolnarrr** [comment]
The JSON you provided does not inherit from any other weapon attributes, contains only a pose, making it invalid.

**Comment by moninformateur** [comment]
After testing it, it seems you are right, using the complete JSON it does work at intended.

Is there any reason my datapack would work in 1.7.4 and not in 1.8.0? 

Anyway, thank you for your fast help. I will correct the datapacks

**Comment by ZsoltMolnarrr** [comment]
The json you posted should never have worked with anything.
Recently changes were made to data file parsing to support ranged weapons.
