### ISSUE TITLE
New error happened.   1.8.1

### ISSUE THREAD

**Issue by Atench** [ZsoltMolnarrr/BetterCombat#297]
Well, there is a mistake with your mod. My 1.20.1 Minecraft crashed.The version of Forge is 47.1.43.
Here is the report and I really want to know what had happened and want to install your mod successfully because I really love it!
I would appreciate it if you can fix this error.
"The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance"
[crash-2023-10-30_01.13.47-client.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/13198712/crash-2023-10-30_01.13.47-client.txt)

**Comment by ZsoltMolnarrr** [comment]
Release notes state 1.8.1 for Forge: _(Forge) Requires at least Forge 47.2.0_
