### ISSUE TITLE
game crash after drying 1.20.1 forge

### ISSUE THREAD

**Issue by kaairu** [ZsoltMolnarrr/BetterCombat#298]
**Minecraft version** 1.20.1
**Mod loader** - forge
**Mod version** - 1.8.1
**I am using the latest version available** - yes

**Describe the bug**
i used the command /kill on myself and when i tried to respawn by game crashed

**To Reproduce**
use /kill @s

**Expected behavior**
to respawn normally

**Screenshots or video recordings**
N/A

**Additional context**
this is most likely a mod conflict which i cant wrap my head around

**crash logs**
https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/1101396706861531157/1168319220237488258/crash-2023-10-29_15.35.13-client.txt?ex=65515510&is=653ee010&hm=cc444e528bdac3f87dcb5c115554741bd232db0c2bc112da5e3126004acb0d0a&&raw=false

https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/1101396706861531157/1168319220568825887/latest.log?ex=65515510&is=653ee010&hm=f18235dab9d8e7681224b09f054c85bc2b93dbea22f5b3565e1d32a1f950221f&&raw=false

**Comment by ZsoltMolnarrr** [comment]
A mod named "Just Leveling" is performing mixin on Better Combat, meaning it alters the code of Better Combat, leading to a crash.
Mixins towards other mods are completely unsafe, and not supported at all.

**Comment by kaairu** [comment]
so i should report this to just leveling since it won't be fixed on ur end correct
