### ISSUE TITLE
Keep 1.20.1 version on Forge 47.1.3 version

### ISSUE THREAD

**Issue by ffuentesm** [ZsoltMolnarrr/BetterCombat#299]
Due to the whole Forge/Neoforge problems, apparently, a LOT of mods decided to stay on Forge 47.1.3 and crash if Forge is updated to any newer version. As of now, Forge seems to have stopped 1.20.1 support too. So, until 1.20.2+ becomes stable, could you stay on 47.1.3 for the 1.20.1 version?

**Comment by ZsoltMolnarrr** [comment]
The current fiasco with all the different Forge versions is a disaster. I understand players getting confused.

Here is the current support table:
- Better Combat (Forge) 1.8.0+1.20.1 supports Forge 47.1.3
- Better Combat (Forge) 1.8.1+1.20.1 supports Forge 47.2.0

Is there a good way to indicate this on CruseForge?

**Comment by ffuentesm** [comment]
If I recall, you can add the forge version of the File tag. 
And you can always add a warning to the mag page description.
