### ISSUE TITLE
[1.20.1-1.8.1] Crash when trying to load into game.

### ISSUE THREAD

**Issue by Baenjamin** [ZsoltMolnarrr/BetterCombat#300]
Minecraft version - 1.20.1
Mod loader - Forge
Mod version - 1.8.1
I am using the latest version available - Yes

Was playing my updated 1.20.1 pack, and when i tried to log in i got this message? Not sure if it's better combat, or this other mod i'm using called 'Just Leveling'. It's not a fresh world as i've been playing it smoothly for some hours now. 

Crash report:
[crash-2023-10-31_23.34.06-client.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/13221826/crash-2023-10-31_23.34.06-client.txt)

Latest Log:
[latest.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/13221828/latest.log)

**Comment by ZsoltMolnarrr** [comment]
"Just Leveling" is performing mixin on Better Combat, meaning it alters the code of Better Combat, leading to a crash.
Mixins towards other mods are completely unsafe, and not supported at all.

**Comment by Baenjamin** [comment]
I see i see. Ima go msg that just leveling guy about it then. tyty.
