### ISSUE TITLE
Compatibility with the Truly Modular Series

### ISSUE THREAD

**Issue by Niphoria** [ZsoltMolnarrr/BetterCombat#301]
**I read project readme, checked client side and server side configurations, and no such feature exists**
YES

**Is your feature request related to a problem? Please describe.**
For some reason the swing overhaul is not working with the items from the Truly Modular Series even tho fallback is enabled and it should find the items via item naming

**Describe the solution you'd like**
The swing overhaul working with the Truly Modular Series

**Describe alternatives you've considered**
Ive tried none so far as this is an incompatibility issue

**Additional context**
The links to the mod:
https://modrinth.com/mod/modular-item-api
https://modrinth.com/mod/truly-modular-archery
https://modrinth.com/mod/truly-modular-arsenal

**Comment by ZsoltMolnarrr** [comment]
It is the other way around my friend.
Better Combat is a low level mod, providing mechanics, API for compatibility, and configurable auto compatibility. It does not reference or support any specific content mod directly tho.
