### ISSUE TITLE
[1.20.1] Modular Golems Compat

### ISSUE THREAD

**Issue by knighthawkUnlimited** [ZsoltMolnarrr/BetterCombat#302]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES, to the best of my knowledge.

**Is your feature request related to a problem? Please describe.**
I was wondering if it was possible to apply Better Combat animations to bipedal mobs. if so could you please link a mod that does it, and if not I believe it would be an interesting idea.

I had this idea when I attempted to give a two handed weapon to a Humanoid Golem from 'Modular Golems', where it used the vanilla one handed hit style animation and looked a bit silly.

After asking the 'Modular Golem' Dev whether it is possible to have them use your animations, they requested an example for reference;
So if you could let me know if this is possible, and if so provide an example that would be wonderful.

Otherwise, if this is something that is not yet doable then this is more of a suggestion than a question. 

but either way, thank you for your time :)

Link to Modular Golems: https://legacy.curseforge.com/minecraft/mc-mods/modulargolems

**Comment by ZsoltMolnarrr** [comment]
Better Combat is much more than just animations.

Also the animation library of Better Combat can only animate player entities. For usecases you seek, GeckoLib is the commonly used solution.
