### ISSUE TITLE
Incompatible with JustLeveling

### ISSUE THREAD

**Issue by squarzyy** [ZsoltMolnarrr/BetterCombat#303]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - BetterCombat 1.7.1 and JustLeveling v.1.7
**I am using the latest version available** - Yes, both of them

**Describe the bug**
Weird Bug, Randomly Crashes and unexpected when it will be happen

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a New World
2."Disconnected from server" warning randomly appear
3. Enter the World again
4. Crash Report Screen

**Expected behavior**
No ideas why, I'm sorry

**Additional context**
Here's the crash report:
https://gist.github.com/HUYBUSSIN/ab5b3a2b590e609d5a870d4e2487d50e

**Comment by ZsoltMolnarrr** [comment]
"Just Leveling" is performing mixin on Better Combat, meaning it alters the code of Better Combat, leading to a crash.
Mixins towards other mods are completely unsafe, and not supported at all.

**Comment by squarzyy** [comment]
so the problem is come from Justleveling side right ?
