### ISSUE TITLE
Can't detect dependency

### ISSUE THREAD

**Issue by festro** [ZsoltMolnarrr/BetterCombat#304]
**Minecraft version** - 1.20.1
**Mod loader** - 47.2.6
**Mod version** - 1.8.1
**I am using the latest version available** - as far as I know

**Describe the bug**
mod does not detect dependent mod "playerAnimator" I have 1.0.2-rc1.

**To Reproduce**
1. start the game
2. Click on wait for crash

**Expected behavior**

**Screenshots or video recordings**

**Additional context**

[crash-2023-11-15_20.59.30-fml.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/13372498/crash-2023-11-15_20.59.30-fml.txt)

**Comment by ZsoltMolnarrr** [comment]
This issue seems to have nothing to with the source code of Better Combat, this looks purely an installation issue.
Manually drag n dropping mods together is not supported, please use a proper launcher like CurseForge or Modrinth apps, to create your installation.

**Comment by festro** [comment]
I only use curseforge, haven't done manual install in forever.
