### ISSUE TITLE
Config Option For Shielding With No Slowdown (1.19.2 please)

### ISSUE THREAD

**Issue by ThatGuyJess** [ZsoltMolnarrr/BetterCombat#305]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO
Yes, I checked and no such feature is available.

**Is your feature request related to a problem? Please describe.**
No frustration is involved, but while playing on 1.12.2 (recently moved to 1.19.2) I found that being able to maintain my walk or run speed while shielding made combat more enjoyable. Being able to maneuver quickly during fights give more opportunity for fast-paced and compelling gameplay. From my experience it especially helps with mob mods that buff, speed up, or add in fast and powerful mobs.

**Describe the solution you'd like**
When you shield you don't slow down, whether sprinting or walking. You can also go from walking while shielding to sprinting while shielding.

**Describe alternatives you've considered**
I've looked for another mod as an alternative but the only other one that exists is way out dated (1.12.2) with no plans on updating; Also I feel like the concept just fits with better combat's mechanics and would make other players appreciative.

**Additional context**
Old mod that has the feature:
_"NoSlow"_
https://www.curseforge.com/minecraft/mc-mods/noslow

Thanks for reading.

(Also, sorry for no label/bad formatting, I don't use GitHub often at all)

**Comment by ZsoltMolnarrr** [comment]
Shield related features are out of scope for Better Combat.
Also 1.19.2 versions are no longer being developed.
