### ISSUE TITLE
Second layer appears in first person

### ISSUE THREAD

**Issue by Caisenn** [ZsoltMolnarrr/BetterCombat#306]
**Minecraft version** - 1.20.1
**NeoForge** - 47.1.79
**Mod version** - 1.8.0
**I am using the latest version available**

This happens when playing with mod "Doctor Who - Regeneration (42.0.0)"

https://github.com/ZsoltMolnarrr/BetterCombat/assets/136863281/e3407fb2-75c4-4573-be8a-e842c77d4e40

Mod list:
Better Combat - 1.8.0;
Cloth Config API - 12.0.109;
Doctor Who - Regeneration - 42.0.0;
playerAnimation - 1.0.2-rc1.

P.s. Its also happens when using better combat 1.8.1 and forge 47.2.16, so that doesnt matter

**Comment by ZsoltMolnarrr** [comment]
This is likely a render state conflict between PlayerAnimator and Doctor Who.

Better Combat has no code related to this, that could be modified to fix this.

**Comment by SugmaLikeSlugma** [comment]
i have the same issue. I do not use the Dr Who mod.
