### ISSUE TITLE
Feature request - Dynamic two-handed / one-handed weapon mechanic

### ISSUE THREAD

**Issue by eilamg** [ZsoltMolnarrr/BetterCombat#307]
**I read project readme, checked client side and server side configurations, and no such feature exists**
Yes.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'm wondering if it would be possible to add a dynamic two-handed/one-handed weapon mechanic. That is, a weapon will use different attack animations (and possibly other properties) when used when holding / not holding another item in the offhand slot.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Cheers

**Comment by ZsoltMolnarrr** [comment]
The purpose of this mod is to recreate the melee combat system of Minecraft Dungeons.
I am sorry, this suggestion falls outside of the project scope.
