### ISSUE TITLE
[1.19.2] Crashes on Launch

### ISSUE THREAD

**Issue by somebodyandnobody** [ZsoltMolnarrr/BetterCombat#311]
**Minecraft version** - 1.19.2
**Mod loader** - Forge
**Mod version** - 1.7.1+19
**I am using the latest version available** - Yes

**Describe the bug**
The game simply does not launch. It reopens the launcher and says an unexpected error occurred. 

**To Reproduce**
1. Start the game on the recommended version with the mod installed.

**Expected behavior**
The game would start.

**Comment by ZsoltMolnarrr** [comment]
This is surely an installation problem. I recommend retrying the installation, using a launcher with automatically resolved dependencies feature (CurseForge launcher).
