### ISSUE TITLE
Two-Handed weapons off hand render

### ISSUE THREAD

**Issue by WaspYarp** [ZsoltMolnarrr/BetterCombat#312]
I got an idea, and this will be purely visual, i dont know how hard it would be...

But when you hold a Two-Handed weapon/item, the item in the off hand dissapear, is no more visible.

So my idea is like render the item in the back, like the shield, it would be soo awsome, or another weapons too

**Comment by ZsoltMolnarrr** [comment]
There are mods to do this, such as Backslot or WeaponMaster.
