### ISSUE TITLE
Animation glitch/janky transition on certain first-person attacks (particularly noticeable with shields)

### ISSUE THREAD

**Issue by Nereithr** [ZsoltMolnarrr/BetterCombat#313]
**Minecraft version** - 1.20.1
**Mod loader** - Forge 47.2.17
**Mod version** - 1.8.1
**I am using the latest version available** - Yes

**Describe the bug**
First of all, great mod! 

Attacking with a shield equipped (whether offhand is rendered during attacks or not) randomly results in an annoying model flicker. I linked a video of the issue and it appears to be either the third person model randomly deciding to also render at the same time as the first person model or a very sudden transition on the last frame of the attack animation to the first-person model.  Additionally, as you can see in the video, this doesn't happen on every attack.

This is particularly jarring with shields because it occurs even when offhand item animations are disabled, suggesting this is a bug. I'm linking a video of the issue, as well as a screenshot of the problem frame.

**To Reproduce**
1. Go into a world
2. Equip a one-handed weapon and an offhand item, preferably a bulky one, like a shield.
3. Attack with weapon for a while until the glitch occurs (should occur  within the first 2-3 attacks)

This is reproducible with just Better Combat and its dependencies and no other mods.

**Expected behavior**
No distracting animation glitches.

**Screenshots or video recordings**
[Link to an imgur video of the issue](https://imgur.com/k5ACgV7).

One of the problem frames.
![mpv-shot0001](https://github.com/ZsoltMolnarrr/BetterCombat/assets/72263884/49c1dfe6-8246-4e39-91cc-66816aec84ef)

**Additional context**
Also occurs on 1.19.2 Forge.

**Comment by ZsoltMolnarrr** [comment]
I am unable to improve this further, I don't know any technical solution.
Anyone is free to send an improvement Pull Request.
Otherwise this issue is non-actionable. :(
