### ISSUE TITLE
Backport bug fixes

### ISSUE THREAD

**Issue by DaddySpin** [ZsoltMolnarrr/BetterCombat#314]
Can we please have the bug fixes from version 1.8.1 on forge 47.1.3?
![chrome_t4GksbrlCD](https://github.com/ZsoltMolnarrr/BetterCombat/assets/34575655/93fc9f0f-07f5-4e6a-8624-a8b966ed2609)

**Comment by Nereithr** [comment]
For what it's worth the latest Curseforge version of BetterCombat seems perfectly compatible with the latest NeoForged 47.1.84 if you simply go into the jar file and change the Forge version number requirement in META-INF\mods.toml. Obviously this is just a short test and there could be some potential incompatibilities that a 5 minute playsession can't reveal.

**Comment by DaddySpin** [comment]
See that would work for your average player but I'm running 650 mods.

**Comment by ZsoltMolnarrr** [comment]
Better Combat 1.8.0 for Forge 47.1.3 version exists, with the mentioned bug absent.
