### ISSUE TITLE
Dual Wield Same Weapons Only

### ISSUE THREAD

**Issue by mahjerion** [ZsoltMolnarrr/BetterCombat#315]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO

YES

**Is your feature request related to a problem? Please describe.**

Not an urgent issue, but sometimes having differing weapons makes dual wielding animations look a bit janky. Works fine though.

**Describe the solution you'd like**

If you could have in the config an option to make it so only weapons of the same type can be held in the offhand. So daggers with daggers only, not daggers with 1-h hammers, etc.

**Additional context**

Making an action-rpg modpack and would be neat to have some uniformity. Not a big deal though! Thought you could use a similar system to your 2-h weapons forcing offhand.

**Comment by ZsoltMolnarrr** [comment]
This is out of scope. I am sorry.
There is no reason to implement this restriction.
