### ISSUE TITLE
Mod crashes my game on Linux

### ISSUE THREAD

**Issue by internetrenegade** [ZsoltMolnarrr/BetterCombat#316]
**Minecraft version** -  1.20.1?
**Mod loader** - Forge?
**Mod version** - 1.8.1?
**I am using the latest version available** - yes?

**Describe the bug**
The game crashes when loading.

**To Reproduce**
1. Put Beter Combat in mods folder
2. Launch Minecraft on Debian 12
3. error

**Expected behavior**
my game should have loaded

**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
I don't see how I can help this.
Make sure to have:
- Purchased copy of the game
- Using a proper launcher that manages mods dependencies for you (such as CurseForge app)
- Not to drag and drop jar files manually
