### ISSUE TITLE
When have BC, my modpack can't load successfuly with more than 90 mods

### ISSUE THREAD

**Issue by YakumoUUZ** [ZsoltMolnarrr/BetterCombat#318]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.6.2
**I am using the latest version available** - yes

**Describe the bug**
When I have BC in my pack, it can't load successfuly with more than 90 mods.

**To Reproduce**
Just start mod pack

**Expected behavior**
Modpack's loading will stuck, the game's window won't show up

**Screenshots or video recordings**
![TC9B~~MWQ~7DENG`NQ((%(U](https://github.com/ZsoltMolnarrr/BetterCombat/assets/122345646/b2697dfb-4448-458c-81b7-5909f04ff359)

**Comment by ZsoltMolnarrr** [comment]
1.18.2 versions are no longer supported. Hence closing this issue.

Make sure to have:
- Purchased copy of the game
- Using a proper launcher that manages mods dependencies for you (such as CurseForge app)
- Not to drag and drop jar files manually
