### ISSUE TITLE
Blocking/Defensive options for Weapons

### ISSUE THREAD

**Issue by DarianStardust** [ZsoltMolnarrr/BetterCombat#321]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I find it very difficult to find opportunities to dual wield, or wield two-handed weapons, as most of the time I will be obligated to wield a Shield almost all times to not die to skeletons and other ranged mobs, especially with mods that increase difficulty, making skeletond Lethal. it's rare that I only ever need to fight melee mobs, and thus, rare to be free to use this mod fully or use alternate playstyles that don't require the shield

**Describe the solution you'd like**
Give most weapons a Blocking stance on Right Click, being able to use dual weapons/Two-Handed weapons to Reduce damage taken, or perhaps parry it(?) based on the type of weapon, Two-handed blades for example: Strong block that reduces most of damage taken, given the wide size of the blade, Then, swords block less damage as a trade for being more agile, while weapons that are entirely offensive having weak, or no way to block, but a parry instead based on timing, like dagger and chakrams, very fast and powerful, very tiny and thin to realistically offer protection

**Describe alternatives you've considered**
If those are not possible, maybe have certain weapon types inherently give extra armor, or even have heavy weapons get Bonus armor when paired with Heavy armor, and light weapons be faster/grant speed with Light armor values, 

**Additional context**
Skeletons are a pain to deal with as dual wield/Two-Handed, they get shots for free, and it would just be very cool to use two swords and hold them in an X shape to block like anime style, or be a tanky brute wielding a hammer

**Comment by ZsoltMolnarrr** [comment]
This feature is listed on the development roadmap on Discord :)

**Comment by DarianStardust** [comment]
> This feature is listed on the development roadmap on Discord :)

Oh, that's nice
Just curious, what you think of the Weapon+Armor weight sinergy?

**Comment by ZsoltMolnarrr** [comment]
Armor weapon weight is unlikely to be added, doesn't fit the original development scope (Minecraft Dungeons melee combat system)
What might be added tho is attack specific extra knockback.
