### ISSUE TITLE
It's basically unhittable when attacking small zombies through half a brick.

### ISSUE THREAD

**Issue by EmptyDreams** [ZsoltMolnarrr/BetterCombat#322]
**Minecraft version** - 1.20.1

**Mod loader** - Fabric

**Mod version** - 1.8.3

**I am using the latest version available** - Yes

**Describe the bug**

You can see the effect in the video below, I had a hard time hitting the zombie with my weapon when there was half a brick between me and the zombie (after many tests I found that there was a chance of hitting the zombie but I didn't find out how to do it in order to get a 100% hit rate), whereas I was able to hit the target normally with the non-weapon props (at this point the module's attack effect wasn't in effect).

**To Reproduce**
1. Place the squares as shown in the video, and you can use any combination of squares and half-bricks.
2. hand-held weaponry
3. Use the left mouse button to attack the small zombies

**Expected behavior**

I should be able to hit the zombie properly.

**Screenshots or video recordings**

https://github.com/ZsoltMolnarrr/BetterCombat/assets/44894906/e69715fd-fb36-4bb9-89d3-906b80add936

**Comment by ZsoltMolnarrr** [comment]
This is a limitation of the collision detection algorythm.
This mod was designed for casual players, definitely for the showcased entrapment situations. Mobfarm related issues will not be actioned.

You have the following options:
- change server settings to allow hitting though walls
- use a different mod for combat
