### ISSUE TITLE
forge 1.19.2 exit code -1 problem

### ISSUE THREAD

**Issue by WeebWarden** [ZsoltMolnarrr/BetterCombat#325]
**Minecraft version** - 1.19.2
**Mod loader** - 1.19.2 43.3.7
**Mod version** - BETA 1.7.1+1.19
**I am using the latest version available** - latest forge version of better combat for 1.19.2

**Describe the bug**
launching forge from minecraft launcher but fails to launch and i receive a exit code-1 error. only mod installed are oculus, rubidium, entity culling and better combat.

**To Reproduce**
1. Go to 'minecraft launcher'
2. Click on 'play'
3. See error

**Screenshots or video recordings**

https://github.com/ZsoltMolnarrr/BetterCombat/assets/157162101/7fdbefe4-baeb-440b-85f8-1d5a14b1e864

**Comment by ZsoltMolnarrr** [comment]
This very likely an installation issue.

## How to resolve issues:
### 1. Use a launcher app to install mods. 
These automatically resolve other required mods, and also show which mods need updating. I recommend the following:
- CurseForge official app https://download.curseforge.com
- Modrinth official app https://modrinth.com/app

Just create your own profile, open it, search for mod, click install and boom! The launcher downloads the mod with all of its required dependencies.
:no_entry_sign: I cannot provide support for manually drag and dropped jar files. Million things can go wrong in the process.

### 2. Make sure all mods are up to date
Check all mods in your launcher which one needs update.
Please never report issues about mod versions those aren't the current latest.
