### ISSUE TITLE
neoforge 1.20.1 support/build

### ISSUE THREAD

**Issue by AsheX1** [ZsoltMolnarrr/BetterCombat#327]
it does work on neoforge but need to edit mod.toml inside the bettercombat-forge jar
need to edit line 49
from versionRange="[47.2,)" #mandatory
to versionRange="[47.1,)" #mandatory

so it does work

it was also crashing on my heavy modded neoforge client but after editing the mod.toml it now boots there also

idk what the best way is on what to do
remove the line  49 from mod.toml or get an other build from you has support from you
[bettercombat-forge-1.8.1+1.20.1-modified.jar.zip](https://github.com/ZsoltMolnarrr/BetterCombat/files/14043830/bettercombat-forge-1.8.1%2B1.20.1-modified.jar.zip)
this is the modified jar i had to put .zip on the name els github wont let me upload -_-
any ways just rename it or just compare the mod.toml as this is all i have changed
mod.toml is found inside the META-INF folder

**Comment by ZsoltMolnarrr** [comment]
Better Combat 1.8.0 is compatible with NeoForge.
NeoForge will receive dedicated support in the future.
