### ISSUE TITLE
First-person Model API Usage

### ISSUE THREAD

**Issue by mpustovoi** [ZsoltMolnarrr/BetterCombat#329]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric
**Mod version** - 1.8.3
**I am using the latest version available** - Yes

**Describe the bug**
With latest **First-person Model** mod version (**2.3.1-1.20.1 - Fabric**) game crashes after trying to hit a mob with any weapon.
Crash-report and latest.log:
https://gist.github.com/mpustovoi/b7bc2ed04ebfe1b93f3fe725946bf384

**To Reproduce**
1. Install Fabric 1.20.1, Better Combat 1.8.3, First-person Model 2.3.1 (and playerAnimator 1.0.2).
2. Join a world and hit a mob with any weapon.
3. Game crashes.

**Expected behavior**
Expected that the crash wouldn't happen.

**Screenshots or video recordings**
Crash happens instantly after clicking LMB.

**Additional context**
The author of the First-person Model mod replied that the problem isn't in his mod.

**Comment by mpustovoi** [comment]
Better Combat will have to update, it's not using the API but instead calling into internals. For the dev version I re-added the field its trying to get as a workaround against the crash.

_Originally posted by @tr7zw in https://github.com/tr7zw/FirstPersonModel/issues/417#issuecomment-1913224330_

**Comment by mpustovoi** [comment]
Better Combat will have to update, it's not using the API but instead calling into internals. For the dev version I re-added the field its trying to get as a workaround against the crash.

_Originally posted by @tr7zw in https://github.com/tr7zw/FirstPersonModel/issues/417#issuecomment-1913224330_

**Comment by tr7zw** [comment]
The version with workaround is now out (2.3.2). (still needs to be fixed, I'll remove the workaround again at some point)
