### ISSUE TITLE
Lower forge version to make it work with neoforge.... again

### ISSUE THREAD

**Issue by AsheX1** [ZsoltMolnarrr/BetterCombat#330]
minecraft 1.20.1
neoforge again
better combat 1.8.4+1.20.1

in the META-INF folder edit mods.toml
had to change line 49 again from (versionRange="[47.2,)" #mandatory) to (versionRange="[47.1,)" #mandatory)

had to do this again to make it works with neoforge as neoforge is not at verson 47.2. yet last neoforge versoin is 47.1.96

pls just lower the the mods.toml forge version to 47.1 as that makes it work on neoforge

here have the jar that i change the mods.toml in to check for your self
[bettercombat-forge-1.8.4+1.20.1.zip](https://github.com/ZsoltMolnarrr/BetterCombat/files/14078105/bettercombat-forge-1.8.4%2B1.20.1.zip)

**Comment by AsheX1** [comment]
dont close it like last time and saying it was compatible as it was not... just upload the fixed jar or maybe change the line your self and upload that jar

**Comment by ZsoltMolnarrr** [comment]
Better Combat 1.8.0 is compatible with NeoForge.
NeoForge will receive dedicated support in the future.

Forge version requirement is not randomly set to 47.2, it is not possible to lower it without introducing severe bugs.

**Comment by inmourning** [comment]
it's not compatible with NeoForge. NeoForge is registered as version 47.1.99.
