### ISSUE TITLE
Option to hit first target instead of cleaving

### ISSUE THREAD

**Issue by SLinxTheFox** [ZsoltMolnarrr/BetterCombat#336]
The cleaving is kind of super over powered in situations with a lot of mobs. I'd like if it was relegated to just perks or enchantments or something

My idea would be that there would be a swing path and the first enemy hit would be the only enemy hit, as to prevent multiplying your damage a bunch when fighting lots of enemies. 

Any weapons that do have sweeping like the sword I'd like 1: the option to turn it off, and 2: the option to make it just as weak as the sword's base sweeping is

**Comment by ZsoltMolnarrr** [comment]
There is no technical basis to implement something like that.
