### ISSUE TITLE
[1.20.1] Crashing after leaving and rejoining a certain world

### ISSUE THREAD

**Issue by Molioron** [ZsoltMolnarrr/BetterCombat#339]
**Minecraft version** - 1.20.1
**Mod loader** - Forge 47.2.20
**Mod version** - 1.8.4
**I am using the latest version available** - latest as of mc1.20.1

**Describe the bug**
Trying to join a specific world, results in a crash. some other worlds are fine.

**To Reproduce**
Not entirely sure, but:
1. Download Better Combat and Just Leveling
2. maximize all levels in just leveling and enable all abilities
3. leave and then rejoin the world

**Expected behavior**
Joining the world without any crashes.

**Screenshots or video recordings**
crashlog: https://pastebin.com/NpCNdGcD

**Comment by immood** [comment]
I'm having the exact same issue with both mods.

**Comment by ZsoltMolnarrr** [comment]
JustLeveling is causing the crash.
It is trying to modify the code of Better Combat, which is unsafe, and it fails doing so.
Remove JustLeveling.
