### ISSUE TITLE
First Person Attack Animations

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [ZsoltMolnarrr/BetterCombat#34]
They are a look a little odd, because player look pitch is not translated as player's expect it.

**Comment by Cixon** [comment]
i assume this is the bug with the head seeping through each swing in FPV?

![Screenshot (121)](https://user-images.githubusercontent.com/69068153/186289325-d2828dcd-f457-41df-a763-3f294f784af6.png)

**Comment by ZsoltMolnarrr** [comment]
No this screenshot is an incompatibility, most likely caused by a Forge mod.

**Comment by ZsoltMolnarrr** [comment]
There is no technical idea on the horizon, moving to private backlog.
