### ISSUE TITLE
Spanish translation not working

### ISSUE THREAD

**Issue by TheLegendofSaram** [ZsoltMolnarrr/BetterCombat#340]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric 0.15.7
**Mod version** - 1.8.4
**I am using the latest version available** - Yes

**Describe the bug**
The spanish lang file has a problem that prevents it from loading. I already fixed it, that and some weird translation. Here is the lang file Is in the Mexican Spanish variant.
[es_mx.zip](https://github.com/ZsoltMolnarrr/BetterCombat/files/14498254/es_mx.zip)

**To Reproduce**
1. Go to 'Minecraft'
2. Click on 'Language'
3. Scroll down to 'Spanish and make it the default language'

**Expected behavior**
The mod should be translated

**Comment by ZsoltMolnarrr** [comment]
Should be fixed in the next update.
