### ISSUE TITLE
Minecraft crashes due to better combat

### ISSUE THREAD

**Issue by Safenteril1** [ZsoltMolnarrr/BetterCombat#342]
**Minecraft version** - 1.201
**Mod loader** - fabric
**Mod version** - 1.8.1
**I am using the latest version available** - yes

**Describe the bug**
Im cannot loading minecraft, got crash

**To Reproduce**
Im just start minecraft

**Expected behavior**
Minecraft should just load up to the main menu, without any errors.

**Screenshots or video recordings**
https://pastebin.com/Dmcs6VvF

**Comment by ZsoltMolnarrr** [comment]
This doesn't happen in when only Better Combat is installed.
To make this actionable, information is required about which is the other mod that we have the conflict with.

**Comment by Safenteril1** [comment]
> This doesn't happen in when only Better Combat is installed. To make this actionable, information is required about which is the other mod that we have the conflict with.

I already realized why, modrinth doesn't say that  need to download cloth config
