### ISSUE TITLE
Better combat / Salami , Pepperoni Debate

### ISSUE THREAD

**Issue by Staghearted** [ZsoltMolnarrr/BetterCombat#343]
**Minecraft version** - 1.19.2
**Mod loader** - Curseforge
**Mod version** - 1.7.1
**I am using the latest version available** - Yes

**Describe the bug**
Crash occurs whilst loading up Modpack, Better combat reacts to an error which causes a failed load up of the Modpack. 

**To Reproduce**
1. Press launch on Minecraft
2. Idly wait for your 2007 PC that you've torn to pieces and shoved a bunch of current model Tech into like some Hybrid Cyborg PC to load up Minecraft
3. Consider if Pepperoni is better then Salami or not...
4. Minecraft Errror appears. 

**Expected behavior**
Me to be able to access Minecraft, and come to a good decision on this Pepperoni or salam thing.. i mean seriously one tastes way better then the one, but i can't tell WHICH is the better one. 

**Screenshots or video recordings**
![image_2024-03-11_174131515](https://github.com/ZsoltMolnarrr/BetterCombat/assets/163032871/37453cb2-75b5-4c53-9da3-158926aa39cc)

**Additional context**
Yup, Salami is better.

**Comment by Orangejewce92** [comment]
I also get a side event phase error on start up. Usually a restart fixes it. But it's becoming almost every time I launch the mod.

**Comment by ZsoltMolnarrr** [comment]
This looks like an installation problem.
1.19.2 versions are no longer provided updates for.
I recommend using CurseForge launcher to install the mod.

**Comment by Orangejewce92** [comment]
I solely use curseforge

**Comment by ZsoltMolnarrr** [comment]
Also, this unzipping problem is specifically caused by Forge mod loader.
Forge is unstable by its legacy nature, I can not provide help for its internal failures.

I recommend primarily using Fabric, being far superior in terms of compatibility and performance.
