### ISSUE TITLE
offhand item disappears when holding two handed wepon

### ISSUE THREAD

**Issue by CalebPowell09** [ZsoltMolnarrr/BetterCombat#345]
**Minecraft version** - 1.20
**Mod loader** - fabric
**Mod version** - 1.8.4
**I am using the latest version available** - yes

**Describe the bug**
When ever i put something in my offhand when i hold a two handed weapon it deletes the items my off hand

**To Reproduce**
1. Put something in offhand
2. hold two handed weapon

**Expected behavior**
I should keep the item

**Screenshots or video recordings**
<img width="400" alt="image" src="https://github.com/ZsoltMolnarrr/BetterCombat/assets/143885704/3a84a0fd-df0c-4ac1-b00c-74057cb69906">
<img width="354" alt="image" src="https://github.com/ZsoltMolnarrr/BetterCombat/assets/143885704/690cb3c9-e01d-4749-8568-50b5486957a8">

**Comment by ZsoltMolnarrr** [comment]
This is intended behavior.
“Two-Handed” weapon

**Comment by peow** [comment]
are items deleted or dropped on the floor?

**Comment by CalebPowell09** [comment]
> are items deleted or dropped on the floor?

deleted

**Comment by peow** [comment]
mmm, this seems to be a big problem, the mod should either prevent you from using the two-handed weapon or drop the items from your off-hand

**Comment by peow** [comment]
take a look in this issue, is similar to your problem:
https://github.com/ZsoltMolnarrr/BetterCombat/issues/268
