### ISSUE TITLE
Swapping any two-handed weapon from offhand slot to hotbar voids the weapon

### ISSUE THREAD

**Issue by AlisonHuang777** [ZsoltMolnarrr/BetterCombat#348]
**Minecraft version** - 1.20.1
**Mod loader** - NeoForge 47.1.99
**Mod version** - Fabric 1.8.4, using Sinytra Connector 1.0.0-beta.32
**I am using the latest version available** - Kind of

**Describe the bug**
As the title described.

**To Reproduce**
1. Put any two-handed weapon in the offhand slot.
2. Swap the weapon to hotbar. (by pressing F by default)
3. The weapon disappears.

**Expected behavior**
The weapon should not disappear.

**Screenshots or video recordings**

https://github.com/ZsoltMolnarrr/BetterCombat/assets/51637996/0a372968-1c58-4b34-9cc0-880cf0dbbf29

**Additional context**
Playing Prominence II Classic modpack (v2.6.0).

**Comment by ZsoltMolnarrr** [comment]
Use Forge specific version, which has this issue fixed.

**Comment by AlisonHuang777** [comment]
Then can you make this mod compatible with NeoForge? The latest version of this mod (for Forge) requires the Forge version to be at least 47.2.0, but NeoForge does not (yet) reach such version number.

**Comment by ZsoltMolnarrr** [comment]
1.8.0 can be used with NeoForge
![image](https://github.com/ZsoltMolnarrr/BetterCombat/assets/4989469/4cb57261-e9f8-4941-9c36-d796c6e33927)

**Comment by ZsoltMolnarrr** [comment]
Dedicated NeoForge support will be added in the future.

**Comment by AlisonHuang777** [comment]
Thank you!
