### ISSUE TITLE
1.20.4 update please

### ISSUE THREAD

**Issue by Kr0sshair** [ZsoltMolnarrr/BetterCombat#350]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I really wanna play bettercombat with my sister on our 1.20.4 world. Unsuprisingly older versions all crash a little after loading into a world.

**Describe the solution you'd like**
An update.

**Describe alternatives you've considered**
None, theres no mod similar to this one that we like,

**Additional context**
I really wanna play with this mod with my sister.

**Comment by ZsoltMolnarrr** [comment]
Did you consider supporting the project financially before asking for development work?

**Comment by Kr0sshair** [comment]
My card is innactive rn so i cant anyways, but im sure to consider it later
at the point if you decide to update, im not the only one asking. Thanks
for making the mod in the first place tho, great shit

**Comment by Kr0sshair** [comment]
Plus it says nowhere a "feature request" strictly requires a donation
