### ISSUE TITLE
Latest build doesnt work.

### ISSUE THREAD

**Issue by Kr0sshair** [ZsoltMolnarrr/BetterCombat#352]
**Minecraft version** - 1.20.4
**Mod loader** - Fabric
**Mod version** - The one mainly features
**I am using the latest version available** - yeah

**Describe the bug**
I built the thing, fully, got the build folder - libs - bettercombat.jar and bettercombat-sources.jar. None of them do their better combat thing. Just doesnt work :(

**Expected behavior**
to work

**Comment by ZsoltMolnarrr** [comment]
1.20.4 version is still in the works.
