### ISSUE TITLE
Weapon swipe animation

### ISSUE THREAD

**Issue by alturz2** [ZsoltMolnarrr/BetterCombat#358]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

It would be pretty cool to have smething like this (https://fmcpe.com/uploads/posts/2021-11/1636274747_combat.gif) but better for attacking. First and third person, and you can toggle it on and off.

**Comment by ZsoltMolnarrr** [comment]
Already on roadmap. Check out our Discord channel for more details :)

**Comment by alturz2** [comment]
Thanks alot (:

**Comment by alturz2** [comment]
It might be a cool idea to add like spark animations and stuff when hitting armour too
