### ISSUE TITLE
Bettercombat forge and fabric crashes with marium soul like weaponry using sinytra connector

### ISSUE THREAD

**Issue by DeadGator** [ZsoltMolnarrr/BetterCombat#359]
**Minecraft version** - 1.20.1
**Mod loader** - Forge 47.2.20
**Mod version** - 1.8.5
**I am using the latest version available** - Yes

**Describe the bug**
I tried fighting the day and night deities (night prowler and day stalker) from marium soullike weaponry and i used cataclysm armor alongside a claymore from simplyswords, everything went well, mid fight the night prowler attacks by slamming the scythe into the ground and smoke? particles come out and when that happens the game instantly crashes. The crash report indicates that there is a collision/related to better combat in some way. I had to disable better combat to access that world again without it crashing. I didn't use any heavy resource packs or shaders and i have a good pc. So it's unlikely this was caused by my computer

**To Reproduce**
1. Install marium soullike weaponry on forge using sinytra connector, as well as better combat for forge/fabric
2. Summon the deities of night and day (night prowler and day stalker)
3. Fight them until the night prowler does a specific attack, crashing the game

**Additional context**

Here are the crash logs
[message.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/15283192/message.txt) (forge version of better combat)

[message (1).txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/15285496/message.1.txt) (fabric version of better combat)

**Comment by ZsoltMolnarrr** [comment]
"Just Leveling" is performing mixin on Better Combat, meaning it alters the code of Better Combat, leading to a crash.
Mixins towards other mods are completely unsafe, and not supported at all.
