### ISSUE TITLE
Shadow missing in First Person view

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [ZsoltMolnarrr/BetterCombat#36]
Sometimes the shadow of the client player is missing.
Not sure about the details. We need feedback.

**Comment by Dr-WeiAL** [comment]
I had this problem, no shadows when using shaders
I am using 1.18.2 forge-40.1.68 oculus-1.2.5a

BetterCombat is not installed
![image](https://user-images.githubusercontent.com/47446553/189256521-de964f38-99f1-47bf-b933-3b313f31b7a2.png)
BetterCombat is installed
![image](https://user-images.githubusercontent.com/47446553/189256802-60cf2abc-e5bd-4377-b33d-b22157a28642.png)

**Comment by ZsoltMolnarrr** [comment]
Yeah, I understand this is an issue.
However I am unable to fix it :(

**Comment by Dr-WeiAL** [comment]
Well, by the way I noticed that the weapon has a shadow when it is swung

**Comment by AxolotlAccount** [comment]
Same issue happens with Better Combat + Iris
