### ISSUE TITLE
Item disappear

### ISSUE THREAD

**Issue by Antidote977** [ZsoltMolnarrr/BetterCombat#363]
When i use two hander weapon and Press F to put it in left hand, now it`s in my left hand. When i swap weapon type two hander weapon, i press F to swap, my left hand (two hander weapon) now it disappear.
mod name: Variant Tools and Weaponry - More Weapons  (vtaw_mw-forge-1.20.1-1.0.4.jar)
Mod loader: forge
game ver 1.20.1

**Comment by ZsoltMolnarrr** [comment]
Please review the full changelog and install the version that is appropriate for your environment.
https://github.com/ZsoltMolnarrr/BetterCombat/blob/1.20.4/CHANGELOG.md
