### ISSUE TITLE
Weapon slam when falling

### ISSUE THREAD

**Issue by mattmoparkour** [ZsoltMolnarrr/BetterCombat#367]
An interesting feature for this mod would be slamming weapons when attacking whilst falling. The player would have to be a certain amount of blocks in the air whilst falling, and the damage/hit would happen at the bottom. There would be a slam animation where the player lifts the weapon above their head or smth.

**Comment by ZsoltMolnarrr** [comment]
Too high complexity, out of scope in regards original project goals.

> ## Project goal:
> Replicate Minecraft Dungeons combat experience.
> Rework the melee combat system of Minecraft, without adding any content or content specific feature, so other content creators can build on Better Combat, without interfering content.
