### ISSUE TITLE
Issue with first-person animations

### ISSUE THREAD

**Issue by SalamiLidCryptid** [ZsoltMolnarrr/BetterCombat#371]
**Minecraft version** - 1.20.1
**Mod loader** - Forge
**Mod version** - 47.2.30
**I am using the latest version available** - Yes

**Describe the bug**
While using any melee weapon (both modded and not) in first person, I cannot see its animation in first person (so for example the physical sword swinging on the screen). I can see that the weapons I'm swinging are actually being used both by the swing indicator under the crosshair and because when sung at mobs they deal damage.

**To Reproduce**
1. Load into 'any singleplayer world'
2. Take out a melee weapon
3. Use/swing it

**Expected behavior**
Expected the animation of the weapons to occur on screen.

**Screenshots or video recordings**
![Proof of bug](https://github.com/ZsoltMolnarrr/BetterCombat/assets/172081825/9001ee2b-f0aa-4fd1-af31-94b0bb13d1ea)

**Additional context**
This is pretty unusual since I can see my character performing it by checking my own shadow (while shaders are on) and my PaperDoll on the left.

This happens in any single player world (both the one I was playing when this occurred and new blank ones) and even with previous versions of this mod (so both the latest and all the previous versions).

Pretty weird that this is occurring only to me, since I did not find any evidence on Github and Curseforge comments of other people having the same problem, so I believe I may have found an incompatibility with some other mod or I may have screwed something up in some way.

Let me know if you'd like me to share the modlist, a latest.log (even though in the log there's no error relevant to BetterCombat or other animations) or further details.

**Comment by SalamiLidCryptid** [comment]
Hello!
I've done some troubleshooting and noticed that the issue was actually caused by the mods **Woodwalkers** and **crafted-core**.

Looking into it more in detail, it was the mod **Woodwalkers** which was suppressing the animations of Better Combat even when not morphed.

Weirdly enough, I've noticed this happening even while woodwalkers was disabled and only its library was active.

Their versions were: **craftedcore-4.2.3-forge.jar** and **walkers-4.5-forge.jar**.

Thank you for your time and sorry for bothering you even if the issue wasn't caused by your mod. 🧍

**Comment by FineFoul** [comment]
I have the same issue but i dont have neither both of these mods
