### ISSUE TITLE
Not Working With Alex’s Caves

### ISSUE THREAD

**Issue by goofygoobersillybilly** [ZsoltMolnarrr/BetterCombat#372]
**Minecraft version** - 1.20.1
**Mod loader** - forge
**Mod version** - 1.8.5
**I am using the latest version available** - yes

**Describe the bug**
when you mount a rideable mob from alex’s caves there are of the same player one on top of the place where it usually is and another hovering in the air behind the mob.

**To Reproduce**
1. Go to 'the toxic caves menu’
2. Click on 'nuclear bomb, remote detonator, tremorzilla egg and nuclear waste exit the menu place the tremorzilla agg and nuclear bomb right click with the remote detonator then use the glowing green remote detonator tame the tremorzilla using nuclear waste and nuclear bombs ride it and go into 3rd person.

**Expected behavior**
two clones of the player riding the tremorzilla.

**Screenshots or video recordings**
no access to my pc rn so i cant put anything here sorry

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
Are you entirely sure this is caused by Better Combat?
