### ISSUE TITLE
Better Combat & Just Leveling compatibility

### ISSUE THREAD

**Issue by KrokusAstra** [ZsoltMolnarrr/BetterCombat#374]
**Minecraft version** - 1.20.1
**Mod loader** - Forge
**Mod version** - 1.8.5
**I am using the latest version available** - For 1.20.1 yes

**Describe the bug**
Previously everything was working as intended - no crashes. But after some point... game starting to crash when i'm trying to enter my world. Minecraft itself successfully starting, but the problem starts when i try to actually play. Game tries to load me in, loading pass 100% and i expect to enter the world, but it says "saving the world" and crashes. 

When i try to create new save, sometimes i could access the game, but sometimes is not.

"Not enough crashes" gives me it:
https://bytebin.lucko.me/atYrZtG8m4

There is full log of old save (crash):
[latest.log](https://github.com/user-attachments/files/15859018/latest.log)

**Additional context**
As i said, previously all worked as intended. But today crashes don't allow me to play. Idk why it started to crash all of the sudden. Yesterday i played without single crash.

**Comment by ZsoltMolnarrr** [comment]
JustLeveling is causing the crashes as it is trying to modify the code of Better Combat, which is unsafe, and it fails doing so.
Remove JustLeveling.
I cannot do anything to resolve this problem besides adding explicit incompatibility flag.
