### ISSUE TITLE
Incomportable with Industrial Revolution

### ISSUE THREAD

**Issue by TheMurkovich** [ZsoltMolnarrr/BetterCombat#375]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric 0.15.11
**Mod version** - 1.8.3
**I am using the latest version available** - no

**Describe the bug**
Gamer Axe without BetterCombat damages 9hp, with BetterCombat ~1hp

**To Reproduce**
1. Install Industrial Revolution mod
2. Create world
3. Pick Gamer Axe
4. Damage any enitity and check

**Expected behavior**
Gamer Axe damages 1hp instead of 9hp

**Screenshots or video recordings**
Im so far from PC and there is no way to attach a video

**Additional context**
Not Requared

**Comment by ZsoltMolnarrr** [comment]
Better Combat is a low level mod, not depending, or supporting any content mod in particular.
In case there is an incompatibility as such, the mod in question needs to implement their changes in a more conventional/compatible manner.
