### ISSUE TITLE
Crash in third person after respawn

### ISSUE THREAD

**Issue by Krampus69** [ZsoltMolnarrr/BetterCombat#376]
Hello !

**Minecraft version** -  1.20.1
**Mod loader** - Forge 47.3.1
**Mod version** - bettercombat-forge-1.8.5+1.20.1
**I am using the latest version available** - Yes

**Describe the bug**
Game just client crashed after dying with an halberd in my hands on third person.

**Expected behavior**
Respawn without crashing.
 Here is the crash report, it says there might be an issue with just levelling mod, but maybe it's not the issue
[crash-2024-06-24_14.17.52-client.txt](https://github.com/user-attachments/files/15955588/crash-2024-06-24_14.17.52-client.txt)

**Comment by ZsoltMolnarrr** [comment]
JustLeveling is causing the crashes as it is trying to modify the code of Better Combat, which is unsafe, and it fails doing so.
Remove JustLeveling.
I cannot do anything to resolve this problem besides adding explicit incompatibility flag.

**Comment by Krampus69** [comment]
Wait, can I maybe contact the guy from just levelling so he fixes the issue ?

**Comment by ZsoltMolnarrr** [comment]
I definitely cannot fix their invasive attempts.
