### ISSUE TITLE
Incompatibility with Balkon's Weaponmod: Legacy 

### ISSUE THREAD

**Issue by DragonacyCX** [ZsoltMolnarrr/BetterCombat#377]
**Minecraft version** - 1.20.1
**Mod loader** - Forge
**Mod version** - 1.8.5 + 1.20.1
**I am using the latest version available** - yes

**Describe the bug**
When trying to join a world with both mods installed, the game crashes.

**To Reproduce**
1. Add "Better Combat 1.8.5 + 1.20.1" and "Balkon's Weaponmod: Legacy 1.20.1-1.21.0
2. Launch the modded game
3. Try to join a world
4. See error:
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "attributeId" is null

**Expected behavior**
I expected the game to work normally with these two mods

**Screenshots or video recordings**

**Additional context**

**Comment by ThexXTURBOXx** [comment]
I have fixed this myself in #378. However, the fix has not yet been published.
Also @ZsoltMolnarrr: my fix has not yet been ported to other versions of Better Combat - only 1.20.1.
However, it also affects other versions as well. These should receive the same treatment :)

**Comment by ZsoltMolnarrr** [comment]
Fix released as part of BetterCombat 1.8.6

Feel free to reopen if the issue resurfaces.
