### ISSUE TITLE
Adding stances for each weapon

### ISSUE THREAD

**Issue by Gabalus** [ZsoltMolnarrr/BetterCombat#379]
By stances i mean an ability for a player to choose an attacks' array with a keybind. Also I consider generating player attributes that will contain data that describes which stances are unlocked for certain player with certain weapon(Maybe this sub feature doesn't suit the mod's idea). I came up to this idea when i thought about adding different skilltrees in Pufferfish's Skills(For example samurai can unlock so called stances for katana, berserk for axes, etc.)

I would have implemented it myself but I didnt understand how to register player attributes because bettercombat is crosscompatible for different modloaders. So I cant just use forge's DefferedRegistry.

So please consider this feature.

**Comment by ZsoltMolnarrr** [comment]
Hi!

Better Combat does have declared project goals. These have been public in Discord, not here unfortunately.
I just added them: https://github.com/ZsoltMolnarrr/BetterCombat/tree/1.20.1

Unfortunately your suggestions don't align with project goals. (Specifically the first point)
