### ISSUE TITLE
Reach compat with Quality Equipment

### ISSUE THREAD

**Issue by Krampus69** [ZsoltMolnarrr/BetterCombat#380]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
Quality Equipment mod adds new attributes to items such as reach distance for weapons. As it is now, changing the quality of your sword with a +0.5 reach attribute doesn't change the reach distance at all. (The Better Combat mod doesn't take into account Quality Equipment)

**Describe the solution you'd like**
It would be awesome to see Better Combat detect this attribute and change it in the config of the weapon. 

**Describe alternatives you've considered**
Maybe asking the Quality Equipment author to make a compatibility on his side, and add the reach distance attribute in the better combat system by himself ?

**Additional context**
![image](https://github.com/ZsoltMolnarrr/BetterCombat/assets/81943963/014560de-286d-4001-98f3-55082af5e180)
https://www.curseforge.com/minecraft/mc-mods/quality-equipment

Thank you for your awesome work !

**Comment by ZsoltMolnarrr** [comment]
Reach (or any attack range modifying) attributes are inherently impossible to balance.
No wonder Minecraft Dungeons (which serves as our UX reference) doesn’t have such feature.

I am sorry to say, I will not be implementing this myself for sure.
Anyone looking to have this feature just because it sounds cool is free to implement compatibility, since Better Combat provides an API for attack range modification.

**Comment by NerdyPuzzle** [comment]
Please note that this attribute is not added by quality equipment, but by forge. The attribute is forge:entity_reach with its translation key overwritten.

**Comment by ZsoltMolnarrr** [comment]
I do note that, I stand by my statement.

As a developer I did not ask Forge to add any such content, nor did I opt in for that.

Forge does many of its unwanted features and under the hood changes, regardless ofprojects want it or not. Issues like this and the continuous drama surrounding the platform make it inefficient to develop complex things for that platform. 

Hence I recommend using Fabric, where no content is added unless the player installs it.

**Comment by Krampus69** [comment]
Just for the record, I asked the quality equipment dev to make it compatible and he did, so that's all good now 👍
