### ISSUE TITLE
Add a Configuration option to change attack range/hit range for a specific mod/weapon set.

### ISSUE THREAD

**Issue by WolfKann** [ZsoltMolnarrr/BetterCombat#383]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
Attack Distance with weapons being inaccurate (I.E certain mods have distances for weapons that do not match and do not reach as far as I'd like

**Describe the solution you'd like**
a Configureable option to change the over-all attack range of all weapons from a specific mod/nbt prefix "bettercombat:"
"minecraft:" "coolweapons:"

**Describe alternatives you've considered**
 a generalized range option. it doesn't need to be enabled by default but I feel like there's a glaring issue when some people make packs that don't have good range for the weapon, and I end up unfortunately low on weapon options because the weapons that are partnered just don't feel like they reach enough.

**Additional context**
N/A

**Comment by WolfKann** [comment]
and I don't care about the generic "why isn't my range working" FAQ Post because it simply tries to ignore the issue that some packs made by people who are quite talented in almost every regard can still screw up the distance to hit things, and it's dumb to shrug off the various possible issues that this can arise with a simple FAQ copy-paste instead of making a simple option. Let people configure things to how they want, don't lock something down entirely because you just don't want to let people customize something that many people WANT to customize and have had various mods for to do so.

**Comment by ZsoltMolnarrr** [comment]
This issue has multiple contradictions.
1. The FAQ addresses a different subject. Not "why attack range cannot be configured", but instead "why attack range attribute based scaling is not supported".
2. There is no sensible way to add attack range, based on weapon id prefix, this ignores that different kind of weapons have different range, to establish various characteristics. (For example adding +0.5 attack range has completely different effect on Daggers vs Spears)
3. Configuring attack range is already possible, by overriding weapon attributes using datapacks.
