### ISSUE TITLE
[1.20.1] neoforge incompatibilities

### ISSUE THREAD

**Issue by OrangeSniper** [ZsoltMolnarrr/BetterCombat#384]
**Minecraft version** - 1.20.1
**Mod loader** - neoforge 1.20.1-47.1.106
**Mod version** - 1.8.5
**I am using the latest version available** - yes

**Describe the bug**
incompatible with neoforge

**To Reproduce**
1. download the latest neoforge version for 1.20.1
2. download the latest Better Combat
3. launch game

**Expected behavior**
Better Combat to be compatible with the latest neoforge version

**Screenshots or video recordings**
![2024-07-14_12 15 03](https://github.com/user-attachments/assets/127ec283-7f11-4e94-a1cf-3720526003ad)

**Additional context**
[crash-2024-07-14_12.12.48-fml.txt](https://github.com/user-attachments/files/16228059/crash-2024-07-14_12.12.48-fml.txt)

[latest.log](https://github.com/user-attachments/files/16228060/latest.log)

**Comment by ZsoltMolnarrr** [comment]
Better Combat 1.8.0 is compatible with NeoForge.

**Comment by inmourning** [comment]
You can literally just lower version requirement in the newest version in mods.toml and it will work just fine on neoforge, and it'll clear any of the confusion about neoforge. Why support an loader that nobody supports anymore anyway?

**Comment by ZsoltMolnarrr** [comment]
I cannot literally just lower version requirement, due to API differences between the two.

NeoForge support is in the works.

In the mean time, supporting development work is welcome.
There are multiple donation links available.

**Comment by inmourning** [comment]
Yes you can, if you change it from 47.2 in mods.toml to 47.1 on latest neoforge it will launch and work just fine, please give it a try
