### ISSUE TITLE
I hope this mod is compatible with Yes Steve Model and First-person Model

### ISSUE THREAD

**Issue by realomg** [ZsoltMolnarrr/BetterCombat#385]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES
Although you said that mods trying to change player model modification will never be compatible, I still want this feature.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using Yes Steve Model and First-person Model。

**Describe the solution you'd like**
I want the attack animation to work properly when I use the Yes Steve Model and the First-person Model.

**Describe alternatives you've considered**
I tried searching for similar mods online, but couldn't find any results that could solve this problem.

**Additional context**

https://github.com/user-attachments/assets/364ce49a-5de5-42d4-a3a2-83cdf5ccb390

**Comment by ZsoltMolnarrr** [comment]
I have zero room for action here.
Yes Steve Model needs to add support with PlayerAnimator library, or implement its changes in a more compatible manner.
