### ISSUE TITLE
Can I only change the player's attack actions? Can I add these attack actions to a custom entity

### ISSUE THREAD

**Issue by 970100646** [ZsoltMolnarrr/BetterCombat#386]
Can I only change the player's attack actions? Can I add these attack actions to a custom entity

**Comment by ZsoltMolnarrr** [comment]
It is not possible to attach attack animations to entity.
The depended library is named PlayerAnimator for a good reason.

**Comment by ZsoltMolnarrr** [comment]
There is no universal method for attaching my animations to entities, because they can have any number of bodyparts and arms, legs.
Mob Entities in general are meant to use GeckoLib animations.

**Comment by 970100646** [comment]
I found a mod, better mod combat, that allows other entities to have BC attack animations, but unfortunately only the Forge version is available
