### ISSUE TITLE
Weapons not rendering while attacking

### ISSUE THREAD

**Issue by VIK044-prog** [ZsoltMolnarrr/BetterCombat#387]
**Minecraft version** - 1.18.2
**Mod loader** - forge 40.2.4
**Mod version** - 1.6.2+1.18.2
**I am using the latest version available** - for 1.18.2 

**Describe the bug**
While attacking any weapon (compatible or not) doesn't render while the attack animation happens
in 1st person mode
**To Reproduce**
Open the attached modpack file for CurseForge which is a modified version of The Isle of Berk modpack
Create a world, choose any weapon and try attacking

https://github.com/user-attachments/assets/51c778be-2c7c-42fb-bc4a-24a39d1b1bbf
[Isle of Berk - Modified.zip](https://github.com/user-attachments/files/16279027/Isle.of.Berk.-.Modified.zip)

**Comment by ZsoltMolnarrr** [comment]
1.18.2 versions are no longer being developed.
I recommend troubleshooting your modpack by disabling some mods to find which one causes the incompatibility.
