### ISSUE TITLE
No animations on servers

### ISSUE THREAD

**Issue by bongjam** [ZsoltMolnarrr/BetterCombat#388]
**Minecraft version** - 1.20.4
**Mod loader** - fabric
**Mod version** - 1.8.6
**I am using the latest version available** - yes

**Describe the bug*
The animations work perfectly fine on single player but doesnt work at all when I am on servers

**To Reproduce**
1. Go to server

**Expected behavior**
I expected it to have animations

**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment]
![image](https://github.com/user-attachments/assets/a248124c-62ff-46a6-a9ad-cb9b26b15c29)
