### ISSUE TITLE
Interupt attack to block

### ISSUE THREAD

**Issue by MangoLassie142** [ZsoltMolnarrr/BetterCombat#390]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
As fun as BC is, it's made objectively worse than vanilla combat by the fact that you're stuck in the attack animation for so much longer, and therefor cannot block anywhere near as reactively.

**Describe the solution you'd like**
Ability to interupt the attack animation with right click to block instantly

**Describe alternatives you've considered**
adding some kind of stun to the attacks? but i think blocking is better

**Comment by ZsoltMolnarrr** [comment]
![image](https://github.com/user-attachments/assets/ca928d58-0a0e-4e09-b25c-8f44f7a443fd)
