### ISSUE TITLE
Crash "attributeID is Null"

### ISSUE THREAD

**Issue by EletronicPanda** [ZsoltMolnarrr/BetterCombat#394]
**Minecraft version** - 1.20.1
**Mod loader** - Forge
**Mod version** - 1.8.5
**I am using the latest version available** - Yes

**Describe the bug**
If I install any other mod into my modpack the game crashes with the error: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "attributeId" is null

**To Reproduce**
1. Install Better Combat
2. Install any other mod in modpack

**Expected behavior**
Should join my world without crash.

Log: 
[latest.log](https://github.com/user-attachments/files/16434332/latest.log)

Crasg Log:
[crash-2024-07-30_20.30.14-server.txt](https://github.com/user-attachments/files/16434336/crash-2024-07-30_20.30.14-server.txt)

**Comment by ThexXTURBOXx** [comment]
I have fixed this myself in #378. However, the fix has not yet been published.

**Comment by ZsoltMolnarrr** [comment]
Fix released as part of BetterCombat 1.8.6

Feel free to reopen if the issue resurfaces.
