### ISSUE TITLE
Better combat encountered an issue during server side-setup.

### ISSUE THREAD

**Issue by DeadGator** [ZsoltMolnarrr/BetterCombat#395]
I installed Cisco's Medieval RPG (ULTIMATE) and added a few mods for myself and i randomly encounter this error. It doesn't happen all the time, sometimes it's combat roll, sometimes its better combat, sometimes its both saying they encountered an issue during server side setup

crash: https://pastebin.com/FKhNrybv

**Comment by ZsoltMolnarrr** [comment]
This is an issue of Forge modloader itself.
The problem is non actionable for me.

I recommed using Fabric.
