### ISSUE TITLE
No Tree Punching Flint knife won't break grass

### ISSUE THREAD

**Issue by TheSexyYeti** [ZsoltMolnarrr/BetterCombat#396]
This really isn't a bug. But I'm working on a mod pack. And the mechanic where Better combat mod makes weapons swing through grass is preventing the flint knife from the no tree punching mod is preventing the knife from breaking grass to get plant fiber. I've been sitting here trying to figure out how to adjust the configs so the flint knife can break grass. But I'm still not seeing any changes. I would have figured adding the mod name to the blacklist for the swing through grass feature. But it's still not working. Do I have to seperate each mod name with a comma. Or just add it in there?.

**Comment by makumaku1974** [comment]
I've done this before but havent reported it and Flint Knife is considered a weapon which is kinda frustrating.

**Comment by ZsoltMolnarrr** [comment]
Configure your modpack, by using one of the blacklist features.
(such as swing thru grass blacklist)
