### ISSUE TITLE
Pickaxe and weapons swinging rapidly like 100 times when i hit a block

### ISSUE THREAD

**Issue by paradox3214** [ZsoltMolnarrr/BetterCombat#399]
**Minecraft version** - ? 1.12.2
**Mod loader** - ? rebirth of the night 
**Mod version** - ? 3.2.2
**I am using the latest version available** - ? yes

**Describe the bug**
So after updating my mod from version 3.2.1 to 3.2.2 my pickaxe and weapons are swinging rapidly and tons of times when i hit a block, this affects all tools except for axes shovels and hoes  ive tried deleting the mod folder curseforge minecraft reinstalling everything and i cant figure out what exactly the issue is nobody elses advice has fixed it 
**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**
![image](https://github.com/user-attachments/assets/253eba21-8989-43d0-82c8-d322ac426984)
I couldnt record but this might help?

**Additional context**

**Comment by paradox3214** [comment]
its normal when i swing them in the air or against mobs but when they hit blocks they go crazy and they go crazier the closer to me i hit 
![image](https://github.com/user-attachments/assets/848376d0-4e46-4e63-afa4-60c55e7edf38)

**Comment by ZsoltMolnarrr** [comment]
Minecraft 1.12.2 is not supprted at all.

I am not sure you are aat the right place.

**Comment by paradox3214** [comment]
> Minecraft 1.12.2 is not supprted at all.
> 
> I am not sure you are aat the right place.

thats weird it worked on 3.2.1 though?
