### ISSUE TITLE
Unique jumping/landing animations for weapons

### ISSUE THREAD

**Issue by polykatt** [ZsoltMolnarrr/BetterCombat#403]
So rather than doing the regular swinging animations, jump attacks can have animations more suited to the action. Like landing slamming down with sword -  might make hitting criticals with this mod easier as well. Maybe it is something similar to the 1.21 mace where the hit animation stays for the duration of the fall (but wouldn't have the same damage increase based off height mechanic that the mace has).

**Comment by ZsoltMolnarrr** [comment]
Sorry this idea doesnt fit project goals.

![image](https://github.com/user-attachments/assets/0f8c7f3c-ae7e-48f0-9ba9-a93f8e0290c0)
