### ISSUE TITLE
Subsquent Hits (holding the mouse button) do 1 dmg only (server)

### ISSUE THREAD

**Issue by MinoreMin** [ZsoltMolnarrr/BetterCombat#405]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric 0.15.11
**Mod version** - 1.8.6
**I am using the latest version available** - Yes

**Describe the bug**
I'm using better combat in a self hosted server with a modpack. I don't know if it's because of the tps and client-server update, but subsequent hits don't do the proper damage, I have to click, wait, and click again. If it's a server issue, I would like to know how to fix it or if it's unfixable

**To Reproduce**
1. Play in a server and try to attack holding the mouse button, only the first hit does the expected damage, the other ones do like 1, maybe 2 damage in mobs, as if I were spamming without the mod installed

**Expected behavior**
All hits doing the weapon damage

**Comment by ZsoltMolnarrr** [comment]
Better Combat is working as expected on all servers so far.

Your issue is most likely some incompatibility issue.
