### ISSUE TITLE
Hi i would like to request animation compatibility with the Fresh Player Animations resourcepack

### ISSUE THREAD

**Issue by BlackLightning-S** [ZsoltMolnarrr/BetterCombat#406]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
No.

Request
The fresh player animations resourcepack adds some really nice animations to the player and better combats combat animations are not usable with it i really would like some integration with this resourcepack for fancier looks in minecraft because this mod is amazing.

**Solution Suggestions**
I have no idea how could this be done so i cant suggest a solution.

**Additional context**
https://www.curseforge.com/minecraft/texture-packs/fresh-player-animations
This is the link to their page on curse forge.

**Comment by ZsoltMolnarrr** [comment]
I am merely a user of PlayerAnimator library, I have no way to make this possible.

I _guess_ this is an incompatibility between the mentioned resourcepack and [PlayerAnimator](https://github.com/KosmX/minecraftPlayerAnimator) lib.

**Comment by BlackLightning-S** [comment]
> I am merely a user of PlayerAnimator library, I have no way to make this possible.
> 
> I _guess_ this is an incompatibility between the mentioned resourcepack and [PlayerAnimator](https://github.com/KosmX/minecraftPlayerAnimator) lib.

Thank you for your fast reply. Have a nice day.
