### ISSUE TITLE
Disable Bettercombat attack in some conditions

### ISSUE THREAD

**Issue by 3247332139** [ZsoltMolnarrr/BetterCombat#408]
The better combat attack sometimes can't hit targets at some special angle.
Could you add a config to disable the better combat attack in some conditions like sneaking.
I achieve it in a fork version and i want to add it in offical version.

**Comment by ZsoltMolnarrr** [comment]
Does not fit project scope.

"Replicate Minecraft Dungeons combat experience, by reworking the melee combat system"

![Screenshot 2024-09-03 at 12 13 04](https://github.com/user-attachments/assets/03e50e23-d596-46a3-b4a6-b8b3055f788b)
