### ISSUE TITLE
[1.21.x][Neoforge] Player head clips through screen when attack animation happens

### ISSUE THREAD

**Issue by ffuentesm** [ZsoltMolnarrr/BetterCombat#409]
**Minecraft version** - 1.21.1
**Mod loader** - Neoforge
**Mod version** - 2.0.0
**I am using the latest version available** - yes

**Describe the bug**
When attacking, the player model clips through the camera, Head included.

**To Reproduce**
1. Attack with a weapon.

**Expected behavior**
The head should have been invisible during attack animation and only the arms should be seen moving. 

**Screenshots or video recordings**
https://github.com/user-attachments/assets/ab971f4e-9c3d-4b5b-b6bc-5f576ec4da40

**Comment by ZsoltMolnarrr** [comment]
Tested on fresh installation, without any other mods the issue does not occur.

The problem is typically caused by another mod, that fails to manage render states correctly.

In this case tho, the most likely cause is Iron's Spells, that needs to update to the newly released PlayerAnimator.

**Comment by ffuentesm** [comment]
Not Iron's Spells. Nor Ars nouveau, or Occultism. 

Apparently, the problem is with Twilight Forest.

**Comment by ffuentesm** [comment]
Also, something that I notice, even without Twilight Forest Installed is that in the 3rd attack animation, the player model tilts fully forward with the legs perpendicular to the chest. Instead of keeping them grounded. 
![image](https://github.com/user-attachments/assets/26569e38-7c57-4746-a149-cfbda9ffcd14)
![image](https://github.com/user-attachments/assets/1cc0c643-7835-4be4-aa1d-8da8f823c482)
Like, only the arms and head are dynamically animated, but the legs are frozen up straight.
