### ISSUE TITLE
Better Combat attack_animations folder now named player_animations

### ISSUE THREAD

**Issue by milkev** [ZsoltMolnarrr/BetterCombat#410]
**Minecraft version** - 1.21.1
**Mod loader** - neoforge 21.1.34
**Mod version** - 1.2.9
**I am using the latest version available** - as far as i know

**Describe the bug**
Better Combat changed the animation file name from `attack_animations` to `player_animations`, resulting in animations not working by default. [changelog of bettercombat](https://modrinth.com/mod/better-combat/version/2.0.0+1.21.1-fabric#:~:text=BREAKING!%20Asset%20directory%20for%20animations%20have%20been%20renamed%20from%20attack_animations%20to%20player_animations)

**To Reproduce**
1. Play game with the 1.21 release of better combat (just released)

**Expected behavior**
Attack animations working.

**Additional context**
Editting the .jar with winrar, i was able to fix the attack animations simply by renaming the folder to `player_animations`

**Comment by ZsoltMolnarrr** [comment]
There is no issue here.

It was an announced braking change.

Everything works as expected.

**Comment by milkev** [comment]
i posted to the wrong github apologies, meant to post to Basic Weapons

**Comment by ZsoltMolnarrr** [comment]
No problem :)
