### ISSUE TITLE
Critical Attacks

### ISSUE THREAD

**Issue by GhostOfAbaddon** [ZsoltMolnarrr/BetterCombat#415]
what is the function/replacement for crits? ive noticed that jump attacks don't do them which means axes are far less effective in terms of combat

**Comment by ZsoltMolnarrr** [comment]
Better Combat FAQ

**How does critical striking work?**
Same as Vanilla. Just consider the upswing of your weapon, so just jump a little later.
The timing of jumps is a little different, but just keep practicing. :slight_smile:
