### ISSUE TITLE
Damage and attack speed attributes separately for one-handed and two-handed weapons 

### ISSUE THREAD

**Issue by jaimarl** [ZsoltMolnarrr/BetterCombat#417]
It would be nice to add attributes that increase damage and attack speed separately for one-handed and two-handed weapons. This should not be difficult to implement, but it would help a lot when creating RPG modpacks.

**Comment by ZsoltMolnarrr** [comment]
Better Combat doesn't touch any of the vanilla attributes on weapons. It would cause a lot of conflicts if it did.

Better Combat assigns behaviours to weapons, nothing else.

To modify the damage and speed attributes of weapons, either use the built in configuration method of mod provided items, if there is no such config you can use a generic tool such as: https://www.curseforge.com/minecraft/mc-mods/cia
