### ISSUE TITLE
Compatibility with camera mods

### ISSUE THREAD

**Issue by RavensVanity** [ZsoltMolnarrr/BetterCombat#419]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I was trying to make an immersive modpack for minecraft and your mod is on the must have list! However when I use a third person renderer it displays both the third person animation and the first person animation from your mod at the same time creating a sort of duplicate/after-image

**Describe the solution you'd like**
A good solution to avoid even having to keep compatibility between other mods would be an option to hide the first person animations in the mod config/mod menu!

**Describe alternatives you've considered**
An alternative would be to check compatibility for other mods and try to fix it individually. That said the previous option seems a lot simpler.

**Additional context**
![bug](https://github.com/user-attachments/assets/3e4e687c-a3b9-4c9c-baa5-8809a63aec7b)

**Comment by ZsoltMolnarrr** [comment]
Released as part of 2.0.4
