### ISSUE TITLE
Mine with Weapon WHITELIST

### ISSUE THREAD

**Issue by ghotiPhoti** [ZsoltMolnarrr/BetterCombat#420]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I want to disable Mine with Weapons in my configuration, so I can swing weapons at the ground without attempting to mine it, but this toggle renders Axes completely unusable as tools. If I were to use the blacklist instead, I would have to put every single weapon that isn't also a tool on the blacklist. While I'm unfamiliar with the way the tags work specifically, I imagine it would be a massive pain for me to go through and find _every single weapon in my modpack that isn't an axe_ just for this minor quality of life tweak.

**Describe the solution you'd like**
A dedicated `"mineWithWeaponWhitelist"` tag would be the ideal solution to this. It would massively simplify the process of allowing certain weapons to be used as tools (axes), without the need to create a comprehensive list of weapons.

**Describe alternatives you've considered**
If I were to use the blacklist to render axes usable as tools instead, I would have to put every single weapon that isn't an axe on the blacklist.
Maybe Attack Instead of Mining would be what I'm looking for, but I'm unsure exactly how it works, or if players would trigger it while their relation tag is set to "HOSTILE."

**Additional context**
I was testing PVP with this mod with someone while playing as an origin that's 22cm tall, and he was constantly trying to dig the ground with his weapon instead of swinging at me. I found the issue with axes shortly afterwards, and only recently found my solution to the tiny hitbox not being hit by swings: the `"player_relations"` tag.

**Comment by ZsoltMolnarrr** [comment]
Mine with weapons blacklist is a regex. It is possible to put inverted values in there.

`(?!.*axe).*`

**Comment by ghotiPhoti** [comment]
i tried pasting this exact string into the blacklist and it's including axes in the blacklist anyway. thanks for the info anyways!
