### ISSUE TITLE
Config option for first-person arm position

### ISSUE THREAD

**Issue by java-jambalaya** [ZsoltMolnarrr/BetterCombat#422]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
When playing in first-person with the "Show arms in first person" option on (and "Show inactive hand in first person" off), the arm being animated to move the weapon often moves far away from the camera, so far that you can see the arm dislocate.

**Describe the solution you'd like**
My solution to this would be an additional config option, and I have thought of three ideas for what this could be:
- A value which is used to scale the distance the weapon/arm is displayed from the player when in first-person.
- A value which is a specific offset for which the weapon/arm in first-person is displayed by.
- A boolean for if the arm is allowed to visually become dislocated in first-person view (this would probably be quite complicated to detect).

**Describe alternatives you've considered**
I have considered and explored editing the animations themselves, however doing so results in the third-person animation becoming the issue, such as the arm being too far behind the torso it should be attached to.

**Additional context**
N/A

**Comment by ZsoltMolnarrr** [comment]
This is just not possible.
