### ISSUE TITLE
First person animations rendering on top of player model

### ISSUE THREAD

**Issue by RavensVanity** [ZsoltMolnarrr/BetterCombat#423]
**Minecraft version** - 1.21.1
**Mod loader** - fabric
**Mod version** - 2.0.3
**I am using the latest version available** - yes

**Describe the bug**
Better Combat plays first person animations on top of third person model

**To Reproduce**
1.Have any mod that renders player model in first person.
2.Attack with any weapon, first person animations plays on top despite third person model being rendered.

**Expected behavior**
first person animations not playing the same time player model is rendered.

**Screenshots or video recordings**
![bug](https://github.com/user-attachments/assets/48f2b8e3-c7b5-4c46-88d1-8ef7d8fc6300)

**Additional context**
I'm creating a modpack focused on making the game as immersive as possible and to do that rendering the player model in first person is a must. While everything works fine (vanilla first person hands and animations aren't rendered), the better combat first person animations keep rendering on top of the player model. I believe it's a simple fix since the "display hand animations" option exists, just adding an option to not render first person animations at all would be a permanent fix for any kind of use scenario of this sort.

**Comment by ZsoltMolnarrr** [comment]
This is most likely a conflict with some custom first person render mod. Which one is it?

**Comment by ZsoltMolnarrr** [comment]
Released as part of 2.0.4
