### ISSUE TITLE
Main hand and offhand modifier (for dual wielding) dont add up correctly

### ISSUE THREAD

**Issue by Blazier1** [ZsoltMolnarrr/BetterCombat#424]
**Minecraft version** - 1.20.1
**Mod loader** - fabric
**Mod version** -  unsure part of a pack
**I am using the latest version available** - 
Don't think so I'm playing Prominence II.

**Describe the bug**
weapon attributes don't add up when holding a weapon in both ha ds

**To Reproduce**
1. Go to 'inventory'
2. Click and drag weapon to 'equipt weapon in offhand'
3. Put main weapon on bar
4. Check zenith attributes window.

**Expected behavior**
Luck in this case should be 3+2+1
Weapon in main hand weapon in offhand + necklace.

**Screenshots or video recordings**
![375630086-20a4f7eb-8b12-407b-a1a7-1aaf29149e2e](https://github.com/user-attachments/assets/9e897b94-8456-461f-a9dc-333d841ccd6a)
![375630084-869fa155-434c-4bda-8f96-70bb64758aa6](https://github.com/user-attachments/assets/33b6884a-4c3d-4def-8974-2df5837eb178)
![375630080-7a2751e5-efa0-4259-bdcf-8d2df1fa0ea8](https://github.com/user-attachments/assets/4efafe38-37a9-4716-80ba-b81f60ae2d20)

**Comment by Blazier1** [comment]
I put this into the Zenith page and they told me to put it here becuase it wasn't in their Side

**Comment by ZsoltMolnarrr** [comment]
The attack damage calculation you see here is done by Vanilla Minecraft. Maybe Zenith changes it somehow.
Better Combat does not affect this use case.
