### ISSUE TITLE
Shooting Crossbow at a mob crashes game

### ISSUE THREAD

**Issue by ErmGhostDawg** [ZsoltMolnarrr/BetterCombat#427]
**Minecraft version** - 1.20.1
**Mod loader** - Modrinth
**Mod version** - 1.8.6 + 1.8.0
**I am using the latest version available** - Yes

**Describe the bug**
 When the arrow impacts with the mob, the game crashes to desktop.

**To Reproduce**
1. load crossbow with an arrow
2. Shoot any mob
3. hard crash

**Expected behavior**
I expected the crossbow to not crash my game.

**Crash Log**
I will include the crash log here:
[crash-2024-10-29_19.20.31-server.txt](https://github.com/user-attachments/files/17564193/crash-2024-10-29_19.20.31-server.txt)

**Additional context**
I have been making a mod pack, and have had better combat on it for a while now, and up until this point I have not used a crossbow after tweaking the pack for multiplayer. Still working on the modpack, and crossbows worked before larger edits to the pack. If anything I am asking for help identifying conflicts causing the issue or if this is an issue with the mod itself. I am not privy with crash log reading, and better combat was the only notable thing I could take away from the crash log.

**Comment by ZsoltMolnarrr** [comment]
This is an integration issue by a third party mod, with the namespace of "hybridlabs.twm"
