### ISSUE TITLE
Attack animations not playing

### ISSUE THREAD

**Issue by UnderPixel1475** [ZsoltMolnarrr/BetterCombat#428]
So the title is pretty straightforward...

The attack animations are not playing. Whenever I swing a sword or even a axe for that matter, my character's model doesn't move nor anything really happens. 

It gets even weirder on first-person, as the item animation plays however the camera breaks and goes inside the model's head. 

I can still damage mobs, but it's pretty weird to not see my character do anything whenever I use a weapon, and the first-person camera glitch is particularly annoying even if it is short-lived,

I am on 1.20.1, using my own custom modpack with Forge 47.3.0.

I will be leaving below the mods I am using alongside with the debug.log gist.

[modlist.txt](https://github.com/user-attachments/files/17605283/modlist.txt)

https://gist.github.com/UnderPixel1475/fa41e6264be6785fedb80d4c5832a4bb

**Comment by ZsoltMolnarrr** [comment]
This is most likely an installation issue.
The mod definitely works on its own.
I recommend installing mods 1 by 1, until you find which one is causing the render conflict in question.
