### ISSUE TITLE
Compatibility Custom Npcs

### ISSUE THREAD

**Issue by Adventurers-Company** [ZsoltMolnarrr/BetterCombat#429]
I read the project README, checked client-side and server-side configurations, and confirmed that no such feature exists.

Is your feature request related to a problem? Please describe.
Currently, NPCs from the Custom NPCs mod cannot utilize the weapons or animations provided by Better Combat. This limits the immersion and combat dynamics when integrating both mods, as NPCs appear static or lack the combat style provided by Better Combat.

Describe the solution you'd like
I would like Better Combat to add compatibility with the Custom NPCs mod so that NPCs can use the weapon animations and combat mechanics from Better Combat, just like players do. This would greatly enhance the realism and functionality of NPC combat interactions.

Describe alternatives you've considered
Attempted scripting in Custom NPCs to mimic the animations, but the results were limited and did not achieve the same fluidity as Better Combat's native animations.
Explored other mods, but none provide the same level of weapon animation customization as Better Combat.
Additional context
This feature would allow for seamless integration between the two mods, enabling NPCs to feel more dynamic and engaging in combat scenarios. Below is an example use case:

A Custom NPC using a sword would swing it using the same animations as a player under Better Combat, creating a more synchronized experience.
Thank you for considering this request!

**Comment by ZsoltMolnarrr** [comment]
I am sorry to tell you, that PlayerAnimator library doesn't allow animating any entity.
Only **players** in particular.
In case CustomNPCs is using faked PlayerEntities the feature you desire still might be possible. However this needs to be implemented specifically by them, as due to efficiency reasons, Better Combat does implement many of its features as part of the Minecraft client itself.
