### ISSUE TITLE
Network configuration task not support: bettercombat:confg

### ISSUE THREAD

**Issue by daveotic** [ZsoltMolnarrr/BetterCombat#430]
**Minecraft version** - 1.21.1
**Mod loader** - fabric
**Mod version** - 
**I am using the latest version available** - 2.0.3

**Describe the bug**
I have better combat installed on my Minecraft server for end users who want to see the animation on the client side, but the server also has users who just use vanilla. Before Minecraft version 1.20.1 there wasn't an issue with having better combat 1.8.6 with players who play on vanilla, however, now they get the error "Network configuration task not support: bettercombat:confg" when connecting to the server. I tried having a server with just the mod and its dependencies on 1.21.1 and still faced the same issue.

**To Reproduce**
1. Go to a server running 1.21.1 Better combat mod on the server while running vanilla
2. See the error "Network configuration task not support: bettercombat:confg"

**Expected behavior**
Allowing the mod to be on the server side, but players can either play on fabric with the mod or play vanilla Minecraft and connect to the server with no network configuration task error. This will mirror how the mod worked back in version 1.8.6 on Minecraft 1.20.1.

**Screenshots or video recordings**
![image](https://github.com/user-attachments/assets/eb8ebad7-3aec-40e1-940b-c802e348481a)

**Additional context**
This mod is a really good flexible mod for those who want to have a vanilla-plus feel to their game while also still being able to play with other users who want to stay on vanilla Minecraft. Thank!

**Comment by ZsoltMolnarrr** [comment]
This is not how Fabric mods work.
Players cannot have mods in an optional manner, especially this one, that modifies many of the in-game attack and item holding mechanics.
Better Combat **requires** server-side and client-side installation, in a synchronised way.
This is explicitly stated on all download pages.
