### ISSUE TITLE
Compatible with movement animation mods

### ISSUE THREAD

**Issue by Dewinski** [ZsoltMolnarrr/BetterCombat#431]
Greetings!
I really like your mod, but I would like to combine it with some good character animation mod (for example Improved Animations)
That would be very cool! And it helped me a lot in creating the perfect mod assembly...
I hope I'm not the only one who needs this

**Comment by ZsoltMolnarrr** [comment]
Hello!
Unfortunately this is non actionable for me, as Better Combat is merely a user of the PlayerAnimator library.
The compatibility you are looking for should be established between the desired mod and PlayerAnimator.
