### ISSUE TITLE
1.21.1 & playerAnimator crash

### ISSUE THREAD

**Issue by SpicyDandelion** [ZsoltMolnarrr/BetterCombat#434]
**Minecraft version** - 1.21.1
**Mod loader** - fabric
**Mod version** - 1.21.1
**I am using the latest version available** - yes

**Describe the bug**
I'm confused on how this is supposed to work? (It doesn't for me) I'm using 1.21.1 of MC. There's a file for 1.21.1 for BetterCombat. However, it requires playerAnimator, which isn't updated for 1.21.1 yet. The latest file for playerAnimator is 1.21, which just tells me it's the wrong version. So when I load the game just crashes. I play on curseforges app, so playerAnimator won't even pop up, or let me install it for my version.

**To Reproduce**
1. Go to~ curseforge & Download 1.21.1 fabric minecraft. Open your newly created modpack. 
2. Click on~ Add more content. Search BetterCombat and add to modpack. 
                    Add more content. Search playerAnimator. No results. 
3. Go to~ Curseforge website.
4. Click on~ Minecraft>Browse All>Mods>Search Bar>Search "playerAnimator">click files>Filter by>1.21
Since there are no 1.21.1 files, I know that sometimes earlier versions will work. So I added the 1.21 file to my mods in attempt to make this mod work. crashes
7. See error

**Expected behavior**
fabric will give you the error popup telling you to install a newer version of playeranimator as the BetterCombat mod vrs 1.21.1, is not compatible with 1.21 playerAnimator

**Comment by ZsoltMolnarrr** [comment]
Use the recommended method for installing mods which is CurseForge desktop app.
Just click on install Better Combat, and it automatically resolves the correct version of PlayerAnimator for you.
