### ISSUE TITLE
[1.21.3][Fabric][Modrinth] Better Combat crashes Minecraft when loading up the game

### ISSUE THREAD

**Issue by ScratchyNuts** [ZsoltMolnarrr/BetterCombat#435]
When I tried to use this mod in 1.21.3, the game would crash before the popup window for the game showed up. Since I am using BetterAnimations, NotEnoughAnimations, and First-person Model, I thought it was a compatibility issue, even though they all work together, so I put it in a different profile by itself with its dependencies and still got the same result

**Comment by ZsoltMolnarrr** [comment]
The new game version is not supported yet.
