### ISSUE TITLE
Armor stand in sweeping attack that doesn't target them doesn't get knockback unlike vanilla. 

### ISSUE THREAD

**Issue by cylian914** [ZsoltMolnarrr/BetterCombat#437]
**Minecraft version** - 1.20.1
**Mod loader** - forge
**Mod version** - 1.8.6

**Describe the bug**
Armor stand in sweeping attack that doesn't target them doesn't get knock back unlike vanilla. 

**To Reproduce**
1. Place 2  armor stand
2. Attack on of the armor stand
3. The armor  stand that wasn't on the cross didn't get knockback

**Expected behavior**
The armor  stand that wasn't on the cross should get knockback like in vanilla

**Screenshots or video recordings**
Vanilla:
https://github.com/user-attachments/assets/6f251a57-59f1-4775-a057-5e205d5e4469
With better combat:
https://github.com/user-attachments/assets/dd968a95-4ccd-4c82-9526-024e3af357e8

**Additional context**
This break every hit detection in farms, making a lot of farm useless.

**Comment by ZsoltMolnarrr** [comment]
Better Combat was specifically designed and made for adventure gameplays, not farms.

But you can fix this problem by adding a relation entry, targeting the Armor Stand type entities, in `config/bettercombat/server.json5`.

![Screenshot 2024-12-10 at 22 18 10](https://github.com/user-attachments/assets/77a7f8f2-d71f-4ee3-9808-ae95e8f7a6ea)

**Comment by cylian914** [comment]
By putting them in neutral they are no longer affected by the sweeping, so not solving the issue of them not getting knock back...
