### ISSUE TITLE
Add a toggle for new combat mechanics. 

### ISSUE THREAD

**Issue by DaimeneX** [ZsoltMolnarrr/BetterCombat#44]
Something akin to what Epic Fight mod does. The new features shouldn't activate unless you switch into the new combat. 
Maybe add a new idle for it to make it visually apparent both in first and third person? Or a GUI message saying that combat has been engaged.

The only real reason why I'm suggesting this is because whenever I try to chop a tree with this mod installed I keep accidentally swinging the axe around like I'm trying to angrily chop the tree down whenever a block finishes mining and there's nothing to mine behind it.
Edit: As you can imagine it's a bit jarring since it interrupts mining and the only way to stop this from happening is to have auto swing disabled, but that's not ideal since I like having that on, it makes combat more fluid.

**Comment by ZsoltMolnarrr** [comment]
Suggested by many others.
I want to avoid adding such a toggle as long as possible.
The new **harvest lock** feature in v1.0.11 should fix mining.
Feel free to reopen the issue if you still dislike the behaviour
