### ISSUE TITLE
It is possible to add range preset from 1.20.1 to 1.19.2?

### ISSUE THREAD

**Issue by squarzyy** [ZsoltMolnarrr/BetterCombat#441]
It is possible to add new Better Combat presets from 1.20.1 to 1.19.2 manually through Datapack? I want to add a heavy crossbow preset which was first introduced in Better Combat 1.20.1- 1.8.0 for my crossbow in 1.19.2 since 1.19.2 doesn't have it. I've tried to download the raw preset and put it in the better combat attributes from my datapack and also add the attribute file for the crossbow but it doesn't work

**Comment by ZsoltMolnarrr** [comment]
There is no development capacity to backport features.
