### ISSUE TITLE
Disabling Better Combat for individual players

### ISSUE THREAD

**Issue by ItsAMatterOfTime** [ZsoltMolnarrr/BetterCombat#442]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES/NO
YES
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to code a datapack/mod which disables Better Combat for individual people
**Describe the solution you'd like**
An unobtainable effect (such as bettercombat:disable_improved_combat) which when active, prevents the combat changes (such as holding left click to attack, attack speed scaling invincibility frames, etc), so datapack/mod developers can add ways for individual players to be incapable of utilizing the mod.
**Describe alternatives you've considered**
- A command to disable the combat. Ex: /bettercombat disable @s
**Additional context**
Better Combat is nice as a general mod, but gets very annoying if its features do something unwanted.

**Comment by ZsoltMolnarrr** [comment]
Better Combat discord FAQ:

> **Can you add a Battle Mode toggle?**
> Toggling on/off the new attack system would be really bad, since players would be able to choose between instant long range hit with swords and delayed short range attacks, granting an easy way to cheat/cheese any fighting scenario.
> Battle mode like toggle will not be added.

**Comment by ItsAMatterOfTime** [comment]
To clarify, this is an unobtainable effect/toggle that players can not use/obtain. The idea is for datapack developers to be able to disable the special combat, for multiple purposes, such as cutscenes, special variations of fighting, and general utility.

To give the best example, I develop Origins (from the Origins mod), but Better Combat makes some aspects of combative origins very difficult to code. It would be very convenient if we could disable the improved combat for players using said Origin, but your current configuration means either everyone has the combat or nobody does. We need a way to stop specific players from using it.
