### ISSUE TITLE
Decrease Movement speed when attacking depending on the weapon type

### ISSUE THREAD

**Issue by DakotaPride** [ZsoltMolnarrr/BetterCombat#45]
I personally feel that it may make combat better for 1, but it would also fix an 'issue' with third-person or viewing the animations outside of first-person. When you attack while moving, it looks a bit wonky (for lack of a better word).

**Comment by ZsoltMolnarrr** [comment]
Better Combat does not modify the attack cooldown of weapons (aka weapon speed).
Weapon speed is specified using Minecraft Vanilla attack cooldown attribute, upon the creation of the item. So if a mod adds a weapon that mod decides about the speed itself, Better Combat does nothing in this regard.

Please use discord for discussion, not github.

**Comment by ZsoltMolnarrr** [comment]
Hey @DakotaPride ,
I completely misunderstood your feature request. Sorry for closing prematurely.
I am considering to add this feature.
I still suggest to continue the conversation on discord.

**Comment by Sweenus** [comment]
> Hey @DakotaPride , I completely misunderstood your feature request. Sorry for closing prematurely. I am considering to add this feature. I still suggest to continue the conversation on discord.

Is it possible to disconnect the upper body animation from the legs, so that you can still have a walking animation while attacking? Not sure how feasible that is to achieve, but it would be neat.

**Comment by ZsoltMolnarrr** [comment]
This feature was released, however it is not specific to weapon type.
