### ISSUE TITLE
1.18.2 client gets kicked from server because hand is null

### ISSUE THREAD

**Issue by DadoIrie** [ZsoltMolnarrr/BetterCombat#46]
server doesn't crash but client gets kicked when getting killed by mod 
![image](https://user-images.githubusercontent.com/61109153/184454076-3e5d87e3-a0b4-4af3-934f-43359ce7e101.png)
https://mclo.gs/PtyT0sW
happening at line 2084

**Comment by DadoIrie** [comment]
as this log above still used 1.0.7 updated better combat to 1.0.12 ... same error
server log: https://mclo.gs/KPvOiQ7 (starting at line 2060)

EDIT: happens when dual wielding btw
3 times the same procedure and 3 times the same outcome ... died - teleported to death location - clicked on grave - got re-equipped - first swing > client gets kicked from server and server still standing ... server not crashing

EDIT: client log: https://mclo.gs/n4LmXWW

EDIT 2 days after: https://mclo.gs/qUPz5io (line 1220 - server side script) client doesn't say anything regarding this but here's just in case also the client's log https://mclo.gs/8VRSvBZ

might be an an important factor here in order to track down the issue:

I'm using you are in grave danger mod which places the sword back to its offhand if it was in the offhand when died ... and after picking up the grave attacking the error and kick from server happens 
it doesn't happen all the time tho ... sometimes it happens also when getting killed

also testing this entirely with dual wielding swords

mentioning that because (even tho not knowing java) I did spot some 'hand' with 'null' checks in the GitHub repo

hope this helps

**Comment by DadoIrie** [comment]
<strike>I might have finally found conflict issue here with that hand is null crash ... I gave up searching for it and decided to wait till better combat might fix this and was playing a bit around with rpg difficulty (https://www.curseforge.com/minecraft/mc-mods/rpgdifficulty) and difficulty plus (https://www.curseforge.com/minecraft/mc-mods/difficultyplus) and since both do add mobs the possibility to spawn with equipped armor and weapon 
tested it by dying over and over and over again and no crash nor error ... all the time I thought about players hand and didn't considered mobs hand ... at least when removing those mods it didn't crashed anymore ... could something be into that ... please look into that ... if it's mobs hand than woudl it be possible excluding  mobs from the hand checks? 
I'm here just reaching and hope I got something

EDIT: but then again I might have found the conflicting mods, but that doesn't mean that that mobs hand is getting checked, because it does crash when the player is dying or picking up the dual swords and crashes upon first attack move</strike>

EDIT2: happened again 👎

**Comment by ZsoltMolnarrr** [comment]
I was testing this issue on 1.19.1, encountered no such issue.
Could you please confirm this only affects 1.18.2 version?

**Comment by ZsoltMolnarrr** [comment]
Fixed by 1.0.13
