### ISSUE TITLE
Attack animations incorrectly mixing with sneaking

### ISSUE THREAD

**Issue by weirdo1275** [ZsoltMolnarrr/BetterCombat#47]
Attack animation while sneaking in 3rd person seems wrong

https://user-images.githubusercontent.com/109478582/184500667-489e60d4-c1f9-4c20-a5c3-96cc5908d5b8.mp4

**Comment by ZsoltMolnarrr** [comment]
Hello
This is a known issue, thanks for reporting tho.
Hard to fix, I will spend more time on it when I can.
