### ISSUE TITLE
Capes should not be rendered in first person

### ISSUE THREAD

**Issue by Nokunami** [ZsoltMolnarrr/BetterCombat#5]
when attacking the capes render
![2022-07-21_00 59 25](https://user-images.githubusercontent.com/107538383/180040340-5070ca0d-ae94-45a4-9c03-0c649473f42c.png)

**Comment by Nokunami** [comment]
cape*

**Comment by ZsoltMolnarrr** [comment]
PlayerEntityModel
    private final ModelPart cloak;
    private final ModelPart ear;
