### ISSUE TITLE
Incompatible with The Box Trot

### ISSUE THREAD

**Issue by JumpStartFartHam** [ZsoltMolnarrr/BetterCombat#52]
Just a quick note! I've found that using Better Combat and The Box Trot mods on the same profile causes some minor visual issues. While wearing a barrel on your head, some clipping occurs that causes the player's head to still be visible - this occurs during attack animations which is to be expected, but it also occurs while simply standing, walking, running, etc.

A fix would be cool, but at the very least I figured it would be good to note that a compatibility issue exists here. I'll be posting on the other mod's issues page as well to inform the devs there.

If it's important, this is on Minecraft version 1.19, Fabric version 0.14.9, and Better Combat version 1.0.13

![2022-08-19_11 03 21](https://user-images.githubusercontent.com/70125767/185660779-4e682ff4-253e-4da7-820c-4c231d8c9f42.png)

![2022-08-19_11 03 09](https://user-images.githubusercontent.com/70125767/185660738-7e80a294-44ff-4060-8855-b7b8cb729e5c.png)
.

**Comment by ZsoltMolnarrr** [comment]
Will be fixed in the next release
