### ISSUE TITLE
tooltip bug

### ISSUE THREAD

**Issue by LILPRINCES** [ZsoltMolnarrr/BetterCombat#56]
![image](https://user-images.githubusercontent.com/60571513/185785618-b42a7181-693a-442d-92f0-1b9cb3fbc928.png) no hide

![image](https://user-images.githubusercontent.com/60571513/185785605-16161cb8-4d6d-47cc-9aaf-dc7cd31635b7.png) hide

When I set hide attribute modifiers, the attack range will still appear in tooltip

**Comment by ZsoltMolnarrr** [comment]
Please update to the latest version, where this bug is fixed.
If the latest version has this issue, feel free to reopen the issue.
