### ISSUE TITLE
[Feature]  Configurable windup time

### ISSUE THREAD

**Issue by LuciusofLegend** [ZsoltMolnarrr/BetterCombat#57]
You know what would be great?  A setting in the server json file that controls the point in the animation where a hit is registered :)

**Comment by ZsoltMolnarrr** [comment]
Hello!
Weapon attribute files specify the windup duration for each attack individually.
The field is called `upswing`.

You can change weapon attribute files on the server side, and they will be synchronized with clients upon connecting.

However! Changing `upswing` values will not change the tipping point of the animations, hence those will be detached, resulting in earlier performed hits than what the animations indicate.

Please describe what the observed problem is on your server, so I can assess what a real solution can be.

**Comment by LuciusofLegend** [comment]
Hi, the only problem was that I didn't notice such a setting.  If I look again I'm sure I'll see it.  I don't mind that the animation will look a little weird :)
