### ISSUE TITLE
Missing first person attack animations

### ISSUE THREAD

**Issue by slammaja** [ZsoltMolnarrr/BetterCombat#58]
**Minecraft version** - 1.18.2
**Mod loader** - Fabric 0.14.8
**Mod version** - 1.0.3 and up
**I am using the latest version available** - yes, tried with the newest version

**Describe the bug**
Missing animation in first person view, third person works fine.

**To Reproduce**
1. Attack in first person view
2. Item slightly moves down and up, attack sound plays.

The mod causing this is First-person Model (Forge/Fabric) version 2.1.2, with version 2.1.0 bug is present as well, but if I use version 1.0.2 of Better Combat, there is no issue.

**Comment by ZsoltMolnarrr** [comment]
Please provide additional information.
Which mod causes this incompatibility?
Without more information, I cannot fix the issue.

**Comment by slammaja** [comment]
It's caused by First-person Model version 2.1.2 without this mod there are attack animations in first person. But animations are present when using First-person Model mod and Better Combat 1.0.2. Anyway removing that mod fixes the issue, I don´t know if it is problem on side of First-person Model mod od Better Combat mod. Your mod way too awesome to play without, so First-person Model mod has to go.

**Comment by ZsoltMolnarrr** [comment]
When FirstpersonModel is installed, Better Combat disables its own first person attack animation rendering entirely, to allow FirstpersonModel to do this instead.

I tested the versions you mentioned, and I cannot see any issues.
Is it possible that FirstpersonModel is installed but not actually enabled?

**Comment by slammaja** [comment]
Oh so it is intended feature, I didn't know. Then there's probably no issue. Sometimes when I'm using Firstperson Model mod I need to disable it (switch back to vanilla first person view) beacause the view is obstructed by held item for instance and in that case there are no attack animations in vanilla first person view ( with Firstperson Model mod installed but disabled via in game button). I was confused because in Better Combat 1.0.2 it was possible to play with Firstperson Model mod installed and disabled and still have attack animations in vanilla first person view. I believe this "issue" can be closed then. I really appreciate your willingness to help. Thank you for great mod and clarifying the problem.
