### ISSUE TITLE
[Forge] Firstperson Model

### ISSUE THREAD

**Issue by supershorty1** [ZsoltMolnarrr/BetterCombat#59]
**Minecraft version** - 1.18.2
**Mod loader** - forge_20.1.73
**Mod version** - 1.1.0
**I am using the latest version available** - yes

**Describe the bug**
when useing First-person Model with Better Combat,arm was rendered twice and body won't render

**To Reproduce**
install First-person Model and Better Combat

**Expected behavior**
see only 2arms and my chest

**Screenshots or video recordings**
![79QE4%6P_O)HGXGYSE92`SY](https://user-images.githubusercontent.com/111652379/186303476-f929f1ba-50b9-4d23-8c34-af9ac9ea7084.png)

**Additional context**

**Comment by RichPrune** [comment]
huh, thats strange, mine worked flawlessly and im on 1.18.2 fabric AND i have not enough animations installed. does this only happen when you swing your sword

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thanks for reporting, this is a Forge specific issue.
Looks like it can be fixed.
