### ISSUE TITLE
Head is visible in First Person whilst Twilight Forest (Forge) is installed

### ISSUE THREAD

**Issue by chronosacaria** [ZsoltMolnarrr/BetterCombat#60]
**Minecraft version** - 1.18.2
**Mod loader** - Forge 40.1.73
**Mod version** - 1.1.0+1.18.2
**I am using the latest version available** - Yes

**Describe the bug**
Whilst in first person and having Twilight Forest installed, whenever the player attacks, their head comes into the view.

**To Reproduce**
1. Install Better Combat
2. Install Twilight Forest
3. Swing weapon
4. See back of head

**Expected behavior**
That the head should not come into view whilst attacking in first person

**Screenshots or video recordings**
![TwilightForestBetterCombatIncompat](https://user-images.githubusercontent.com/67794130/186467026-dc0f932f-050a-44e0-851a-ea015b1c4373.png)

**Additional context**
Not really

**Comment by ZsoltMolnarrr** [comment]
This issue needs to be fixed by Twilight forest, their Trophy renderer causes it.
There is nothing I can do to fix it.
An example of the bugfix already exists in the Fabric port of their project.

**Comment by HockeyZman2000** [comment]
will someone open up an issue on their github and reference this here so we can get it fixed? i tried but don't know how to reference an issue from a different repository

**Comment by chronosacaria** [comment]
Okay, I've passed the issue along to TeamTwlight

**Comment by HockeyZman2000** [comment]
Thank you!!!

**Comment by WenXin20** [comment]
It looks like twilight forest is fixing it for 1.19 only

**Comment by chronosacaria** [comment]
Oh okay, so it has been fixed as much as it will be :)
