### ISSUE TITLE
Can't hit mobs

### ISSUE THREAD

**Issue by DanMeadWasTaken** [ZsoltMolnarrr/BetterCombat#63]
minecraft version: 1.19.2
loader: Fabric
mod version: 1.1.0
I am using the latest version available on curseforge.

Cannot hit any mobs, regardless of whether I am in third person or first person. 

Load the mods listed in the report, and try to hit something with a weapon (has been tried with diamond axe and diamond sword)

The expected behavior is for the player to be able to hit things. 

The log:
https://paste.ee/p/IPDCG

**Comment by chronosacaria** [comment]
@DanMeadWasTaken I see Carpet in your list of mods. Are you on a server? If so, do you have Better Combat installed on both?

**Comment by ZsoltMolnarrr** [comment]
@DanMeadWasTaken are you playing on a server?
Does the server have the mod installed?

**Comment by DanMeadWasTaken** [comment]
@ZsoltMolnarrr @chronosacaria It's in single player, not on multiplayer, I use carpet mod for auto crafting and such. Without better combat, i can hit things just fine, With it, I can't seem to actually hit anything, I move around, I swing repeatedly and even tried holding down, and it just doesn't hit.

**Comment by ZsoltMolnarrr** [comment]
This is an interesting issue.
You have lots of mods installed, I cannot tell which one would cause this incompatibility.

If you could find which mod causes this problem, than I could fix it. :)

**Comment by ZsoltMolnarrr** [comment]
Please provide additional data or context, otherwise I have to close the issue.

**Comment by DanMeadWasTaken** [comment]
I can start going through the pack today (it's almost 8am and I have classes) yesterday was very busy so I didn't have time to check GitHub. I'll find out which mod is having the conflict before the day is over, as I have to do that for a couple other mods too.

**Comment by DanMeadWasTaken** [comment]
Alright, so after almost an hour and a half of testing, the issue is with multi-connect. Which i use to connect to a vanilla server which is on 1.19.1, so it'd be much appreciated if that could be fixed, but i wouldn't blame ya if it can't be fixed

**Comment by ZsoltMolnarrr** [comment]
This mod is not a cosmetic upgrade to be used on Vanilla servers.
CurseForge and Modrinth pages explicitly state `SERVER SIDE INSTALLATION REQUIRED`.
No vanilla compatible, stripped down verison will be implemented.
