### ISSUE TITLE
[Fabric/Quilt] Invisible body when sleeping

### ISSUE THREAD

**Issue by SplendidAlakey** [ZsoltMolnarrr/BetterCombat#67]
**Minecraft version** - 1.19.2
**Mod loader** - Quilt 0.17.3 and Fabric 0.14.9
**Mod version** - 1.1.0
**I am using the latest version available** - ✅

**Describe the bug**

With the mod installed, player's body is not visible when sleeping.

**To Reproduce**

1. Go to bed

**Expected behavior**

![2022-08-25_14 00 51](https://user-images.githubusercontent.com/86702831/186658923-9c7f7b7b-a364-4a71-8674-9e907c38653b.png)

**Screenshots or video recordings**

![2022-08-25_13 56 55](https://user-images.githubusercontent.com/86702831/186659268-7fc0c1ce-3c2b-4be5-9eee-408dc76570d9.png)

**Additional context**

The issue is reproducible on Fabric and Quilt. Here are logs for both Fabric and Quilt, if necessary: https://gist.github.com/Footage2-Amply-Pounce/4d594efcd092ae5b1b6915a397a0c94b

Adding standalone, newer version of Player Animator library doesn't help.

**Comment by ZsoltMolnarrr** [comment]
This is a valid issue.
However fairly low priority.
