### ISSUE TITLE
Mod Crashing when opened on Fabric. Ver- 1.19.2

### ISSUE THREAD

**Issue by FoxyShowtz** [ZsoltMolnarrr/BetterCombat#69]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric (fabric loader  0.14.9-1.19.2)
**Mod version** - bettercombat-fabric-1.1.0+1.19
**I am using the latest version available** - Yes

**Description of the bug**

Whenever I try to open the game it says that the mod 'Better Combat' requires any version of Fabric, which is missing. Even though I have Fabric

**To Reproduce**
1. Go to 'Minecraft Launcher and choose Fabric Loader'
2. Click on 'Play'
3. See error

**Expected behavior**
The game will crash.

**Screenshot**
![Screenshot 2022-08-25 114219](https://user-images.githubusercontent.com/112089722/186668591-4eb9b3f0-7d5f-41f1-be1d-46e3284bed71.png)

**Additional context**
I have some other mods and the required mods, but they shouldn't be a problem for this mod.
**The other mods I have are:**
Sodium- Fabric
Iris - Fabric
Litematica - Fabric
Malilib - Fabric
DistantHorizons - Fabric
Cloth-Config - Fabric
ModMenu - Fabric
player-animation-lib - Fabric

**Comment by SplendidAlakey** [comment]
"Any version of fabric" refers to [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3936024), not Fabric Loader.

**Comment by ZsoltMolnarrr** [comment]
This is not a crash.
This is Fabric mod loader telling you to install Fabric API https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3936024
Yes it phrases a bit vaguely.
