### ISSUE TITLE
[Suggestions] Better Shield FP & Jump Attack

### ISSUE THREAD

**Issue by Jusey1** [ZsoltMolnarrr/BetterCombat#70]
**I read project readme, checked client side and server side configurations, and no such feature exists** - Yes.

**Is your feature request related to a problem? Please describe.**
So, I got the mod working and already added a compatibility patch with my Waraxes (Waraxes are one-handed axes, Battle Axes are the two-handed ones) but after playtesting the animations and the mod. I notice two slight issues, not big ones mind you, just two things that bothers me:

1. The shield in first-person animation can get really weird while attacking and in the way.
2. Doing crit-attacks feels wonky now as the animation doesn't feel natural for the attack style and it is easier to miss since you have to connect with the animation.

**Describe the solution you'd like**
My solutions for the two is as follows:
1. Disable the off-hand first-person animations while holding any shields so that it doesn't get in the way so much during attack animations.
2. Add in an unique animation when jumping down onto an target to make the jump-critical hit more reliable to pull off cause right now, you have to start the attack before jumping with certain weapons and it looks a bit wonky.

**Describe alternatives you've considered**
I really only have one alternative for the shield idea which is simply just hide the shield in first-person when attacking.

**Additional context**
Context picture for the shield and how it can block vision during attack animations:
![Untitled](https://user-images.githubusercontent.com/61861078/186713905-33fa72b8-1da2-4f61-856a-0fd4fe0e6d5c.png)

And with some modded shields:
![Untitled2](https://user-images.githubusercontent.com/61861078/186714567-dc5ef2cf-4753-4aca-ac9a-38d55d59ade8.png)
![Untitled3](https://user-images.githubusercontent.com/61861078/186715089-c65709c6-0848-45aa-a7ad-bb06f36f7485.png)
![Untitled4](https://user-images.githubusercontent.com/61861078/186715103-cea57e90-64cd-49d4-b037-d12ac6d78d10.png)

**Comment by ZsoltMolnarrr** [comment]
1. I cannot disable first person animations, the mod would become unplayable. One handed animations could be changed to lift other arm in a lower angle, so shields wouldn't get in the way by so much. Maybe I'll look this later, however this is a really minor issue.
2. Creating jump specific variants for every single attack animation is an unfeasibly large task.
Moreover I disagree with the problem. Getting critical strikes have become more natural due to the upswing (aka windup) mechanic. Sure it requires a bit of practice, but it likely will not change, because there is no more technically found solution.

**Comment by Jusey1** [comment]
Honestly, the jump specific variants isn't that big of a deal anyways so I'm not too worried about it as a whole, my bigger concern was the shield... Cause yeah, it can get pretty bad with how much the shield covers your vision.

**Comment by ZsoltMolnarrr** [comment]
I'll investigate later how much of an obstruction really is the shield problem, and how can we solve it properly.

**Comment by Jusey1** [comment]
Okay, til then I'll probably stick to 3rd person when using a shield.

**Comment by ZsoltMolnarrr** [comment]
Hey @Jusey1 someone proposed a solution for the shield problem.
I just implemented it.
