### ISSUE TITLE
Figura mod causes first-person to be unusable

### ISSUE THREAD

**Issue by cy1der** [ZsoltMolnarrr/BetterCombat#71]
**Minecraft version** - 1.18.2
**Mod loader** - Fabric
**Mod version** - 1.1.0
**I am using the latest version available** - yes

**Describe the bug**
The figura mod causes the whole body to render in first-person. Which the head becomes visible from the inside when you attack. 

**To Reproduce**
1. Download the mod, figura 0.0.8, and simply swords 1.05
2. Keep default configurations
3. Attack with any weapon

**Expected behavior**
The head should not render

**Screenshots or video recordings**
[drive.google.com video](https://drive.google.com/file/d/1euB8VC6o9XfmRwY02sOFyk5sAIUjq8K-/view?usp=sharing)

**Additional context**
n/a

**Comment by ZsoltMolnarrr** [comment]
Any mod that is trying to change the player rendering in such radical way is incompatible PlayerAnimator (the animation library used by Better Combat).
I am sorry I have to `breaks` entry for this mod.
