### ISSUE TITLE
Multiple Incompatibilities

### ISSUE THREAD

**Issue by Alkiasan** [ZsoltMolnarrr/BetterCombat#74]
**Minecraft version** - 1.18.2
**Mod loader** - Quilt
**Mod version** - Latest
**I am using the latest version available** - Yes

**Describe the bug**
The game seems to crash on launch when launched alongside my mods. Seems to be a mixin error but i'm not too sure. Crash doesn't happen when BetterCombat is removed.

**To Reproduce**
1. Start Game
2. See crash

**Expected behavior**
Game starts properly

**Additional context**
Both of these mods seem to be relating to the crash, and these are both seperate reports.
The second report was generated after the first incompatible mod (Carrier) was removed.
Seems to be  a mixin conflict but i'm not too sure, Is this fixable?
Thanks,
Logs attached:
https://hastebin.com/geqifejape.yaml
https://hastebin.com/hozapiweni.yaml

**Comment by ZsoltMolnarrr** [comment]
None of these errors seem to be Better Combat related. I'm not sure how I can help.

**Comment by Alkiasan** [comment]
> playerAnimator-onlyBend.mixins.json:LivingEntityRenderRedirect from mod (unknown)

This is in the first report, seems to be an issue with this mixin?

**Comment by ZsoltMolnarrr** [comment]
Please update EmoteCraft to the latest version.

**Comment by Alkiasan** [comment]
Oh yeah, that fixed the issue, thank you! ^^
