### ISSUE TITLE
[Forge 1.18.2] Crash on Load

### ISSUE THREAD

**Issue by chosti-factor** [ZsoltMolnarrr/BetterCombat#75]
When I add Better Combat to my modlist, it crashes early. It won't generate a crashlog. Apparently it's missing a dependency:

[main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: playeranimator

The log:
https://pastebin.com/GFWrirMr

The debug log:
https://pastebin.com/Q1vG27PN

Crash won't happen without Better Combat. I have the latest version of cloth-config for 1.18.2. Can't figure this one out. Any help is appreciated.

**Comment by PlouklaPenguin** [comment]
Have you installed [https://www.curseforge.com/minecraft/mc-mods/playeranimator](url)?

**Comment by chosti-factor** [comment]
Hi PloukaPenguin! I did not install it because I didn't see it listed as a dependency. I still looked for it, but for some reason curseforge search didn't find it. Thank you very much for providing a link! :) Maybe the author should list it as a dependency in curseforge?

**Comment by chosti-factor** [comment]
@PlouklaPenguin It loads perfectly with the playeranimator dependency. Thank you for showing me where to find it.
