### ISSUE TITLE
Can't harvest "grassy plants" with Farmers Delight knife

### ISSUE THREAD

**Issue by alexhowell610** [ZsoltMolnarrr/BetterCombat#76]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.1.0
**I am using the latest version available** - Yes

With the Farmers Delight mod you need to harvest "grassy plants" (their wiki calls them this) with a knife. When Better Combat installed you just swing at it, you cant actually harvest anything.

**Comment by ZsoltMolnarrr** [comment]
Hello!
You have 2 options.
A.) Disable Swing thru grass (client side settings) while using the knife
B.) Open `/config/bettercombat/fallback_compatibility.json`. Add the id of farmer's delight knife to the blacklist regex.
