### ISSUE TITLE
Forge 41.1.0 1.19 / Optifine

### ISSUE THREAD

**Issue by Piccolina80** [ZsoltMolnarrr/BetterCombat#79]
Hello.
I use the forge 41.1.0 version with Optifine, but inserted the mod and started minecraft, the game closes.
OUTPUT CODE 1.
I also added player animation lib.
What's the problem?

**Comment by ZsoltMolnarrr** [comment]
Optifine is a closed source mod, there is absolutely nothing I can do to help or fix it.
Please try using other versions.

**Comment by Piccolina80** [comment]
Thanks you
