### ISSUE TITLE
[Render Bug] FPP - Head renders whilst using Twilight Forest

### ISSUE THREAD

**Issue by Cixon** [ZsoltMolnarrr/BetterCombat#81]
**Minecraft version**
1.18.2

**Mod loader**
Forge

**Mod version**
Lastest - 1.1.1

**Describe the bug**
Player Head renders in FPP.

**To Reproduce**
1. Install Twilight Forest with Better combat.
2. Launch Minecraft.
3. See results.

**Screenshots or video recordings**
![Screenshot (121)](https://user-images.githubusercontent.com/69068153/187009757-1985b32c-c89c-4e06-8782-f3bb775cb9a9.png)

**Comment by ZsoltMolnarrr** [comment]
Please update to the latest version of Twilight Forest, they solved the issue recently.
