### ISSUE TITLE
Game crashing when mod is installed.

### ISSUE THREAD

**Issue by KaykenJr** [ZsoltMolnarrr/BetterCombat#84]
**Minecraft version** - 1.18.2
**Mod loader** - Forge 40.1.73
**Mod version** - 1.1.1
**I am using the latest version available** -  Yes

**Describe the bug**
when the mod is installed and you try to launch the game you get a crash.

**Screenshots or video recordings**
Log file here
[latest.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/9440607/latest.log)

**Additional context**
I crashed with other mods and without other mods.

**Comment by ZsoltMolnarrr** [comment]
This issue has nothing to do with Better Combat.
Please make sure to install the correct dependencies. Looks like you were trying to install Fabric version of Cloth Config.

**Comment by KaykenJr** [comment]
sorry about that but the thing is even with creative core and cloth config that's FORGE it still crashes.
[latest.log](https://github.com/ZsoltMolnarrr/BetterCombat/files/9445837/latest.log)
![image](https://user-images.githubusercontent.com/112353962/187236607-d7893a13-21a7-46d0-9d6b-a31a4f76826f.png)

**Comment by ZsoltMolnarrr** [comment]
You are missing the PlayerAnimator. Link on CurseForge page.

**Comment by KaykenJr** [comment]
SO SORRY. I was on the curse forge game support and they said it was the mod's fault and said to delete it so I thought it was the mod. it works now.
