### ISSUE TITLE
[forge] [1.18.2] No tinker construct compatiblity.

### ISSUE THREAD

**Issue by Cixon** [ZsoltMolnarrr/BetterCombat#85]
**Bug:** Mod doesn't recognize tinker construct weapons.

**My config Here:**
[fallback_compatibility.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9441510/fallback_compatibility.txt)

**Comment by Reimnop** [comment]
Experienced this same issue, fixed it with a custom datapack. I'll share it here, hope it helps!
[TConstructBetterCompat.zip](https://github.com/ZsoltMolnarrr/BetterCombat/files/9441948/TConstructBetterCompat.zip)

**Comment by ZsoltMolnarrr** [comment]
Failing to use GitHub issue template.
