### ISSUE TITLE
Corrupted fallback compatibility configuration crashes on launch

### ISSUE THREAD

**Issue by Cixon** [ZsoltMolnarrr/BetterCombat#86]
**version v1.1.1**

**crash-report:**
[crash-2022-08-29_00.10.58-fml.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9441519/crash-2022-08-29_00.10.58-fml.txt)

**config:**
[fallback_compatibility.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9441518/fallback_compatibility.txt)

**Comment by ZsoltMolnarrr** [comment]
`Failure message: Better Combat (bettercombat) has failed to load correctly`

Are you using some kind of mod that is trying to accelerate the launch procedure of the game?

**Comment by Cixon** [comment]
> `Failure message: Better Combat (bettercombat) has failed to load correctly`
> 
> Are you using some kind of mod that is trying to accelerate the launch procedure of the game?

I use this:
https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded

maybe your mod and this is not compatible?

**Comment by ZsoltMolnarrr** [comment]
I have never tested it, its most likely not compatible.
Please try without it, report back.

**Comment by ZsoltMolnarrr** [comment]
By the way, your fallback config is corrupted.
`item_id_regex` accepts a single string value.
So instead this:
`"sweater:mythril_sword", "sweater:soul_steel_sword", "tconstruct:sword", "twilightforest:fiery_sword", "twilightforest:ice_sword", "twilightforest:ironwood_sword", "twilightforest:knightmetal_sword", "twilightforest:steeleaf_sword"`

Use this:
`"sweater:mythril_sword|sweater:soul_steel_sword|tconstruct:sword|twilightforest:fiery_sword|twilightforest:ice_sword|twilightforest:ironwood_sword|twilightforest:knightmetal_sword|twilightforest:steeleaf_sword"`

**Comment by ZsoltMolnarrr** [comment]
This corrupt JSON causes your crash BTW.
I will fix the crash side, but you have to make a valid JSON for fallback compatibility.

**Comment by Cixon** [comment]
> This corrupt JSON causes your crash BTW. I will fix the crash side, but you have to make a valid JSON for fallback compatibility.

had no idea, thank you so much!
