### ISSUE TITLE
I see my head when i swing

### ISSUE THREAD

**Issue by Landrozaum** [ZsoltMolnarrr/BetterCombat#87]
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.1.1
**I am using the latest version available** - yes

**Describe the bug**
I literally see myhead when i swing any item in first person, this is weird.

**To Reproduce**
1. Open Minecraft Forge with bettercombat-forge-1.1.1+1.18.2 and player-animation-lib-forge-0.3.5
2. Open any world.
3. Swing with a sword in the air.
4. The bug happens: your body is shown when swinging.

**Expected behavior**
Only swing the sword normaly, without the body being shown

**Screenshots or video recordings**
Swinging with a sword:
![2022-08-29_01 36 05](https://user-images.githubusercontent.com/76543480/187125007-6196daaa-16e7-414a-8620-3c33d970c86c.png)

**Additional context**
I'm not sure if it's a conflict with some other mod, because when I try to open the game with BetterCombat, the game crashes
![image](https://user-images.githubusercontent.com/76543480/187125220-4d9c28e7-4422-4c4a-be84-e3ee6c8bb7d7.png)

**Comment by Landrozaum** [comment]
2 errors in one.

**Comment by ZsoltMolnarrr** [comment]
Please only report 1 problem under 1 GitHub issue.
Please update Twilight Forest to latest version, to avoid the renderer error.
