### ISSUE TITLE
Joiner's uuid is forced to change

### ISSUE THREAD

**Issue by dher383** [ZsoltMolnarrr/BetterCombat#88]
**Minecraft version** - 1.19.2
**Mod loader** - forge
**Mod version** - bettercombat-forge-1.1.1+1.19
**I am using the latest version available** - yes

**Describe the bug**
When i and my friend playing multiplayer using only BetterCombat mod and its hard dependencies,my friend is the host and i am the joiner.I found my stuff was missing!
When i and my friend removed these mod,my stuff was back.
After a few test on my own computer,i found that your mod or one of your dependencies make joiner's uuid changes.

**To Reproduce**(my test)
1. Player A host a save and Player B join in.
2. Check Player B's uuid.
3. Make Player B create his own world.
4. Check Player B's uuid again.
5. The two uuid are different.

**Expected behavior**
none.

**Screenshots or video recordings**
 player B's uuid after joining player A's world:
![1](https://user-images.githubusercontent.com/100601694/187187767-fce0d6ba-0400-4aa5-aca7-6729e031bf2c.png)

player B's uuid when in singleplayer:
![2](https://user-images.githubusercontent.com/100601694/187188055-32543c8d-8e4b-41b6-bb6b-d756b4418e13.png)

**Additional context**
none

**Comment by ZsoltMolnarrr** [comment]
Sorry, could you explain how is this Better Combat related?
I don't my code does anything in this regards.

**Comment by dher383** [comment]
idk,maybe one of the dependencies cause that,i think it's [playerAnimator](https://www.curseforge.com/minecraft/mc-mods/playeranimator)

**Comment by ZsoltMolnarrr** [comment]
Is this causing any problem in practice?

**Comment by dher383** [comment]
yes,after removing this mod,my stuff is back

**Comment by dher383** [comment]
emm...i'm dumb, I found that I did too few tests, when i join my friend's world again with bettercombat mod, my stuff isn't missing. Sorry to bother you.
