### ISSUE TITLE
Tetra compatible

### ISSUE THREAD

**Issue by Dr-WeiAL** [ZsoltMolnarrr/BetterCombat#89]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
I found this mod is not compatible with tetra's weapons

**Describe the solution you'd like**
I want this mod to recognize tetra's weapons

**Describe alternatives you've considered**
Since the tetra mod can assemble weapons, identifying it's weapons is a problem, but I saw a mod
This way of working should solve the problem
https://www.curseforge.com/minecraft/mc-mods/epic-fight-nbt-integration

**Additional context**
https://www.curseforge.com/minecraft/mc-mods/tetra

**Comment by ZsoltMolnarrr** [comment]
Hi,
This was recently released: https://www.curseforge.com/minecraft/mc-mods/tetratic-combat
You can give it a try :)

**Comment by Dr-WeiAL** [comment]
Oh, thanks! I didn't know this mod existed before

**Comment by ZsoltMolnarrr** [comment]
It was released very recently.

**Comment by Dr-WeiAL** [comment]
Well, I saw it was posted 12 hours ago, thanks again!
Then I will close this issue

**Comment by gardenappl** [comment]
It looks like the author of Tetratic Combat does not plan to update their mod to 1.20, so I think this issue can be reopened.

**Comment by Dr-WeiAL** [comment]
> It looks like the author of Tetratic Combat does not plan to update their mod to 1.20, so I think this issue can be reopened.

Yeah, you're right.

**Comment by ZsoltMolnarrr** [comment]
Why was this issue reopened?
What am I expected to do?:)

**Comment by Dr-WeiAL** [comment]
hmm... Tetratic Combat is no longer updated, which means 1.20 doesn't have Tetra compatible, so that's why it was reopened
The modder of Tetratic Combat created Truly Modular and he said he won't update Tetratic Combat anymore

**Comment by Dr-WeiAL** [comment]
Huh? I just realized it's a repository for BetterCombat, maybe I shouldn't say that here?
I'm sorry to bother you.
