### ISSUE TITLE
Easy compatibility via datapacks and resource packs

### ISSUE THREAD

**Issue by Catomax262** [ZsoltMolnarrr/BetterCombat#91]
**I read project readme, checked client side and server side configurations, and no such feature exists** - NO

**Is your feature request related to a problem? Please describe.**
I kinda hate the compatibility method you used, having to build an entire mod with this as a core but having no modding knowledge is kinda hard to use. There can't be compatibility between other mods but rather only with mods built around using this mod.

**Describe the solution you'd like**
Datapacks. Instead of having to make a full mod why not using datapacks? They can be used to take control over ID handling, for example an item from a mod is a hammer, but it somehow ends with the axe animation because of its ID: examplemod:hammer_axe. 
In the other hand, resource packs would be used to configure the animation and sounds. (i think it's possible to do this but just clarifying) Datapacks can also be used to make whole new categories using json files and then resource packs to add the animations and sounds.

**Describe alternatives you've considered**
I think datapacks and resource packs are enough.

**Additional context**
n/a

**Comment by ZsoltMolnarrr** [comment]
The integration guide doesn't address this specifically, compatibility can be added via datapacks, many people have done such things.
I suggest joining the Better Combat discord to get help with this.
I will extended the readme when I have time.

**Comment by Catomax262** [comment]
I can say, please specify datapack usage in the integration guide.

**Comment by ZsoltMolnarrr** [comment]
It works exactly the same.
