### ISSUE TITLE
[Fabric 1.19.2] Crash on startup

### ISSUE THREAD

**Issue by MarioAndWeegee3** [ZsoltMolnarrr/BetterCombat#92]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - 1.2.0+1.19
**I am using the latest version available** - yes

**Describe the bug**
The game window does not open. There is an error in [the log](https://mclo.gs/AkQDjEs)

**To Reproduce**
1. Install Better Combat and all of its dependencies
2. Attempt to launch the game
3. The game crashes

**Expected behavior**
The game should start normally

**Comment by ZsoltMolnarrr** [comment]
Hello!
I wasn't able to reproduce the issue.
What version of PlayerAnimator are you using?

**Comment by ZsoltMolnarrr** [comment]
Looks like the issue is, that I forgot to specify PlayerAnimator as a Fabric dependency.

**Comment by ZsoltMolnarrr** [comment]
Thank you for noticing the issue!
I will republish v1.2.0 that will give a clear instruction by Fabric to install the required dependency, instead of crashing.
