### ISSUE TITLE
[Fabric] Attack request error logs

### ISSUE THREAD

**Issue by OkinawaGaijin** [ZsoltMolnarrr/BetterCombat#93]
**Minecraft version** - 1.19.2
**Mod loader** - Fabric
**Mod version** - 0.14.9
**Fabric API** - 0.60.0+1.19.2
**BetterCombat** - 1.2.0+1.19
**PlayerAnimator Lib** - 0.3.5
**I am using the latest version available** - Yes

**Describe the bug**
I am not yet sure that this is indeed related to BetterCombat, as I get neither a crash nor a valid latest log.

The issue: At some point, the integrated Server just freezes up. Entities stop moving, Blocks stop dropping items, new Chunks don't load. I can still walk around, do stuff. But the world won't interact with me.

Issue happened since I upgraded BetterCombat to today's version, which also requires the playeranimations library.

Since I don't crash, I don't get a crash log. I looked into my latest.log to see what the last entries are:
The following stack is from the last moment I knew it was working (just killed a zombie, then ran around, killed a creeper and stopped to eat some meat), to the final entry in the log.

[20:32:07] [Server thread/INFO]: ItsJacky has made the advancement [§2Monster Hunter§f]
[20:32:07] [Render thread/INFO]: [System] [CHAT] ItsJacky has made the advancement [§2Monster Hunter§f]
[20:32:08] [Render thread/INFO]: Loaded 691 advancements
[20:32:08] [Render thread/ERROR]: missing entity for data tracking ClientWorld minecraft:overworld28354
[20:32:12] [Render thread/ERROR]: missing entity for data tracking ClientWorld minecraft:overworld28353
[20:32:14] [Render thread/INFO]: Loaded 692 advancements
[20:32:29] [Render thread/INFO]: Loaded 692 advancements
[20:32:29] [Render thread/ERROR]: missing entity for data tracking ClientWorld minecraft:overworld28444
[20:32:47] [Render thread/INFO]: Loaded 692 advancements
[20:32:47] [Render thread/ERROR]: missing entity for data tracking ClientWorld minecraft:overworld28355
[20:32:48] [Render thread/INFO]: Loaded 695 advancements
[20:33:22] [Render thread/INFO]: Loaded 695 advancements
[20:34:48] [Netty Server IO #1/ERROR]: Server handling Packets.C2S_AttackRequest - No current attack hand!
[20:34:48] [Netty Server IO #1/ERROR]: Combo count: 0 is dual wielding: false
[20:34:48] [Netty Server IO #1/ERROR]: Main-hand stack: 4 cooked_beef
[20:34:48] [Netty Server IO #1/ERROR]: Off-hand stack: 1 air
[20:34:48] [Netty Server IO #1/ERROR]: Server handling Packets.C2S_AttackRequest - No current attack hand!
[20:34:48] [Netty Server IO #1/ERROR]: Combo count: 1 is dual wielding: false
[20:34:48] [Netty Server IO #1/ERROR]: Main-hand stack: 4 cooked_beef
[20:34:48] [Netty Server IO #1/ERROR]: Off-hand stack: 1 air
[20:34:48] [Netty Server IO #1/ERROR]: Server handling Packets.C2S_AttackRequest - No current attack hand!
[20:34:48] [Netty Server IO #1/ERROR]: Combo count: 2 is dual wielding: false
[20:34:48] [Netty Server IO #1/ERROR]: Main-hand stack: 4 cooked_beef
[20:34:48] [Netty Server IO #1/ERROR]: Off-hand stack: 1 air
[20:34:49] [Netty Server IO #1/ERROR]: Server handling Packets.C2S_AttackRequest - No current attack hand!
[20:34:49] [Netty Server IO #1/ERROR]: Combo count: 0 is dual wielding: false
[20:34:49] [Netty Server IO #1/ERROR]: Main-hand stack: 4 cooked_beef
[20:34:49] [Netty Server IO #1/ERROR]: Off-hand stack: 1 air
[20:34:50] [Netty Server IO #1/ERROR]: Server handling Packets.C2S_AttackRequest - No current attack hand!
[20:34:50] [Netty Server IO #1/ERROR]: Combo count: 1 is dual wielding: false
[20:34:50] [Netty Server IO #1/ERROR]: Main-hand stack: 4 cooked_beef
[20:34:50] [Netty Server IO #1/ERROR]: Off-hand stack: 1 air
[20:34:51] [Netty Server IO #1/ERROR]: Server handling Packets.C2S_AttackRequest - No current attack hand!
[20:34:51] [Netty Server IO #1/ERROR]: Combo count: 0 is dual wielding: false
[20:34:51] [Netty Server IO #1/ERROR]: Main-hand stack: 4 cooked_beef
[20:34:51] [Netty Server IO #1/ERROR]: Off-hand stack: 1 air
[20:34:51] [Netty Server IO #1/ERROR]: Server handling Packets.C2S_AttackRequest - No current attack hand!
[20:34:51] [Netty Server IO #1/ERROR]: Combo count: 1 is dual wielding: false
[20:34:51] [Netty Server IO #1/ERROR]: Main-hand stack: 4 cooked_beef
[20:34:51] [Netty Server IO #1/ERROR]: Off-hand stack: 1 air

Since this log throws a lot of errors that sound like they have to do with BetterCombat, I was wondering if those cause the internal server to deadlock or freeze.

Another alternative would be that the freeze already builds up earlier and the latest log entries are just a result of BetterCombat trying to communicate with a deadlocked server.

Prior entries that catch my eye are mainly spams like:
[Render thread/ERROR]: missing entity for data tracking ClientWorld minecraft:overworld23545
for which I either suspect ImmersivePortals or my mix of BYG, Terralith, William Wythers Overhauled Overworld. But I don't know quite exactly what this line means.

I've also attached a compiled list of my current mods, shaders and resource packs just in case.

[Modlist_Latest.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9461247/Modlist_Latest.txt)

**Comment by OkinawaGaijin** [comment]
Okay, might be completely unrelated. Sorry to bother. I just downgraded Daedalus to jump back in the world I just had this issue with and it tells me that errors in currently selected Datapacks prevented the world from loading.

I suspect my world-gen is messed up and then slowly kills the integrated server. I will sort this out on my end.

**Comment by ZsoltMolnarrr** [comment]
Interesting logs.
Looks like a player is trying to send attack requests to the server while not holding any attributed weapon.
I don't know how is this possible to happen.
Maybe you have some server optimiser mod installed, that drops some of the held item sync packets.
I will take a look at this.

Maybe there is a way to improve stability, by relying less implicitly on the vanilla held item sync.

**Comment by ZsoltMolnarrr** [comment]
Based on these error logs, I don't think Better Combat is responsible for the deadlock.

**Comment by OkinawaGaijin** [comment]
I will have to sort out so many mods to find out which one (or which combination) is causing this. I'm crying right now.

According to Google, the missing entity for data tracking ClientWorld happens when A) a mod that adds mobs is removed and new chunks are loaded that still expect said mob to show up (but I started a fresh world) or multiple mods add entities under the same ID.

I am clueless. I hope that my guess is right and the mix of using WWOO, Terralith, BetterNether and BetterEnd (those add their own worldgen entry) as well as BYG just corrupted the worldgen somehow and cause this issue to happen.

Now doing a run without WWOO and trying to see if it happens again.

**Comment by OkinawaGaijin** [comment]
okay, this is weird.

I have done two things:
1. Disable WWOO by adding .disabled after the jar to make it an unreadable file format
2. Replace the latest BetterCombat by Daedalus with the last version I had in my recycle bin (1.1.1)

Now I've been playing a new map for about 30 minutes. Latest log entries are these:

missing entity for data tracking ClientWorld minecraft:overworld
Ignoring unknown attribute 'forge:entity_gravity'
Re-processed riding packet
Received passengers for unknown entity

But I have no issues with the integrated server actually locking up and entities not responding. I've killed as many mobs as I could find. I used creative mode to fly to the edge of rendered chunks. I picked stuff from chests and destroyed trees and blocks.

The log is getting these entries, but even after 30 minutes I have no timeout issues.

**Comment by OkinawaGaijin** [comment]
Added in WWOO again, recreated the crashed world. It happened again. I'm gonna recreate the exact same seed without WWOO again now. If it doesn't crash, I may have already found the issue.

Edit: and my log, right after I teleported to a village close by has an incredible amount of "reclaimed X bytes at Address Y that were leaked from an unknown location (logging is disabled)

So that looks like a big memory leak.

Also: Can't keep up! Is the server overloaded? Running 3085ms or 61 ticks behind

I think you can close this issue at your discretion, as it is definitely not a BetterCombat issue.

**Comment by ZsoltMolnarrr** [comment]
Hey @OkinawaGaijin !
It would be very helpful if you could reproduce the Better Combat related error logs you sent, using the latest release `1.2.1`.

**Comment by OkinawaGaijin** [comment]
I can do that, but these only showed up once after my integrated server deadlocked from that still unresolved unrelated issue.

I've just deleted most of my structure adding mods as well as one mod that added fish and was only experimental for the fabric branch.

Now I flew around a new map for a good hour or so, loading more than 6900 chunks, fighting mobs, doing all the usual stuff. Teleporting all over the place to throw off the chunk loading. No server freeze.

But the latest.log entries about missing entity for data tracking and the memoryleak stuff are unchanged, still present.

I'm at wits end.

But I'll update your mod and let you know if it shows in any way or form in the next logs.

**Comment by Ninty9** [comment]
Hi, i know this is closed but i managed to recreate this.
It seems to cause a crash whenver someone is loading chunks (to an extent that it lags the server) at the same time as swapping items while attacking)

```
26.09 22:14:28 [Server] Server thread/[WARN] ninty moved too quickly! 4.426064933007453,0.6480365881674999,9.526614764505211
26.09 22:14:28 [Server] Server thread/[WARN] Exlann moved too quickly! 0.5720877907073714,-2.0,-9.824916554530091
26.09 22:14:28 [Server] Server thread/[INFO] [ninty: Set own game mode to Creative Mode]
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Server handling Packets.C2S_AttackRequest - No current attack hand!
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Combo count: 0 is dual wielding: false
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Main-hand stack: 17 bread
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Off-hand stack: 1 air
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Selected slot server: 1 | client: 2
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Server handling Packets.C2S_AttackRequest - No current attack hand!
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Combo count: 1 is dual wielding: false
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Main-hand stack: 17 bread
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Off-hand stack: 1 air
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Selected slot server: 1 | client: 2
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Server handling Packets.C2S_AttackRequest - No current attack hand!
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Combo count: 2 is dual wielding: false
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Main-hand stack: 17 bread
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Off-hand stack: 1 air
26.09 22:14:30 [Server] Netty Epoll Server IO #0/[ERROR] Selected slot server: 1 | client: 2
26.09 22:14:31 [Server] Server thread/[WARN] ninty moved too quickly! 0.5104514474576476,3.7466194923685094,9.379667664802582
26.09 22:14:34 [Server] Server thread/[WARN] ninty moved too quickly! 1.4552889204017347,3.1909013491950162,10.42598651072467
26.09 22:14:37 [Server] Server thread/[WARN] ninty moved too quickly! -1.0149425904499907,3.3594124209233485,9.503882133600655
26.09 22:14:38 [Server] Server thread/[WARN] ninty moved too quickly! -7.688723948482902,6.937520841563526,2.0917748674555696
26.09 22:14:40 [Server] Server thread/[WARN] Can't keep up! Is the server overloaded? Running 14075ms or 281 ticks behind
26.09 22:14:57 [Server] Server thread/[WARN] ninty moved too quickly! 0.25852741027027903,-2.1277875399255066,17.286263483969833
26.09 22:14:57 [Server] Server thread/[WARN] Exlann moved too quickly! 2.2983051287370984,-3.252203340253729,-9.220468138850265
26.09 22:14:59 [Server] Server thread/[WARN] Can't keep up! Is the server overloaded? Running 4137ms or 82 ticks behind
26.09 22:15:01 [Server] Server thread/[WARN] ninty moved too quickly! 7.976559939448599,0.0,6.313500907032221
26.09 22:15:03 [Server] Server thread/[WARN] ninty moved too quickly! 8.263993927050812,0.0,6.9695206417788995
26.09 22:15:04 [Server] Server thread/[ERROR] POI data mismatch: never registered at class_2338{x=162, y=7, z=1790}
26.09 22:15:08 [Server] Server thread/[WARN] ninty moved too quickly! 8.157159994726499,0.0,6.398558417250342
26.09 22:15:11 [PebbleHost Loader] Server Stopped
```

It could be that this is not directly caused by bettercombat but it is definitely related to it.
