### ISSUE TITLE
[Forge 1.18.2] Crash for last version

### ISSUE THREAD

**Issue by XionioXMaster** [ZsoltMolnarrr/BetterCombat#97]
**Minecraft version** - 1 18 2
**Mod loader** - Forge 40.1.76
**Mod version** - 1.3.1
**I am using the latest version available** - Yes

**Describe the bug**
I don't understand how this happened on the server

**To Reproduce**
1. I don't understand

**Expected behavior**

**Screenshots or video recordings**

**Additional context**
https://pastebin.com/jyNLhRr4

**Comment by ZsoltMolnarrr** [comment]
Hello!
This crash while happens inside the action handler of a Better Combat attack request packet, there is no sign of any Better Combat features causing this crash.
