### ISSUE TITLE
Passable Foliage Compatible

### ISSUE THREAD

**Issue by Dr-WeiAL** [ZsoltMolnarrr/BetterCombat#98]
**I read project readme, checked client side and server side configurations, and no such feature exists** - YES

**Is your feature request related to a problem? Please describe.**
Weapons can ignore grass, but can't ignore leaves

**Describe the solution you'd like**
maybe adding a configuration that ignores leaves would be better?

**Describe alternatives you've considered**
Or will this feature be enabled when the mod is detected?

**Additional context**
Sometimes using a weapon to attack will hit a block, which makes it impossible to swing the weapon, but if you turn on isMiningWithWeaponsEnabled, the axe will not be able to chop down trees. Is there any solution for this?

**Comment by ZsoltMolnarrr** [comment]
Hello!
Thank you for the suggestion, after long consideration I have to reject it, sorry.
My remarks:
- It would be a fragile, difficult to maintain integration to create this feature
- Not being able to swing your weapon while passing thru leaves is good I think, it adds to the realism of the mod
- Mine with weapons can be assigned a hotkey
